### ISSUE TITLE
no CUDA-capable device is detected

### ISSUE THREAD

**Issue by happyflyingfish** [NVIDIA/DALI#1161]
Hi, I'm trying to execute the official example, but getting stuck with error:

```python
class RandomRotatedGPUPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(RandomRotatedGPUPipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        self.input = ops.FileReader(file_root = image_dir, file_list = image_dir + '/file_list.txt', random_shuffle = True, initial_fill = 21)
        self.decode = ops.ImageDecoder(device = 'cpu', output_type = types.RGB)
        self.rotate = ops.Rotate(device = "gpu")
        self.rng = ops.Uniform(range = (-10.0, 10.0))

    def define_graph(self):
        jpegs, labels = self.input()
        images = self.decode(jpegs)
        angle = self.rng()
        rotated_images = self.rotate(images.gpu(), angle = angle)
        return (rotated_images, labels)

pipe = RandomRotatedGPUPipeline(batch_size, 1, 0)
pipe.build()

pipe_out = pipe.run()
print(pipe_out)

>>>

[<nvidia.dali.backend_impl.TensorListGPU object at 0x7fdca4f05c00>, <nvidia.dali.backend_impl.TensorListCPU object at 0x7fdca4f05c38>]
```

The above code can be correctly executed, but when I execute the following VideoPipe code

```python
batch_size=2
sequence_length=8

initial_prefetch_size=10
video_directory = "video_files"

video_files=[video_directory + '/' + f for f in os.listdir(video_directory)]

shuffle=True

n_iter=6

class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data, shuffle):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id, seed=16)
        self.input = ops.VideoReader(device="gpu", filenames=data, sequence_length=sequence_length,
                                     shard_id=0, num_shards=1,
                                     random_shuffle=shuffle, initial_fill=initial_prefetch_size)


    def define_graph(self):
        output = self.input(name="Reader")
        return output


pipe = VideoPipe(batch_size=batch_size, num_threads=2, device_id=0, data=video_files, shuffle=shuffle)
pipe.build()
for i in range(n_iter):
    pipe_out = pipe.run()
    sequences_out = pipe_out[0].as_cpu().as_array()
    print(sequences_out.shape)

>>>
Traceback (most recent call last):
  File "video_test.py", line 40, in <module>
    pipe_out = pipe.run()
  File "/usr/local/app/anaconda3/envs/torch1.1.0-py3.6.5/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 367, in run
    return self.outputs()
  File "/usr/local/app/anaconda3/envs/torch1.1.0-py3.6.5/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 285, in outputs
    return self._outputs()
  File "/usr/local/app/anaconda3/envs/torch1.1.0-py3.6.5/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 355, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline: CUDA driver API error CUDA_ERROR_NO_DEVICE (100):
no CUDA-capable device is detected
Current pipeline object is no longer valid.
```

Spec:

- nvidia-dali==0.12.0
- CentOS Linux release 7.2 (Final)
- Cuda 9.0 Driver Version: 384.81
- ffmpeg version 4.0

**Comment by awolant** [comment]
Hi, thanks for the question.
Video reader uses driver API, so maybe there is something wrong with the NVIDIA driver on your machine. We discussed it and it's really hard to tell without more information.
Are you building DALI locally or using ready binary?

**Comment by happyflyingfish** [comment]
I Installed prebuilt DALI packages through the below command

```bash
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/9.0 nvidia-dali
```

**Comment by awolant** [comment]
That looks right. 
If you can, maybe try to reinstall the driver.
It's a bit weird that you did not get the file and the line number in you error message. I will try to find out why in  the meantime.

**Comment by JanuszL** [comment]
Can you also provide the GPU model you have?

**Comment by JanuszL** [comment]
If that still doesn't work for you please reopen.

**Comment by TiankaiHang** [comment]
I rebuild the docker and get such error information as above.

**Comment by JanuszL** [comment]
Hi @TiankaiHang,

Without more details, it is hard to tell where the problem is. I think it would be best if you would ask the question in https://github.com/NVIDIA/nvidia-docker project.
