### ISSUE TITLE
Error by using PythonOperator: PythonFunction error: TypeError: _feed_fn() missing 1 required positional argument: 'feed_val'

### ISSUE THREAD

**Issue by kometa-triatlon** [NVIDIA/DALI#1185]
According to [this example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html#GPU-operator-implementation), creating a Python operator must be straightforward.

However, when I am trying to build a pipeline with it, it fails. Here is the code:

```
self.dummy_pyop = ops.PythonFunction(function=lambda x: x)                                                                                                                                                                              
...

boxes = self.dummy_pyop(boxes) 
```
The error I got:

```
DALI daliShareOutput(&pipe_handle_) failed: Critical error in pipeline: Error in thread 5: PythonFunction error: TypeError: _feed_fn() missing 1 required positional argument: 'feed_val'
Current pipeline object is no longer valid.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: DALI daliShareOutput(&pipe_handle_) failed: Critical error in pipeline: Error in thread 5: PythonFunction error: TypeError: _feed_fn() missing 1 required positional argument: 'feed_val'
Current pipeline object is no longer valid.
         [[{{node Dali}}]]
         [[{{node concat}}]]

```
I am using DALI v0.12.0
Without this operation the pipeline works just fine.

**Comment by banasraf** [comment]
Hi,
The operator construction and usage looks fine. Could you provide an example of pipeline where the problem appears?

**Comment by kometa-triatlon** [comment]
An excerpt from my pipeline related to boxes and labels:

```
class SSDInputPipeline(Pipeline):
    def __init__(self, tfrecords, tfrecords_idx, ...):

        super(SSDInputPipeline, self).__init__(batch_size, num_threads, device_id)

        features = {
            TfExampleFields.image_encoded: tfrecord.FixedLenFeature((), tfrecord.string, ''),
            # Object boxes and classes.
            TfExampleFields.object_bbox_xmin: tfrecord.VarLenFeature(tfrecord.float32, 0.0),
            TfExampleFields.object_bbox_ymin: tfrecord.VarLenFeature(tfrecord.float32, 0.0),
            TfExampleFields.object_bbox_xmax: tfrecord.VarLenFeature(tfrecord.float32, 0.0),
            TfExampleFields.object_bbox_ymax: tfrecord.VarLenFeature(tfrecord.float32, 0.0),
            TfExampleFields.object_class_label: tfrecord.VarLenFeature(tfrecord.int64, -1),
        }

        self.input = ops.TFRecordReader(path=tfrecords,
                                        index_path=tfrecords_idx,
                                        features=features,
                                        shard_id=shard_id,
                                        num_shards=num_shards,
                                        random_shuffle=False,
                                        device='cpu')

        self.concat = ops.ConcatAndClipBboxCoords(device="cpu")
        self.cast_to_int32 = ops.Cast(device="cpu", dtype=types.INT32)
        self.bbox_paste = ops.BBoxPaste(device='cpu', ltrb=True)
        self.bbox_flip = ops.BbFlip(device='cpu', ltrb=True)

        self.filter_boxes_labels = ops.PythonFunction(function=lambda x: x)

def define_graph(self):
        # Read images and labels
        inputs = self.input(name="Reader")
        images = inputs[TfExampleFields.image_encoded]
        xmin = inputs[TfExampleFields.object_bbox_xmin]
        ymin = inputs[TfExampleFields.object_bbox_ymin]
        xmax = inputs[TfExampleFields.object_bbox_xmax]
        ymax = inputs[TfExampleFields.object_bbox_ymax]
        labels = inputs[TfExampleFields.object_class_label]

        boxes = self.concat(xmin, ymin, xmax, ymax)
        labels = self.cast_to_int32(labels)
        boxes = self.bbox_flip(boxes, horizontal=do_flip)

        paste_ratio = self.paste_ratio()
        paste_pos_x = self.paste_pos()
        paste_pos_y = self.paste_pos()
        boxes = self.bbox_paste(boxes, ratio=paste_ratio, paste_x=paste_pos_x, paste_y=paste_pos_y)
        crop_begin, crop_size, boxes, labels = self.crop(boxes, labels)

        boxes = self.filter_boxes_labels(boxes)  # <- error here
        return images.gpu(), boxes.gpu(), labels.gpu()
```

Here, `ConcatAndClipBboxCoords` is my custom CPU operator that concatenates four coords tensors into a single tensor.

So, without the python function, everything works fine, I can visualize the data etc. Inclusion of the Python operator causes the aforementioned error.

**Comment by awolant** [comment]
This pipeline looks ok for me. How do you run it? From the error messages I'm assuming you are using TensorFlow?

**Comment by kometa-triatlon** [comment]
Yes, TensorFlow/Keras inside NVIDIA docker image tf-19.06.

**Comment by kometa-triatlon** [comment]
Ok, it seems to be a problem with my custom docker image.
If I use `nvcr.io/nvidia/tensorflow:19.03-py3` with DALI upgraded to 0.12, it works.

**Comment by awolant** [comment]
I modified one of our [TensorFlow examples](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/tensorflow/tensorflow-plugin-sparse-tensor.html) to use `ops.PythonFunction(function=lambda x: x)` and was able to run it on the GPU without any issues from the `PythonFunction`. I was using TensorFlow 1.14
Could you provide complete reproduction of this issue?

**Comment by awolant** [comment]
Ok, in that case, I'm closing the issue for now. If you experience more problems with this please reopen.
