### ISSUE TITLE
NVJPEG error "3" Current pipeline object is no longer valid

### ISSUE THREAD

**Issue by XiaotaoChen** [NVIDIA/DALI#119]
i use MXNet1.3.0 to train resnext50 by fp16 in 4*TitanV. To support the speed of TitanV, i replace the source io named `ImageRecordIter` with DALI. At beginning，the program running normally. After a while, it tells the error:

```
root INFO Epoch[0] Rank[0] Batch[20] TotalIter[20] Train:0.002(0.003)	kv_sync:0.072(0.673)	data:0.209(0.881)	iter_total_time:0.226(0.936)	Speed: 1366.24 samples/sec	accuracy=0.000744	top_k_accuracy_5=0.005580
root INFO Epoch[0] Rank[0] Batch[40] TotalIter[40] Train:0.003(0.003)	kv_sync:0.091(0.392)	data:0.113(0.524)	iter_total_time:0.234(0.607)	Speed: 1953.21 samples/sec	accuracy=0.001270	top_k_accuracy_5=0.004883
......
......
root INFO Epoch[0] Rank[0] Batch[920] TotalIter[920] Train:0.003(0.003)	kv_sync:0.094(0.119)	data:0.097(0.153)	iter_total_time:0.214(0.234)	Speed: 2371.57 samples/sec	accuracy=0.001465	top_k_accuracy_5=0.004687
root INFO Epoch[0] Rank[0] Batch[940] TotalIter[940] Train:0.002(0.003)	kv_sync:0.114(0.119)	data:0.117(0.153)	iter_total_time:0.224(0.233)	Speed: 2390.58 samples/sec	accuracy=0.000879	top_k_accuracy_5=0.004297
Traceback (most recent call last):
  File "/mnt/truenas/scratch/xiaotao.chen/softwares/resnet.mxnet/train.py", line 156, in <module>
    main(config)
  File "/mnt/truenas/scratch/xiaotao.chen/softwares/resnet.mxnet/train.py", line 151, in main
    kvstore=kv)
  File "/mnt/truenas/scratch/xiaotao.chen/softwares/resnet.mxnet/core/solver.py", line 113, in fit
    next_data_batch = next(data_iter)
  File "/mnt/truenas/scratch/xiaotao.chen/py-envs/py27_mxnet0722/local/lib/python2.7/site-packages/nvidia/dali/plugin/mxnet.py", line 169, in next
    return self.__next__();
  File "/mnt/truenas/scratch/xiaotao.chen/py-envs/py27_mxnet0722/local/lib/python2.7/site-packages/nvidia/dali/plugin/mxnet.py", line 126, in __next__
    outputs.append(p.outputs())
  File "/mnt/truenas/scratch/xiaotao.chen/py-envs/py27_mxnet0722/local/lib/python2.7/site-packages/nvidia/dali/pipeline.py", line 239, in outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline: [/mnt/truenas/scratch/xiaotao.chen/DALI/dali/pipeline/operators/decoder/nvjpeg_decoder.h:167] NVJPEG error "3"
Current pipeline object is no longer valid.
./resnet.train.sh: line 13: 21009 Segmentation fault      (core dumped) python /mnt/truenas/scratch/xiaotao.chen/softwares/resnet.mxnet/train.py
```
According to the log info, it seems like NVJPEG bug. 

**My environment as follows.**

```shell
Package                       Version   Location                                                                            
----------------------------- --------- ------------------------------------------------------------------------------------
backports.functools-lru-cache 1.5       
certifi                       2018.8.13 
chardet                       3.0.4     
cycler                        0.10.0    
Cython                        0.28.5    
easydict                      1.7       
future                        0.16.0    
futures                       3.2.0     
graphviz                      0.8.4     
idna                          2.6       
kiwisolver                    1.0.1     
matplotlib                    2.2.3     
mxnet                         1.3.0     /mnt/truenas/scratch/xiaotao.chen/softwares/mxnet0722/python                        
numpy                         1.15.0    
nvidia-dali                   0.3.0     /mnt/truenas/scratch/xiaotao.chen/py-envs/py27_mxnet0722/lib/python2.7/site-packages
opencv-python                 3.4.2.17  
pip                           18.0      
pkg-resources                 0.0.0     
pyarrow                       0.10.0    
pyparsing                     2.2.0     
python-dateutil               2.7.3     
pytz                          2018.5    
pyzmq                         17.1.2    
requests                      2.18.4    
setuptools                    40.0.0    
six                           1.11.0    
subprocess32                  3.5.2     
urllib3                       1.22      
wheel                         0.31.1    
zmq                           0.0.0 
```

the main configuration as below:

```shell
 'batch_size': 512,
 'data_dir': '/mnt/truenas/scratch/algorithm/datasets/imagenet/imagenet_data_new/',
 'data_nthreads': 16,
 'data_type': 'float16',
 'dataset': 'imagenet',
 'depth': 50,
 'gpu_list': [0, 1, 2, 3],
 'grad_scale': 128.0,
 'image_shape': [3, 224, 224],
 'kv_store': 'device',
 'multi_precision': True,
 'network': 'resnet'
```

the image's shape in `train.rec` and `val.rec` keep in it's source, i haven't do any process while using `im2rec.py` to transform `ILSVRC2012`  to  `rec`

my `dali iter` implementation is here.

```python
import nvidia.dali.ops as ops
import nvidia.dali.types as types
from nvidia.dali.plugin.mxnet import DALIClassificationIterator

class HybridTrainPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus, db_folder):
        super(HybridTrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        self.input = ops.MXNetReader(path=[os.path.join(db_folder, "train.rec")], index_path=[os.path.join(db_folder, "train.idx")],
                                     random_shuffle=True, shard_id=device_id, num_shards=num_gpus)
        self.decode = ops.nvJPEGDecoder(device="mixed", output_type=types.RGB)
        self.rrc = ops.RandomResizedCrop(device="gpu", size=(224, 224))
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(224, 224),
                                            image_type=types.RGB,
                                            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                            std=[0.229 * 255,0.224 * 255,0.225 * 255])
        self.coin = ops.CoinFlip(probability=0.5)

    def define_graph(self):
        rng = self.coin()
        self.jpegs, self.labels = self.input(name = "Reader")
        images = self.decode(self.jpegs)
        images = self.rrc(images)
        output = self.cmnp(images, mirror = rng)
        return [output, self.labels]

class  HybridValPipe (Pipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus, db_folder):
        super(HybridValPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        self.input = ops.MXNetReader(path=[os.path.join(db_folder, "val.rec")], index_path=[os.path.join(db_folder, "val.idx")],
                                     random_shuffle=False, shard_id=device_id, num_shards=num_gpus)
        self.decode = ops.nvJPEGDecoder(device="mixed", output_type=types.RGB)
        self.rs = ops.Resize(device="gpu", resize_x=256, resize_y=256)
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(224, 224),
                                            image_type=types.RGB,
                                            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                            std=[0.229 * 255,0.224 * 255,0.225 * 255])

    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        images = self.rs(images)
        output = self.cmnp(images)
        return [output, self.labels]


def get_dali_iter(data_dir, batch_size, kv, image_shape, num_gpus):
    num_examples = 1281167
    trainpipes = [HybridTrainPipe(batch_size=batch_size//num_gpus, num_threads=2, device_id=i, num_gpus=num_gpus, db_folder=data_dir) for i in range(num_gpus)]
    valpipes = [HybridValPipe(batch_size=batch_size//num_gpus, num_threads=2, device_id=i, num_gpus=num_gpus, db_folder=data_dir) for i in range(num_gpus)]

    trainpipes[0].build()
    valpipes[0].build()

    print("Training pipeline epoch size: {}".format(trainpipes[0].epoch_size("Reader")))
    print("Validation pipeline epoch size: {}".format(valpipes[0].epoch_size("Reader")))

    dali_train_iter = DALIClassificationIterator(trainpipes, trainpipes[0].epoch_size("Reader"))
    dali_val_iter = DALIClassificationIterator(valpipes, valpipes[0].epoch_size("Reader"))

    return dali_train_iter, dali_val_iter, num_examples
```

**Comment by ptrendx** [comment]
Hi @XiaotaoChen, thank you for submitting this issue. We are aware of this and were already working on a fix:
- please make sure you have 0.1.4 version of nvJPEG installed (apparently the website was not updated for some reason and it still lists 0.1.3, which should be fixed very soon, but in the meantime you can use direct link to it as in our Dockerfile: https://github.com/NVIDIA/DALI/blob/master/Dockerfile.deps#L91)
- even after this fix to nvJPEG there is a problem with one of the images in the ImageNet dataset, which is actually a PNG (even though it is named as JPEG), where a bug in DALI prevents fallback to host decoder. Please try applying PR #118 and testing with that.

**Comment by XiaotaoChen** [comment]
Thanks sincerely. @ptrendx According to your advice, i compile dali source code which commit-id is a66396e with nvJPEG0.1.4. It running normally in the whole dataset. But it's accuracy is terrible as below.

    root INFO Epoch[0] Train-accuracy=0.000977
    root INFO Epoch[0] Train-top_k_accuracy_5=0.007812
    root WARNING DALI iterator does not support resetting while epoch is not finished. Ignoring...
    root INFO Epoch[0] Validation-accuracy=0.000996
    root INFO Epoch[0] Validation-top_k_accuracy_5=0.004982
    ...
    root INFO Epoch[1] Train-accuracy=0.000000
    root INFO Epoch[1] Train-top_k_accuracy_5=0.007812
    root INFO Epoch[1] Validation-accuracy=0.000996
    root INFO Epoch[1] Validation-top_k_accuracy_5=0.005042
    ...
    root INFO Epoch[2] Train-accuracy=0.000000
    root INFO Epoch[2] Train-top_k_accuracy_5=0.011719
    root INFO Epoch[2] Validation-accuracy=0.001007
    root INFO Epoch[2] Validation-top_k_accuracy_5=0.004973

here is the accuracy that i trained resnext50 by fp16 in 2*TitanV,  Using `ImageRecordIter`

    root INFO Epoch[0] Train-accuracy=0.208008
    root INFO Epoch[0] Train-top_k_accuracy_5=0.440430
    root INFO Epoch[0] Validation-accuracy=0.243822
    root INFO Epoch[0] Validation-top_k_accuracy_5=0.482820
    ...
    root INFO Epoch[1] Train-accuracy=0.362305
    root INFO Epoch[1] Train-top_k_accuracy_5=0.595703
    root INFO Epoch[1] Validation-accuracy=0.382372
    root INFO Epoch[1] Validation-top_k_accuracy_5=0.650220
    ...
    root INFO Epoch[2] Train-accuracy=0.386719
    root INFO Epoch[2] Train-top_k_accuracy_5=0.641927
    root INFO Epoch[2] Validation-accuracy=0.431490
    root INFO Epoch[2] Validation-top_k_accuracy_5=0.693690
    ...
    root INFO Epoch[99] Train-accuracy=0.809896
    root INFO Epoch[99] Train-top_k_accuracy_5=0.941406
    root INFO Epoch[99] Validation-accuracy=0.760961
    root INFO Epoch[99] Validation-top_k_accuracy_5=0.928332

I will try to migrate our data enhancement method in `ImageRecordIter` to DALI, but I am not sure if DALI supports all enhancement methods.

**Comment by ptrendx** [comment]
Hmmm, accuracy being 0 is certainly unexpected. Could you share the DALI pipeline you use and equivalent call to ImageRecordIter? Also, how did you prepare recordio files (just with `--passthrough` or some more options)?
I will try to repro this.

**Comment by ptrendx** [comment]
I did not notice previously that you showed the DALI pipeline used in the first post.
I just made a similar test with the top of release_v0.2 branch and recordios made with just `--pass-through` flag:
```
python /opt/mxnet/tools/im2rec.py --list --recursive train /data/imagenet/train-jpeg
python /opt/mxnet/tools/im2rec.py --pass-through --num-thread 40 train /data/imagenet/train-jpeg
```
and similarly for validation. I use training script based off of `example/image-classification/train_imagenet.py` from MXNet and I can get good accuracy:
```
INFO:root:Epoch[29] Train-accuracy=0.525684
INFO:root:Epoch[29] Validation-accuracy=0.487427
```
So there are still a few possibilities:
 - top of master is somehow broken vs top of release_v0.2 branch (could you check with a version built from that branch @XiaotaoChen ? I will check too)
 - I noticed you use grad_scale - do you use it for both DALI and ImageRecordIter testing? It should not be required and one needs to be careful when using it since it overwrites the default scaling of the gradient by the batch size. Could you try without setting this parameter?

**Comment by XiaotaoChen** [comment]
@ptrendx It's seems like the `grad_scale` setting causes the terrible accuracy. The accuracy increases normally when i remove the `grad_scale` setting. here is the accuracy of running `example/image-classification/train_imagenet.py`

- DALI iter

```shell
INFO:root:Epoch[0] Train-accuracy=0.207031
WARNING:root:DALI iterator does not support resetting while epoch is not finished. Ignoring...
INFO:root:Epoch[0] Validation-accuracy=0.195033
...
INFO:root:Epoch[1] Train-accuracy=0.325195
INFO:root:Epoch[1] Validation-accuracy=0.314063
...
INFO:root:Epoch[2] Train-accuracy=0.381510
INFO:root:Epoch[2] Validation-accuracy=0.404046
...
INFO:root:Epoch[3] Train-accuracy=0.400391
INFO:root:Epoch[3] Validation-accuracy=0.424625
```

- `ImageRecordIter` with it's default augmentation settings.

```shell
INFO:root:Epoch[0] Train-accuracy=0.268555
INFO:root:Epoch[0] Validation-accuracy=0.241928
...
INFO:root:Epoch[1] Train-accuracy=0.369141
INFO:root:Epoch[1] Validation-accuracy=0.338542
...
INFO:root:Epoch[2] Train-accuracy=0.442708
INFO:root:Epoch[2] Validation-accuracy=0.403425
```

### In addition

my recordios also made with `--pass-through`.

And I test the release_v0.2 code with the validation pipeline in `DALI/docs/examples/mxnet/mxnet-resnet50.ipynb` as below.

```python
class HybridValPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus):
        super(HybridValPipe, self).__init__(batch_size, num_threads, device_id, seed = 12 + device_id)
        self.input = ops.MXNetReader(path = [db_folder+"val.rec"], index_path=[db_folder+"val.idx"],
                                     random_shuffle = False, shard_id = device_id, num_shards = num_gpus)
        self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
        self.cmnp = ops.CropMirrorNormalize(device = "gpu",
                                            output_dtype = types.FLOAT,
                                            output_layout = types.NCHW,
                                            crop = (224, 224),
                                            image_type = types.RGB,
                                            mean = [0.485 * 255,0.456 * 255,0.406 * 255],
                                            std = [0.229 * 255,0.224 * 255,0.225 * 255])

    def define_graph(self):
        self.jpegs, self.labels = self.input(name = "Reader")
        images = self.decode(self.jpegs)
        output = self.cmnp(images)
        return [output, self.labels]
```

it tells error:

```shell
    dali_val_iter = DALIClassificationIterator(valpipes, valpipes[0].epoch_size("Reader"))
  File "/root/cxt/py-envs/py27_mxnet0722/local/lib/python2.7/site-packages/nvidia/dali/plugin/mxnet.py", line 226, in __init__
    data_layout)
  File "/root/cxt/py-envs/py27_mxnet0722/local/lib/python2.7/site-packages/nvidia/dali/plugin/mxnet.py", line 102, in __init__
    self._first_batch = self.next()
  File "/root/cxt/py-envs/py27_mxnet0722/local/lib/python2.7/site-packages/nvidia/dali/plugin/mxnet.py", line 169, in next
    return self.__next__();
  File "/root/cxt/py-envs/py27_mxnet0722/local/lib/python2.7/site-packages/nvidia/dali/plugin/mxnet.py", line 126, in __next__
    outputs.append(p.outputs())
  File "/root/cxt/py-envs/py27_mxnet0722/local/lib/python2.7/site-packages/nvidia/dali/pipeline.py", line 239, in outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline: [/mnt/truenas/scratch/xiaotao.chen/softwares/DALI_v0.2/dali/pipeline/operators/fused/crop_mirror_normalize.cu:349] Assert on "H >= crop_h_" failed
Current pipeline object is no longer valid.
```

After adding `ops.Resize`, like[Error when using not resized RecordIO file. #57 ](https://github.com/NVIDIA/DALI/issues/57). it's normal. the validation pipeline as follow.

```python
class  HybridValPipe (Pipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus, db_folder):
        super(HybridValPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        self.input = ops.MXNetReader(path=[os.path.join(db_folder, "val.rec")], index_path=[os.path.join(db_folder, "val.idx")],
                                     random_shuffle=False, shard_id=device_id, num_shards=num_gpus)
        self.decode = ops.nvJPEGDecoder(device="mixed", output_type=types.RGB)
        self.rs = ops.Resize(device="gpu", resize_x=256, resize_y=256)
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(224, 224),
                                            image_type=types.RGB,
                                            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                            std=[0.229 * 255,0.224 * 255,0.225 * 255])

    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        images = self.rs(images)
        output = self.cmnp(images)
        return [output, self.labels]
```
