### ISSUE TITLE
Question: How to use ops.FileReader to read a directory filled with images but without labels?

### ISSUE THREAD

**Issue by XiaoqiangZhou** [NVIDIA/DALI#1206]
Dear developers,
Thanks for your contribution for building this package. But I have met some problems, could you please help me?

I want to build a pipeline which can read images from a directory, and **there are no labels**, just an ordinary folder filled with images.
It seems `ops.FileReader` could satisfy my demand. But is `ops.FileReader` needs a well-organized folder structure?

I got an error when run my code,
```
read 0 files from 0 directories
Traceback (most recent call last):
  File "dataset_dail.py", line 50, in <module>
    num_gpus=1)
  File "dataset_dail.py", line 40, in get_dataset_iter_dail
    pip_train.build()
  File "/home/zhouxiaoqiang/anaconda3/envs/torch/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 231, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: [/opt/dali/dali/pipeline/operators/reader/loader/file_loader.h:108] Assert on "Size() > 0" failed: No files found.
```
And my codes are as follows:
```
def __init__(***):
        self.input = ops.FileReader(file_root=my_data_dir)
        self.decode = ops.ImageDecoder(device="mixed",output_type=types.RGB)

def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        output = images
        return output
```
`my_data_dir` is a folder like `image_folder/` which consists of `image_folder/001.jpg`, `image_folder/002.jpg`, `image_folder/003.jpg`

Thanks!

**Comment by XiaoqiangZhou** [comment]
The whole codes of this script is listed below, just FYI
```
class HybridTrainPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data_dir, crop, dali_cpu=False, local_rank=0, world_size=1):
        super(HybridTrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        self.input = ops.FileReader(file_root=data_dir, shard_id=local_rank, num_shards=world_size, random_shuffle=True) 
        self.decode = ops.ImageDecoder(device="mixed", 
                                       output_type=types.RGB) # output: HWC
        self.coin = ops.CoinFlip(probability=0.5)
    
    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        import ipdb; ipdb.set_trace()
        images = self.decode(self.jpegs)
        output = images
        return output

def get_dataset_iter_dail(type, image_dir, batch_size, num_threads, device_id, num_gpus, crop, 
                          val_size=256,
                          world_size=1,
                          local_rank=0):
    if type in ['train', 'val', 'test']:
        pip_train = HybridTrainPipe(batch_size=batch_size, num_threads=num_threads, device_id=local_rank,
                                    data_dir=image_dir,
                                    crop=crop, world_size=world_size, local_rank=local_rank)
        pip_train.build()
        import ipdb; ipdb.set_trace()
        dali_iter_train = DALIGenericIterator(pip_train, output_map=["data"], size=pip_train.epoch_size("Reader") // world_size)
        return dali_iter_train

if __name__ == "__main__":
    train_loader = get_dataset_iter_dail(type='train', image_dir='/data3/zhouxiaoqiang/datasets/celeba_hq_images/',                                                  batch_size=16,
                                         num_threads=4, 
                                         crop=256,
                                         device_id=3, 
                                         num_gpus=1)
    for i, data in enumerate(train_loader):
        images = data.cuda(non_blocking=True)
        import ipdb; ipdb.set_trace()
```

**Comment by awolant** [comment]
Hi, thanks for the question.
Yes, `FileReader` requires certain folder structure to work.
For your purpose you can use  [`file_list`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html?highlight=filereader#nvidia.dali.ops.FileReader) parameter of `FileReader`. You could create a file with paths for images and some dummy value for label.
