### ISSUE TITLE
test_operator_crop_mirror_normalize.py failing on x86 and PPC

### ISSUE THREAD

**Issue by aalugore** [NVIDIA/DALI#1349]
Hello. As part of our testing infrastructure, we run a selection of tests from this repo's test directory `DALI/dali/test/python`. Recently we began seeing an error coming from `test_operator_crop_mirror_normalize.py`. We are currently using the DALI code pegged at branch `release_v0.13`. Important to note, we see the exact same error on x86 as we do on PPC. The heart of the error seems to be the calculated `err` value growing greater than the given thresholds `eps`. Below I have pasted the error messages from the two different error types we are seeing. We ran the test via `nose`:

`nosetests test_operator_crop_mirror_normalize.py`

```======================================================================
FAIL: test_operator_crop_mirror_normalize.test_cmn_cpu_vs_gpu(1, DALIDataType.INT32, DALITensorLayout.NHWC, 0.0, [123.675, 116.28, 103.53], [0.229, 0.224, 0.225], False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cmn/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/builder/DALI/dali/test/python/test_operator_crop_mirror_normalize.py", line 70, in check_cmn_cpu_vs_gpu
    batch_size=batch_size, N_iterations=iterations, eps=eps)
  File "/home/builder/DALI/dali/test/python/test_utils.py", line 110, in compare_pipelines
    check_batch(out1_data, out2_data, batch_size, eps)
  File "/home/builder/DALI/dali/test/python/test_utils.py", line 98, in check_batch
    assert(False)
AssertionError:
-------------------- >> begin captured stdout << ---------------------
failed[False] err[0.010489742772108844]

--------------------- >> end captured stdout << ----------------------
```
```
======================================================================
FAIL: test_operator_crop_mirror_normalize.test_cmn_vs_numpy('gpu', 8, DALIDataType.FLOAT, DALITensorLayout.NCHW, 1.0, [123.675, 116.28, 103.53], [58.395, 57.120000000000005, 57.375], True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cmn/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/builder/DALI/dali/test/python/test_operator_crop_mirror_normalize.py", line 214, in check_cmn_vs_numpy
    batch_size=batch_size, N_iterations=iterations)
  File "/home/builder/DALI/dali/test/python/test_utils.py", line 110, in compare_pipelines
    check_batch(out1_data, out2_data, batch_size, eps)
  File "/home/builder/DALI/dali/test/python/test_utils.py", line 98, in check_batch
    assert(False)
AssertionError:
-------------------- >> begin captured stdout << ---------------------
failed[False] err[0.34790971875190735]
Batch at 7 can't be saved as an image
[[[-0.06293353 -0.02868403 -0.86779696 ...  0.41655958 -0.6280504
   -0.30268008]
  [-0.06293353 -0.02868403 -0.88492167 ...  0.41655958 -0.6280504
   -0.3369296 ]
  [-0.06293353 -0.04580878 -0.88492167 ...  0.3994348  -0.6109257
   -0.3711791 ]
  ...
  [-0.16568205 -0.04580878 -0.9191712  ... -0.45680287 -0.76504844
   -1.0390445 ]
  [-0.1828068  -0.04580878 -0.9191712  ... -0.47392762 -0.7136742
   -1.004795  ]
  [-0.1828068  -0.04580878 -0.90204644 ... -0.49105236 -0.6965494
   -1.004795  ]]

 [[ 0.04761904  0.08263305 -0.77521014 ...  0.53781515 -0.5301121
   -0.19747901]
  [ 0.04761904  0.08263305 -0.79271716 ...  0.53781515 -0.5301121
   -0.23249301]
  [ 0.04761904  0.06512605 -0.79271716 ...  0.52030814 -0.5126051
   -0.26750702]
  ...
  [-0.10994399  0.01260504 -0.8802521  ... -0.40756306 -0.7226891
   -1.0028012 ]
  [-0.12745099  0.01260504 -0.8802521  ... -0.42507005 -0.6701681
   -0.96778715]
  [-0.12745099  0.01260504 -0.86274517 ... -0.44257706 -0.6526611
   -0.96778715]]

 [[ 0.19991282  0.2696296  -0.5844009  ...  0.72278863 -0.34039217
   -0.0092375 ]
  [ 0.19991282  0.2696296  -0.60183007 ...  0.72278863 -0.34039217
   -0.04409589]
  [ 0.19991282  0.2522004  -0.60183007 ...  0.70535946 -0.322963
   -0.07895428]
  ...
  [ 0.06047927  0.18248363 -0.7064052  ... -0.23581702 -0.5495425
   -0.8284096 ]
  [ 0.04305008  0.18248363 -0.7064052  ... -0.25324622 -0.4972549
   -0.7935512 ]
  [ 0.04305008  0.18248363 -0.68897605 ... -0.27067542 -0.47982574
   -0.7935512 ]]
[[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  ...
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]]
[[[-0.02868401 -0.86779696 -0.49105236 ... -0.6280504  -0.30268008
   -0.9705455 ]
  [-0.02868401 -0.88492167 -0.47392762 ... -0.6280504  -0.3369296
   -0.9705455 ]
  [-0.04580877 -0.88492167 -0.45680285 ... -0.6109256  -0.37117907
   -0.9705455 ]
  ...
  [-0.04580877 -0.9191712  -0.9191712  ... -0.7650484  -1.0390445
   -0.13143253]
  [-0.04580877 -0.9191712  -0.90204644 ... -0.7136741  -1.004795
   -0.16568205]
  [-0.04580877 -0.90204644 -0.88492167 ... -0.6965494  -1.004795
   -0.2170563 ]]

 [[ 0.08263308 -0.7752101  -0.390056   ... -0.530112   -0.19747898
   -0.8802521 ]
  [ 0.08263308 -0.7927171  -0.37254903 ... -0.530112   -0.23249298
   -0.8802521 ]
  [ 0.06512608 -0.7927171  -0.355042   ... -0.5126051  -0.267507
   -0.8802521 ]
  ...
  [ 0.01260506 -0.8802521  -0.8802521  ... -0.7226891  -1.0028012
   -0.07492995]
  [ 0.01260506 -0.8802521  -0.8627451  ... -0.6701681  -0.96778715
   -0.10994396]
  [ 0.01260506 -0.8627451  -0.8452381  ... -0.6526611  -0.96778715
   -0.16246498]]

 [[ 0.26962966 -0.58440083 -0.20095858 ... -0.3403921  -0.00923745
   -0.688976  ]
  [ 0.26962966 -0.60183    -0.18352939 ... -0.3403921  -0.04409584
   -0.688976  ]
  [ 0.25220045 -0.60183    -0.16610019 ... -0.32296294 -0.07895423
   -0.688976  ]
  ...
  [ 0.18248367 -0.70640516 -0.70640516 ... -0.5495424  -0.82840955
    0.09533771]
  [ 0.18248367 -0.70640516 -0.688976   ... -0.49725488 -0.79355115
    0.06047932]
  [ 0.18248367 -0.688976   -0.6715468  ... -0.47982568 -0.79355115
    0.00819174]]
[[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  ...
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]]

--------------------- >> end captured stdout << ----------------------
```

Has something changed internally that has made this test obsolete? Please let me know if you need any other information.

**Comment by JanuszL** [comment]
Hi,
Could you tell us more about the condition when you started to see this error? You said that you are on `release_v0.13`. Does it mean that tests are from this branch while code is from master or the opposite?
The thing that seems closest to what you see it that we have moved this tests to DALI extra and also found out that numpy reference implementation behaves a bit different than our CPU/GPU code as `np.round` we have used round to the nearest even instead to the nearest as the native code - https://github.com/NVIDIA/DALI/pull/1177.
Regarding `test_operator_crop_mirror_normalize.test_cmn_cpu_vs_gpu` I have no idea.
Could you tell us more about the particular sha you are on, what test data you are using, etc?

**Comment by aalugore** [comment]
Hello again! after looking at your test in DALI_extra and updating `test_operator_crop_mirror_normalize.py` to look like that version, our test passed. Seems like updating the tolerance to 0.02 and then the `np.round` vs `np.float32` fixed it. We will investigate updating our tests to use the ones inside DALI_extra but for now the issue in question is resolved. Thanks @JanuszL !
