### ISSUE TITLE
Tensorflow plugin example error

### ISSUE THREAD

**Issue by gon9031** [NVIDIA/DALI#138]
I followed the Tensorflow example as it is, and an error like this occurred. I don't know why.

RUN: CaffeReadPipeline
Traceback (most recent call last):
  File "train_image_classifier2.py", line 107, in <module>
    test_batch = get_batch_test_dali(BATCH_SIZE, pipe_name)
  File "train_image_classifier2.py", line 86, in get_batch_test_dali
    serialized_pipes = [pipe.serialize() for pipe in pipes]
  File "train_image_classifier2.py", line 86, in <listcomp>
    serialized_pipes = [pipe.serialize() for pipe in pipes]
  File "/usr/local/lib/python3.5/dist-packages/nvidia/dali/pipeline.py", line 182, in serialize
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/nvidia/dali/pipeline.py", line 124, in build
    self._prepare_graph()
  File "/usr/local/lib/python3.5/dist-packages/nvidia/dali/pipeline.py", line 63, in _prepare_graph
    outputs = self.define_graph()
  File "train_image_classifier2.py", line 65, in define_graph
    return self.base_define_graph(images, labels)
  File "train_image_classifier2.py", line 52, in base_define_graph
    images = self.resize(images, resize_shorter = self.resize_rng())
  File "/usr/local/lib/python3.5/dist-packages/nvidia/dali/ops.py", line 192, in __call__
    op_instance = _OperatorInstance(inputs, self, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nvidia/dali/ops.py", line 94, in __init__
    self._spec.AddArgumentInput(k, kwargs[k].name)
RuntimeError: [/opt/dali/dali/pipeline/operators/op_spec.cc:56] Assert on "schema.HasArgument(arg_name)" failed: Argument resize_shorter is not part of the op schema

**Comment by JanuszL** [comment]
Hi,
Between DALI 0.1 and 0.2 there was change in operators API. Examples you are running are form master branch (new code) but DALI itself is probably 0.1.x. We just released 0.2, please update DALI and try again. If that doesn't work please reopen.
