### ISSUE TITLE
How to crop images read from OpenCV?

### ISSUE THREAD

**Issue by hitachinsk** [NVIDIA/DALI#1450]
Hello everyone! I want to crop the images read from OpenCV with DALI, here is my pipeline.
```
class TrainPipe(Pipeline):
    def __init__(self, data_iterator, batch_size, num_threads, device_id, local_rank=0, world_size=1,
                 dali_cpu=False):
        super(TrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12)
        self.iterator = data_iterator

        dali_device = 'gpu'
        self.input1 = ops.ExternalSource()
        # Crop operations
        self.LQ_crop = ops.Crop(device=dali_device, crop_h=32, crop_w=32, crop_pos_x=0.2, crop_pos_y=0.2)

    def iter_setup(self):
        img1 = self.iterator.next()
        self.feed_input(self.img1, img1)

    def define_graph(self):
        self.img1 = self.input1()
        output = self.img1.gpu()
        self.img1 = self.LQ_crop(output)
        return [self.img1]
```
As you can see, I feed the pipeline with an `ExternalSource` function, which contains the `ndarray` read from a single image with `OpenCV`, here is my external iterator to feed images.
```
class ExternalInputIterator(object):
    def __init__(self, batch_size, opt):
        self.batch_size = batch_size
        self.opt = opt
        self.GT_root = opt['dataroot_GT'] # root directory 

        self.paths = [
            '10091373_01',
            '10091373_02',
            '10091373_03',
            '10272022_01',
            '10272022_02',
            '10272022_03'
        ]
        shuffle(self.paths)

    def __iter__(self):
        self.i = 0
        self.n = len(self.paths)
        return self

    def __next__(self):
        imgs = []
        for _ in range(self.batch_size):
            name_a, name_b = self.paths[self.i].split('_')
            print(name_a, name_b)
            img = self.read_img(os.path.join(self.GT_root, name_a, name_b, '00001.jpg'))
            imgs.append(img)
            self.i = (self.i + 1) % self.n
        return (imgs)

    def read_img(self, path):
        img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
        img = img.astype(np.float) / 255.
        if img.ndim == 2:
            img = np.expand_dims(img, axis=2)
        if img.shape[2] > 3:
            img = img[:, :, 3]
        img = np.ascontiguousarray(img[:, :, [2, 1, 0]]) # turn BGR to RGB and must keep continuity of this array
        return img[np.newaxis, :, :, :]

    next = __next__
```
Finally, I use a `DALIGenericIterator` to transform and iterate all the images produced by this Pipeline.
```
eii = ExternalInputIterator(1, opt)
iterator = iter(eii)
pip_train = TrainPipe(iterator, batch_size=1, num_threads=2, device_id=0, opt=opt)
pip_train.build()
train_loader = DALIGenericIterator([pip_train], ['img1'], 6)
for i, data in enumerate(train_loader):
    ......
```
But when I test this program, something strange happens, here is the error log.
```
Traceback (most recent call last):
  File "cv2dalitest.py", line 102, in <module>
    train_loader = DALIGenericIterator([pip_train], ['img1'], 6)
  File "/home/zkd/anaconda2/envs/py35/lib/python3.5/site-packages/nvidia/dali/plugin/pytorch.py", line 135, in __init__
    self._first_batch = self.next()
  File "/home/zkd/anaconda2/envs/py35/lib/python3.5/site-packages/nvidia/dali/plugin/pytorch.py", line 235, in next
    return self.__next__()
  File "/home/zkd/anaconda2/envs/py35/lib/python3.5/site-packages/nvidia/dali/plugin/pytorch.py", line 150, in __next__
    outputs.append(p.share_outputs())
  File "/home/zkd/anaconda2/envs/py35/lib/python3.5/site-packages/nvidia/dali/pipeline.py", line 402, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline: Error in thread 0: [/opt/dali/dali/pipeline/operators/util/external_source.cc:30] Assert on "OperatorBase::batch_size_ == static_cast<int>(t_data_.size())" failed: Data list provided to ExternalSource needs to have batch_size length.
```
When I comment the line of `ops.Crop`, the error disappears. It seems I haven't provided the batch_size length to ExternalSource, but how can I provide it? I'm looking forward to your reply, and I'd appreciate to all of your help!

**Comment by JanuszL** [comment]
Hi,
I think you confuse DALI with:
```
    def define_graph(self):
        self.img1 = self.input1()
        output = self.img1.gpu()
        self.img1 = self.LQ_crop(output)
        return [self.img1]
```
You should write something like:
```
    def define_graph(self):
        self.img1 = self.input1()
        output = self.img1.gpu()
        output = self.LQ_crop(output)
        return [output]
```
If you use `self.img1` as the output of the ExternalSource and the output of some other operator it cause troubles.
Some minimal example that works for me (including layout support):
```
import os
import types
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
from nvidia.dali.plugin.pytorch import DALIGenericIterator
import cv2

class TrainPipe(Pipeline):
    def __init__(self, data_iterator, batch_size, num_threads, device_id, local_rank=0, world_size=1,
                 dali_cpu=False):
        super(TrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12)
        self.iterator = data_iterator

        dali_device = 'gpu'
        self.input1 = ops.ExternalSource()
        # Crop operations
        self.LQ_crop = ops.Crop(device=dali_device, crop_h=32, crop_w=32, crop_pos_x=0.2, crop_pos_y=0.2)

    def iter_setup(self):
        img1 = self.iterator.next()
        self.feed_input(self.img1, img1, layout="HWC")

    def define_graph(self):
        self.img1 = self.input1()
        output = self.img1.gpu()
        output = self.LQ_crop(output)
        return [output]

class ExternalInputIterator(object):
    def __init__(self, batch_size, opt):
        self.batch_size = batch_size
        self.opt = opt
        self.GT_root = opt['dataroot_GT'] # root directory 

        self.paths = [
            '100#swan-3584559_640.jpg',
            '134#baukran-3703469_1280.jpg',
            '113#snail-4345504_1280.jpg',
            '182#dog-2425598_1280.jpg',
            '241#dog-4366295_1920.jpg',
            '312#grasshopper-4357907_1280.jpg'
        ]
        shuffle(self.paths)

    def __iter__(self):
        self.i = 0
        self.n = len(self.paths)
        return self

    def __next__(self):
        imgs = []
        for _ in range(self.batch_size):
            name_a, name_b = self.paths[self.i].split('#')
            print(name_a, name_b)
            path = os.path.join(self.GT_root, name_a, name_b)
            img = self.read_img(path)
            imgs.append(img)
            self.i = (self.i + 1) % self.n
        return (imgs)

    def read_img(self, path):
        img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
        img = img.astype(np.float32) / 255.
        if img.ndim == 2:
            img = np.expand_dim(simg, axis=2)
        if img.shape[2] > 3:
            img = img[:, :, :3]
        img = np.ascontiguousarray(img[:, :, [2, 1, 0]]) # turn BGR to RGB and must keep continuity of this array
        return img

    next = __next__

opt = {'dataroot_GT' : /DALI_extra/db/single/jpeg/'}
eii = ExternalInputIterator(1, opt)
iterator = iter(eii)
pip_train = TrainPipe(iterator, batch_size=1, num_threads=2, device_id=0)
pip_train.build()
train_loader = DALIGenericIterator([pip_train], ['img1'], 6)
for i, data in enumerate(train_loader):
    pass
```
