### ISSUE TITLE
`ops.VideoReader`: Multiple/Different Video Resolution Not Supported Error

### ISSUE THREAD

**Issue by BlackPepperAPI** [NVIDIA/DALI#1637]
Hi. I would like to have your suggestion/advice on using `ops.VideoReader`, reading labelled videos by passing the structured video directory to `file_root` argument as decribed in [DALI docs](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#videoreader)

Here are my package versioning:
- Python: 3.6
- NVIDIA Dali version: 
```
Name: nvidia-dali
Version: 0.17.0
Summary: NVIDIA DALI for CUDA 9.0. Git SHA: e61c304d9f5560fff1be5c821ee140cdab104aef
```

## Issue/Error
I ran into a problem when I'm building my pipeline for video action recognition dataset so called `HMDB51` which has different resolution/ frame shape (all RGB but different HxW). I'm trying to load labelled videos which has structure as follows:
```
├── HMDB51
│   ├── raw
│   │   ├── brush_hair  # class 0
│   │    |         | ─ brush_hair_vid_0.avi  # video file
│   │    |         | ─ brush_hair_vid_1.avi
│   │    |         | ─ brush_hair_vid_2.avi
│   │    |         | ─ brush_hair_vid_3.avi
│   │   ├── cartwheel   # class 1
│   │   ├── catch  # class 2
│   │   ├── chew  # and so on...
```

However, I got an error saying that NVIDIA Decoder for video doesn't support reconfigure feature for different video resolution. 
```
[/opt/dali/dali/operators/reader/loader/video_loader.cc:247] 
File data/HMDB51/raw//brush_hair/Aussie_Brunette_Brushing_Hair_II_brush_hair_u_nm_np1_ba_goo_4.avi 

does not have the same resolution as previous files. (416x240 instead of 320x240). 

Install Nvidia driver version >=396 (x86) or >=415 (Power PC) to decode multiple resolutions

[/opt/dali/dali/operators/reader/video_reader_op.h:58] Decoder reconfigure feature not supported
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    main()
  File "main.py", line 30, in main
    pipeline.build()
  File "/home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 308, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: Decoder reconfigure feature not supported
```

My environment uses CUDA `9.0`. I'm aware that currently, my GPU server has Nvidia version `396.54` where as the driver that support multiple resolutions for video is `>= 415` (from the error):
> Nvidia driver version >=396 (x86) or >=415 (Power PC) to decode multiple resolutions

![nvidia-smi-mlda](https://user-images.githubusercontent.com/59719804/72134008-cf6bb780-33bd-11ea-8e0b-dd1db00e6824.png)

Here, I'm using architecture `x86_64` for Ubuntu 18.04
```
$uname -m
x86_64
```

## Question:
I'm aware of [issue #1350](https://github.com/NVIDIA/DALI/issues/1599) but it doesn't answer my question, so I would like to raise a question here :

1. The solution might be obsvious from the error: Installling/Upgrade to NVIDIA driver `>=415`. However currently I'm not the admin of the server. Is it possible to have some workaround before I request to my admin? 
2. I'm aware that there are `SequenceReader` as well which I get from your tutorial [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/sequence_reader_simple_example.html). The input are images from those frames. Would you recommend this method instead of `VideoReader` as my workaround? Does `SequenceReader` support multiple /different shape/size in different sequence?

3.

**Comment by BlackPepperAPI** [comment]
This is my little experiment code:
```
import nvidia.dali.ops as ops
import nvidia.dali.types as types
from nvidia.dali.pipeline import Pipeline
from nvidia.dali.plugin.pytorch import DALIGenericIterator


class VideoReaderPipeline(Pipeline):
	def __init__(self, file_root, batch_size, sequence_length, crop_size, 
				num_threads, device_id, output_layout=types.NCHW,
				random_shuffle=True, step=-1, seed=42):
		super().__init__(batch_size, num_threads, device_id, seed=seed)

		# Define video reader
		self.reader = ops.VideoReader(device = "gpu", file_root, sequence_length,
		    random_shuffle, image_type = types.RGB, initial_fill = 16)

		self.rescrop = ops.CropMirrorNormalize(device = "gpu", crop_size, 
                                             output_layout = types.NFCHW)

	def define_graph(self):
		input_vid  = self.reader(name = "Reader")
		output_vid = self.rescrop(input_vid)
		return output_vid
...

file_root = "data/HMDB51/raw/"

# Define video reader pipeline
pipeline = VideoReaderPipeline(file_root, 
                                    batch_size = 2,
                                    sequence_length = 16,
                                    crop_size = (224,224),
                                    num_threads = 2,
                                    device_id = 0,
                                    random_shuffle = True,
                                    step = 2)
# Build pipeline
pipeline.build()

for k in range(10):
    pipeout = pipeline.run()
    sequence_out = pipeout[0].as_cpu().as_array()  # [batch_size, sequence_length, channel, height, width]
    print(sequence_out.shape)
```

**Comment by JanuszL** [comment]
Hi,
> ## Question:
> 
> I'm aware of [issue #1350](https://github.com/NVIDIA/DALI/issues/1599) but it doesn't answer my question, so I would like to raise a question here :
> 
>     1. The solution might be obsvious from the error: Installling/Upgrade to NVIDIA driver `>=415`. However currently I'm not the admin of the server. Is it possible to have some workaround before I request to my admin?
> 
>     2. I'm aware that there are `SequenceReader` as well which I get from your tutorial [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/sequence_reader_simple_example.html). The input are images from those frames. Would you recommend this method instead of `VideoReader` as my workaround? Does `SequenceReader` support multiple /different shape/size in different sequence?

If you have driver >= 396 and your machine is x86_64 the only thing that comes to my mind is the issues fixed https://github.com/NVIDIA/DALI/pull/1591 and https://github.com/NVIDIA/DALI/pull/1592.
Can you try the latest nightly build and see how it works?
`SequenceReader` its implementation is rather rudimentary - it has very limited ability to assign labels to sequences comparing to the video reader now. Also, it is CPU only so you won't get any JPEG CUDA decoding acceleration. I would recommend trying to resolve the problem with the `VideoReader` first.

@a-sansanwal - FYI

**Comment by BlackPepperAPI** [comment]
Hi @JanuszL 

I installed the nightly build from `https://developer.download.nvidia.com/compute/redist/nightly/cuda/9.0 nvidia-dali-nightly`. Here is the version:
```
Name: nvidia-dali
Version: 0.17.0
Summary: NVIDIA DALI for CUDA 9.0. Git SHA: e61c304d9f5560fff1be5c821ee140cdab104aef
Home-page: https://github.com/NVIDIA/dali
Author: NVIDIA Corporation
Author-email: UNKNOWN
License: Apache License 2.0
Location: /home/students/student3_17/.local/lib/python3.6/site-packages
```

After re-running the script, I see another issue which I think came from different causes other than the first problem above.

#### Observation 1:
I have videos from HMDB51 dataset with `.avi` format which I put in `data/HMDB51/raw/`. Running the above `ops.VideoReader` with `file_root = "data/HMDB51/raw"` hangs indefinitely as similar to [issue #1041](https://github.com/NVIDIA/DALI/issues/1041). Probably the same root cause as issue #1041 and I'll proceed to discuss there

#### Observation 2:
I do process the video HMDB51 with `ffmpeg` so that it has constant frame rate and convert to video format with extension `.mp4`. I save it in `data/HMDB51/processed/` Running the above `ops.VideoReader with `file_root="data/HMDB51/processed"` gives the following error:

```
Traceback (most recent call last):                                                                                                                                                                          
  File "main.py", line 64, in <module>                                                                                                                                                                      
    main()                                                                                                                                                                                                  
  File "main.py", line 54, in main                                                                                                                                                                          
    dali_iterator = VideoLoader(file_root, batch_size=10, sequence_length=7, crop_size=(224,224))                                                                                                           
  File "/home/students/student3_17/ComputerVision/pytorch-actionnet/torchaction/dataloader.py", line 118, in __init__                                                                                       
    auto_reset = True)                                                                                                                                                                                      
  File "/home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 148, in __init__                                                                                 
    self._first_batch = self.next()                                                                                                                                                                         
  File "/home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 245, in next                                                                                     
    return self.__next__()                                                                                                                                                                                  
  File "/home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 163, in __next__                                                                                 
    outputs.append(p.share_outputs())                                                                                                                                                                       
  File "/home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 409, in share_outputs                                                                                  
    return self._pipe.ShareOutputs()                                                                                                                                                                        
RuntimeError: Critical error in pipeline: [/opt/dali/dali/operators/fused/crop_mirror_normalize.h:147] Assert on "ImageLayoutInfo::IsImage(input_layout_)" failed: Unsupported layout: '' for input 0 'Video
Reader_id_0_output_1'                                                                                                                                                                                       
Stacktrace (11 entries):                                                                                                                                                                                    
[frame 0]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x2bea1e) [0x7efc92ac8a1e]                                                                       
[frame 1]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0xfadeef) [0x7efc937b7eef]                                                                       
[frame 2]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0xf739b0) [0x7efc9377d9b0]                                                                       
[frame 3]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x8a87fd) [0x7efc930b27fd]                                                                       
[frame 4]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0xc2bbd) [0x7efc9157dbbd]                                                                                  
[frame 5]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0xc3511) [0x7efc9157e511]                                                                                  
[frame 6]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x950c3) [0x7efc915500c3]                                                                                  
[frame 7]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x112156) [0x7efc915cd156]                                                                                 
[frame 8]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x724510) [0x7efc91bdf510]                                                                                 
[frame 9]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7efcf98c26db]                                                                                                                                  
[frame 10]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7efcf9bfb88f]  
```

**Comment by BlackPepperAPI** [comment]
If possible, I would like to concentrate this threads on problem from my **Observation 2**
