### ISSUE TITLE
Cannot build DALI from the source

### ISSUE THREAD

**Issue by milkpot** [NVIDIA/DALI#1692]
I did:
```
git clone --recursive https://github.com/NVIDIA/DALI.git
cd DALI
cd docker
PYVER=3.6 CUDA_VERSION=10 BUILD_TF_PLUGIN=YES ./build.sh
```

and, after some minutes, got an error:
```
+ /opt/_internal/cpython-3.4.8/bin/python get-pip.py --force-reinstall
Traceback (most recent call last):
  File "get-pip.py", line 22711, in <module>
    main()
  File "get-pip.py", line 198, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 83, in bootstrap
    from pip._internal.commands.install import InstallCommand
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmp159nl_4g/pip.zip/pip/_internal/commands/install.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmp159nl_4g/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 92, in <module>
RuntimeError: Python 3.5 or later is required
The command '/bin/sh -c bash build_scripts/build.sh && rm -r build_scripts' returned a non-zero code: 1
```

It seems to fail to build manylinux

**Comment by JanuszL** [comment]
Hi,
It is not expected. Can you try to remove Python 3.4 in https://github.com/NVIDIA/DALI/blob/master/docker/0001-An-approximate-manylinux3_x86_64.patch#L184 and rerun?

**Comment by JanuszL** [comment]
It looks that pip has been just updated and it no longer supports Python 3.4 https://github.com/pypa/pip/blob/20.0.2/src/pip/_vendor/pkg_resources/__init__.py#L91.
https://github.com/NVIDIA/DALI/pull/1694 should fix this.

**Comment by milkpot** [comment]
Removing 3.4.8 from that line, the build succeeded. Thank you for your help!
