### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#2068]
Looking in indexes: https://pypi.org/simple, https://developer.download.nvidia.com/compute/redist/cuda/10.0
Collecting nvidia-dali
  Using cached nvidia-dali-0.0.1.dev3.tar.gz (3.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/tiger/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ju740_l5/nvidia-dali/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ju740_l5/nvidia-dali/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yrib12li
         cwd: /tmp/pip-install-ju740_l5/nvidia-dali/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ju740_l5/nvidia-dali/setup.py", line 130, in <module>
        raise RuntimeError("This package should not be installed.\nPlease refer "
    RuntimeError: This package should not be installed.
    Please refer to NVIDIA instructions: https://github.com/nvidia/tensorflow.
    Your PIP command defaults to the official PyPI as a package repository.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by pawopawo** [comment]
hope for help
