### ISSUE TITLE
Why the Dali pipeline 2 not valid, when Dali pipeline 1 in the same computer is closed.

### ISSUE THREAD

**Issue by RichardMLe** [NVIDIA/DALI#2084]
I got a small problem when I **run two evaluation processes using the same .py file in one computer.**  
The evaluation process 1 is running in gpu 0.
The evaluation process 2 is running in gpu 1.

By modifying the parameters, I run two evaluation processes using the same .py file.  In each process , I will test multiple test sets, which means that the Dali pipeline will be created several times. When I start running two evaluation process, everything is ok. But once one evaluation process is done, the other evaluation process will also stop.

System: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-46-generic x86_64)
Driver Version: 418.39       
CUDA Version: 10.1
DALI Version: 0.21.0
pytorch Vession: 1.1
python : 3.6.2

The Dali pipeline is designed with reference to the  [ExternalSource operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-external_input.html).
The Dalie pipeline file is as follows:

```
import types
import collections
import os
import os.path
import sys
import numpy as np
from random import shuffle
from PIL import Image
from torchvision import transforms
try:
    from nvidia.dali.plugin.pytorch import DALIClassificationIterator as PyTorchIterator
    from nvidia.dali.pipeline import Pipeline
    import nvidia.dali.ops as ops
    import nvidia.dali.types as types
except ImportError:
    raise ImportError("Please install DALI from https://www.github.com/NVIDIA/DALI to run this example.")

#IMG_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif', '.tiff', '.webp')
IMG_EXTENSIONS = ('.png')
def pil_loader(path):
    # open path as file to avoid ResourceWarning (https://github.com/python-pillow/Pillow/issues/835)
    with open(path, 'rb') as f:
        img = Image.open(f)
        img = img.convert('RGB')
        loader = transforms.Compose([
            transforms.ToTensor()])
        return loader(img).unsqueeze(0)

def default_loader(path):
    from torchvision import get_image_backend
    if get_image_backend() == 'accimage':
        return accimage_loader(path)
    else:
        return pil_loader(path)

def has_file_allowed_extension(filename, extensions):
    """Checks if a file is an allowed extension.

    Args:
        filename (string): path to a file
        extensions (tuple of strings): extensions to consider (lowercase)

    Returns:
        bool: True if the filename ends with one of given extensions
    """
    return filename.lower().endswith(extensions)


def is_image_file(filename):
    """Checks if a file is an allowed image extension.

    Args:
        filename (string): path to a file

    Returns:
        bool: True if the filename ends with a known image extension
    """
    return has_file_allowed_extension(filename, IMG_EXTENSIONS)


def make_dataset(dirx, extensions=IMG_EXTENSIONS, is_valid_file=None):
    images = []
    dirx = os.path.expanduser(dirx)
    if not ((extensions is None) ^ (is_valid_file is None)):
        raise ValueError("Both extensions and is_valid_file cannot be None or not None at the same time")
    if extensions is not None:
        def is_valid_file(x):
            return has_file_allowed_extension(x, extensions)
        d = dirx
        if not os.path.isdir(d):
            return 0
        for root, _, fnames in sorted(os.walk(d)):
            for fname in sorted(fnames):
                path = os.path.join(root, fname)
                if is_valid_file(path):
                    size = os.path.getsize(path)
                    if size > 50*1024:
                        images.append(path+' '+'1')
        if len(images)==0:
            images.append(path+' '+'1')
        print(len(images))
    return images


def dataList(dirx, extensions=IMG_EXTENSIONS, is_valid_file=None):
    images = []
    dirx = os.path.expanduser(dirx)
    if not ((extensions is None) ^ (is_valid_file is None)):
        raise ValueError("Both extensions and is_valid_file cannot be None or not None at the same time")
    if extensions is not None:
        def is_valid_file(x):
            return has_file_allowed_extension(x, extensions)
        d = dirx
        if not os.path.isdir(d):
            return 0
        for root, _, fnames in sorted(os.walk(d)):
            for fname in sorted(fnames):
                path = os.path.join(root, fname)
                if is_valid_file(path):
                    size = os.path.getsize(path)
                    if size > 50*1024:
                        images.append(path)
        if len(images)==0:
            images.append(path)
        print(len(images))
    return images




class ExternalInputIterator(object):
    def __init__(self, images_dir, batch_size=128, device_id=0, num_gpus=1,is_shuffle=False):
        self.images_dir = images_dir
        self.batch_size = batch_size
        self.files = make_dataset(self.images_dir)
        self.data_set_len = len(self.files)
        # based on the device_id and total number of GPUs - world size
        # get proper shard
        self.files = self.files[self.data_set_len * device_id // num_gpus:
                                self.data_set_len * (device_id + 1) // num_gpus]
        self.n = len(self.files)
        if is_shuffle:
            shuffle(self.files)

    def __iter__(self):
        self.i = 0
        return self

    def __next__(self):
        batch = []
        labels = []
        
        if self.i >= self.n:
            raise StopIteration

        for _ in range(self.batch_size):
            jpeg_filename, label = self.files[self.i].split(' ')
            f = open(jpeg_filename, 'rb')
            batch.append(np.frombuffer(f.read(), dtype = np.uint8))
            labels.append(np.array([label], dtype = np.uint8))
            self.i = (self.i + 1) % self.n
        return (batch, labels)
    
    @property
    def size(self,):
        return self.data_set_len

    next = __next__
    
    
class ExternalSourcePipeline(Pipeline):                   
    def __init__(self, batch_size, num_threads, device_id, size,
                 mean, std, local_rank=0, world_size=1, dali_cpu=False, shuffle=False,
                 crop=224,fp16=False,external_data=None):
        super(ExternalSourcePipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id)
        if dali_cpu:
            decode_device = "cpu"
            self.dali_device = "cpu"
            self.crop = ops.Crop(device="cpu", crop=(crop, crop))

        else:
            decode_device = "mixed"
            self.dali_device = "gpu"

            output_dtype = types.FLOAT
            if fp16:
                output_dtype = types.FLOAT16
        self.input = ops.ExternalSource()
        self.input_label = ops.ExternalSource()
        self.decode = ops.ImageDecoder(device = decode_device, 
                                       output_type = types.RGB)
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                                output_dtype=output_dtype,
                                                output_layout=types.NCHW,
                                                image_type=types.RGB,
                                                mean=mean,
                                                std=std)
        self.res = ops.Resize(device=self.dali_device, resize_shorter=size, interp_type=types.INTERP_TRIANGULAR)
        self.external_data = external_data
        self.iterator = iter(self.external_data)

    def define_graph(self):                                                                
        self.jpegs = self.input()
        self.labels = self.input_label()
        images = self.decode(self.jpegs)                                                   
        output = self.res(images)
        if self.dali_device == 'gpu':
            output = self.cmnp(output )
        else:
            # CPU backend uses torch to apply mean & std
            output = self.crop(output )
        self.labels = self.labels.gpu()
        return (output, self.labels)

    
    def iter_setup(self):
        try:
            (images, labels) = self.iterator.next()
            self.feed_input(self.jpegs, images)
            self.feed_input(self.labels, labels)
        except StopIteration:
            self.iterator = iter(self.external_data)
            raise StopIteration       
        


def build_dali_pipeline(data_dir, batch_size, device_id, data_size=224, fp16=False,
                 workers=4, local_rank=0, world_size=1, dali_cpu=False, shuffle=False,
                 mean=(0.485 * 255, 0.456 * 255, 0.406 * 255),
                 std=(0.229 * 255, 0.224 * 255, 0.225 * 255),):
    
    eii = ExternalInputIterator(images_dir=data_dir, batch_size=batch_size, 
                                device_id=device_id, num_gpus=world_size,is_shuffle=shuffle)

    pipe = ExternalSourcePipeline(batch_size=batch_size, num_threads=workers, device_id = device_id, 
                              mean=mean, std=std, size=data_size, external_data = eii)
    pii = PyTorchIterator(pipe, size=eii.size, last_batch_padded=True, fill_last_batch=False)   
    
    return pii
```

The core valid process is shown here. In the evaluation process, the single_WSI_prediction will be called multiple times.

```
def validate(val_loader, model):
    model.eval()
    end = time.time()
    pathSummary = []
    for i, data in enumerate(val_loader):
        input = data[0]['data']
        target = data[0]['label']
        #path = data[2]
        path = ''
        if args.gpu is not None:
            input = input.cuda(args.gpu, non_blocking=True)

        # compute output
        with torch.no_grad():
            output = model(input)
            output = output[:,0:5]
        if i==0:
            outputSummary=np.asarray(output.cpu())
        else:
            outputSummary = np.concatenate((outputSummary,np.asarray(output.cpu())),axis=0)
        pathSummary.extend(path)
    timeCost = time.time() - end
    return outputSummary, pathSummary,timeCost

def single_WSI_prediction(model,data_path):
    dataset=build_dali_pipeline(data_dir=data_path,
                                batch_size=args.batch_size,
                                workers=args.workers,
                                world_size=args.world_size,
                                device_id=args.gpu)
    outputSummary, pathSummary,timeCost = validate(dataset, model)
    return outputSummary, pathSummary,timeCost
```

But when one evaluation process is done, the other process will show this:

```
<nvidia.dali.pipeline.DataNode object at 0x7f4e5bdc5710>
Traceback (most recent call last):
  File "./predictionWSI.py", line 345, in <module>
    all_WSI_prediction_with_list(model,WSIList=WSIList, log_dir =log_dir, predictedScoreDir=predictedScoreDir)
  File "./predictionWSI.py", line 306, in all_WSI_prediction_with_list
    outputSummary, useLessPathSummary,timeCost = single_WSI_prediction(model,data_path=sub_class_WSI_path)
  File "./predictionWSI.py", line 194, in single_WSI_prediction
    outputSummary, pathSummary,timeCost = validate(dataset, model)
  File "./predictionWSI.py", line 161, in validate
    for i, data in enumerate(val_loader):
  File "/home/richard/.conda/envs/torch/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 177, in __next__
    outputs.append(p.share_outputs())
  File "/home/richard/.conda/envs/torch/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 529, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline: CUDA allocation failed
Current pipeline object is no longer valid.
```

**Comment by JanuszL** [comment]
Hi,
I will check that.

**Comment by JanuszL** [comment]
I don't see anything wrong with your code. Could you squash it to a minimal, self-contained reproduction scenario I could run on my own (you can use https://github.com/NVIDIA/DALI_extra as a source of test data)?
Have you tried to run only this evaluation process that stops on its own? From my point of view, it looks rather as a coincidence that one process ends and the second crashes at the same time. DALI doesn't use any inter-process communication so I don't know how it could cause other processes to crash. The error you see is rather the effect of running out of the GPU memory.

**Comment by RichardMLe** [comment]
> 
> 
> I don't see anything wrong with your code. Could you squash it to a minimal, self-contained reproduction scenario I could run on my own (you can use https://github.com/NVIDIA/DALI_extra as a source of test data)?
> Have you tried to run only this evaluation process that stops on its own? From my point of view, it looks rather as a coincidence that one process ends and the second crashes at the same time. DALI doesn't use any inter-process communication so I don't know how it could cause other processes to crash. The error you see is rather the effect of running out of the GPU memory.

I can not reproduce it as well. Yesterday, the process has run another three times with no bugs. It may just be a coincidence.
And I am sorry that I cannot provide the code. Thank you.

**Comment by JanuszL** [comment]
Please let us know when this problem appears again and you can provide a code reproducing it.
