### ISSUE TITLE
Error while using erase operator to remove random regions of an image

### ISSUE THREAD

**Issue by akshay-raj-dhamija** [NVIDIA/DALI#2171]
Hi, I am trying to use the `Erase` operator to remove random parts of an image during training. 
According to my understanding, the erase operator may be called with the anchor argument to create erased patches at varied positions in the image.
If I call the operator in the graph defination using 
`images = self.erase(images, anchor=(self.anchor_loc(),self.anchor_loc()))` 
where 
`self.anchor_loc = nvidia_ops.Uniform(range=(0.,0.5))` 
I get the error message.
`TypeError: Expected inputs of type `DataNode`. Received input of type 'tuple'.`

If I only provide a single anchor location as 
`images = self.erase(images, anchor=self.anchor_loc())` 
I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    main()
  File "main.py", line 96, in main
    training.trainer(0, args)
  File "/net/home/store/home/adhamija/ImageNet_Dali/training.py", line 168, in trainer
    batch_size=args.batch_size, random_seed=0)
  File "/net/home/store/home/adhamija/ImageNet_Dali/training.py", line 53, in create_data_loader
    loader = PyTorchIterator(data_pipeline, size=-1, auto_reset=True)
  File "/home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 356, in __init__
    last_batch_padded = last_batch_padded)
  File "/home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 161, in __init__
    self._first_batch = self.next()
  File "/home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 273, in next
    return self.__next__()
  File "/home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 175, in __next__
    outputs.append(p.share_outputs())
  File "/home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 558, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline: [/opt/dali/dali/operators/generic/erase/erase_utils.h:111] Assert on "roi_anchor.size() == roi_shape.size()" failed
Stacktrace (11 entries):
[frame 0]: /home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/libdali_operators.so(+0x39095e) [0x7f4c564de95e]
[frame 1]: /home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/libdali_operators.so(+0x4a37a3) [0x7f4c565f17a3]
[frame 2]: /home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/libdali_operators.so(+0x4a3e91) [0x7f4c565f1e91]
[frame 3]: /home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/libdali_operators.so(+0x46f1cc) [0x7f4c565bd1cc]
[frame 4]: /home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/libdali.so(+0x113433) [0x7f4c451db433]
[frame 5]: /home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/libdali.so(+0x113fb6) [0x7f4c451dbfb6]
[frame 6]: /home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/libdali.so(+0xe8d52) [0x7f4c451b0d52]
[frame 7]: /home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/libdali.so(+0x15bdf6) [0x7f4c45223df6]
[frame 8]: /home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/nvidia/dali/libdali.so(+0x908350) [0x7f4c459d0350]
[frame 9]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f4cc9ac76db]
[frame 10]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f4cc97f0a3f]

Current pipeline object is no longer valid.
Traceback (most recent call last):
  File "/home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/adhamija/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
```

What is the best way to address this, I am using version `0.23.0`
Following is a minimalistic pipeline for reproduction.
```
class ExternalSourcePipeline(Pipeline):
    def __init__(self,external_data,batch_size,**kwargs):
        super(ExternalSourcePipeline, self).__init__(batch_size=batch_size,num_threads=1,device_id=0)#200, num_threads, device_id, seed=34,prefetch_queue_depth={ "cpu_size": 10, "gpu_size": 2})
        self.input = nvidia_ops.ExternalSource()
        self.input_label = nvidia_ops.ExternalSource()
        self.crop_loc = nvidia_ops.Uniform(range=(0.,1.))
        self.anchor_loc = nvidia_ops.Uniform(range=(0.,0.5))
        self.train_decode = nvidia_ops.ImageDecoderRandomCrop(device="cpu",output_type=nvidia_types.RGB,random_aspect_ratio=(0.5,4.))
        self.erase = nvidia_ops.Erase(device="cpu",axis_names="HW",shape=[64,64],centered_anchor=True,normalized_anchor=True,normalized_shape=False,fill_value=128)
        self.resize = nvidia_ops.Resize(device="cpu", resize_shorter=256)
        self.crop_mirror_normalize = nvidia_ops.CropMirrorNormalize(device="cpu", crop=(224,224),mean=128,std=128,output_layout='HWC')
        self.external_data = external_data
        self.iterator = iter(self.external_data)

    def define_graph(self):
        self.jpegs = self.input()
        self.labels = self.input_label()
        images = self.train_decode(self.jpegs)
        images = self.resize(images)
        images = self.crop_mirror_normalize(images, crop_pos_x=self.crop_loc(), crop_pos_y=self.crop_loc())
        images = self.erase(images, anchor=self.anchor_loc())
        images = images.gpu()
        return (images, self.labels)

    def iter_setup(self):
        try:
            (images, labels) = self.iterator.next()
            self.feed_input(self.jpegs, images)
            self.feed_input(self.labels, labels)
        except StopIteration:
            self.iterator = iter(self.external_data)
            raise StopIteration
```

**Comment by JanuszL** [comment]
Hi,
[This example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/erase.html) should answer all your questions. It shows how to hardcore the erase region as well as to provide any number of randomly selected regions.

**Comment by akshay-raj-dhamija** [comment]
Thanks! this was really helpful and it solved my issue.
