### ISSUE TITLE
[Question] Video reader: compatible chroma sampling 

### ISSUE THREAD

**Issue by JuanFMontesinos** [NVIDIA/DALI#2197]
Hi
Got this error
```
[/opt/dali/dali/operators/reader/nvdecoder/cuvideodecoder.cc:206] Unsupported Codec AVC/H.264 with chroma format YUV 444
/opt/dali/dali/operators/reader/nvdecoder/nvdecoder.cc:158: Unable to decode file /media/jfm/Slave/SkDataset/videos_crop/cello/CJMOPvsinJE.mp4
Traceback (most recent call last):
  File "/home/jfm/GitHub/VnBSS/run.py", line 149, in <module>
    size=pipe.epoch_size('video')))
  File "/home/jfm/.local/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 160, in __init__
    self._first_batch = self.next()
  File "/home/jfm/.local/lib/python3.6/site-packages/nvidia/dali/plugin/base_iterator.py", line 273, in next
    return self.__next__()
  File "/home/jfm/.local/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 174, in __next__
    outputs.append(p.share_outputs())
  File "/home/jfm/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 663, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: ('Critical error in pipeline:\nError when executing GPU operator VideoReaderResize encountered:\nDecoder hardware does not support this video codec and/or chroma format\nCurrent pipeline object is no longer valid.', 'Error detected! Epoch 0. Mode True')
```
Sooo since the video coded is h264 I assume that the chroma sample (4:4:4) is not compatible. 

Can you  give me extra infor about compatible formats?
Anyway 4:4:4 is high quality thus I don't really get why it's not comp

Edit: btw checking other issues
https://developer.nvidia.com/nvidia-video-codec-sdk
found this and seems 4:4:4 should be compatible

I leave ffprobe data
```
ffprobe version 3.4.8-0ubuntu0.2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/media/jfm/Slave/SkDataset/videos_crop/cello/CJMOPvsinJE.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:04:56.92, start: 0.000000, bitrate: 414 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 241x1080, 411 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
```

```
Dali version: 0.25.0dev.20200717
gpu: gtx 1080 ti
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+


```
Thanks you in advance

**Comment by JanuszL** [comment]
Hi,
For some reason, VideoSDK says that video you have is not supported. Can you share this particular video sample so we can take a close look?

**Comment by JuanFMontesinos** [comment]
I have a big bunch of samples which are not compatible XD 
https://drive.google.com/file/d/1hv0WipFPBVMFQbvjkJOUkw_VnpRkiqQU/view?usp=sharing

They were made via
` writer = skvideo.io.FFmpegWriter(path.replace(videos_path, dst).replace('.webm', '.mp4').replace('.mkv','.mp4'),                                                   outputdict={'-r': '25'})`

**Comment by JuanFMontesinos** [comment]
And btw I also found (in yuv 420 videos) the following error
`('Critical error in pipeline:\nError when executing GPU operator VideoReaderResize encountered:\n[/opt/dali/dali/operators/reader/nvdecoder/cuvideodecoder.cc:136] Assert on "width >= caps_.nMinWidth && height >= caps_.nMinHeight" failed: Video is too small in at least one dimension.\nStacktrace (17 entries):\n[frame 0]: /home/jfm/.local/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x3b81c6)`

Do you know what these values are?

**Comment by a-sansanwal** [comment]
>Assert on "width >= caps_.nMinWidth && height >= caps_.nMinHeight" failed: Video is too small in at least one dimension
This probably means, that your video is some weird small resolution like 2x2 or something.

**Comment by a-sansanwal** [comment]
Hi @JuanFMontesinos , H.264 with yuv444 is actually not supported by NVDEC.
I guess the support matrix is a little ambiguous.

**Comment by JuanFMontesinos** [comment]
hi @a-sansanwal 
The video is 32x360 (that's why im wondering the specific minimum size) 
It's a shame 4:4:4 is not comp. What about 4:2:2?

**Comment by a-sansanwal** [comment]
> hi @a-sansanwal
> The video is 32x360 (that's why im wondering the minimum size)
> It's a shame 4:4:4 is not comp. What about 4:2:2?

Only 4:2:0

**Comment by a-sansanwal** [comment]
Actually the decoder hardware reports to DALI a minimum resolution and maximum resolution it supports.
Before we even decode anything, we check it.

You could send in a larger padded video that is supported and discard the padding later. As an alternative

**Comment by JuanFMontesinos** [comment]
I see
Thanks for the info @a-sansanwal  and @JanuszL 

And glad to see this library growing.

**Comment by a-sansanwal** [comment]
>The video is 32x360 (that's why im wondering the minimum size)
My rough guess is that >64 is supported.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2203 should provide more verbose information when DALI video decoder fails.
