### ISSUE TITLE
invalid device ordinal even using single GPU training?

### ISSUE THREAD

**Issue by ruiyuanlu** [NVIDIA/DALI#2390]
Hi, I met such issue not only during DDP training even when I use single GPU training. I've double checked the local rank(single GPU is 0), device id(single GPU is 0) and torch.cuda.current_device, which are all correct. So what else should I do? Thanks anyway.

```python
Traceback (most recent call last):
  File "tools/train_net.py", line 24, in <module>
    main()
  File "tools/train_net.py", line 20, in main
    dist.multi_proc_run(num_proc=cfg.NUM_GPUS, fun=trainer.train_model)
  File "/home/user/code/classification/imagenet_cls/imagenet_cls/core/distributed.py", line 200, in multi_proc_run
    fun(*fun_args, **fun_kwargs)
  File "/home/user/code/classification/imagenet_cls/imagenet_cls/core/trainer.py", line 157, in train_model
    train_loader = loader.construct_train_loader()
  File "/home/user/code/classification/imagenet_cls/imagenet_cls/datasets/loader.py", line 106, in construct_train_loader
    return _construct_loader(
  File "/home/user/code/classification/imagenet_cls/imagenet_cls/datasets/loader.py", line 77, in _construct_loader
    loader, msg = _construct_dali_loader(dataset_name, split, batch_size, shuffle, drop_last)
  File "/home/user/code/classification/imagenet_cls/imagenet_cls/datasets/loader.py", line 65, in _construct_dali_loader
    loader = _DALI_DATALOADER[dataset_name](data_path, split)
  File "/home/user/code/classification/imagenet_cls/imagenet_cls/datasets/imagenet_dali.py", line 145, in __init__
    self._iterator = DALIClassificationIterator(pipelines=pipe, reader_name='Reader', auto_reset=False)
  File "/home/user/anaconda3/envs/new_dali/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py", line 350, in __init__
    super(DALIClassificationIterator, self).__init__(pipelines, ["data", "label"],
  File "/home/user/anaconda3/envs/new_dali/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py", line 158, in __init__
    p.schedule_run()
  File "/home/user/anaconda3/envs/new_dali/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 650, in schedule_run
    self._run_once()
  File "/home/user/anaconda3/envs/new_dali/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 761, in _run_once
    self._run_gpu()
  File "/home/user/anaconda3/envs/new_dali/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 614, in _run_gpu
    self._pipe.RunGPU()
RuntimeError: CUDA runtime API error cudaErrorInvalidDevice (10):
``````

**Comment by JanuszL** [comment]
Are you sure you are passing the right GPU ID to the DALI pipeline?
Can you show your DALI code?

**Comment by ruiyuanlu** [comment]
Here is the simplified code of my DALI code. The rank is obtained by `get_rank()` and `get_local_rank()`

The rank-related function:
```python
import torch
import torch.distributed as dist

_LOCAL_PROCESS_GROUP = None
"""
A torch process group that only includes processes that on the same machine as the current process.
This variable is set manually if multi-machine training is necessary.
"""

def get_local_rank() -> int:
    """
    Current local GPU ID of current machine:
    e.g., local_rank = 0-7 for 2 mahcines with 8 GPUs each.

    Note that sometimes there will be no local rank.
    Thus, we choose to return get_rank() as local rank in such cases.
    """
    if not dist.is_available():
        return 0
    if not dist.is_initialized():
        return 0
    if _LOCAL_PROCESS_GROUP is None:
        return dist.get_rank()
    return dist.get_rank(group=_LOCAL_PROCESS_GROUP)


def get_rank() -> int:
    """
    Current global GPU ID of Total GPUs:
    rank = machine_rank * num_gpu_per_machine + gpu_rank
    """
    if not dist.is_available():
        return 0
    if not dist.is_initialized():
        return 0
    return dist.get_rank()


def get_world_size() -> int:
    """
    The number of total GPUs on multiple machines.
    world_size = num_machine * num_gpus_per_machine
    """
    if not dist.is_available():
        return 1
    if not dist.is_initialized():
        return 1
    return dist.get_world_size()


```

My DALI code:
```python
import nvidia.dali.types as types
from nvidia.dali.pipeline import Pipeline

class ImageNetPipeline(Pipeline):
    def __init__(self, data_path, split):
        # fmt off:
        self.is_train          = split == 'train'
        self.order             = types.RGB
        self.mean              = _MEAN
        self.std               = _STD
        self.img_size_train    = 224
        self.img_size_test     = 256
        batch_size             = 128 # This is total batch size over all GPUs
        num_threads            = 64
        shuffle                = self.is_train
        exec_async             = False
        exec_pipelined         = False
        self.dali_cpu          = True
        self.prefetch_num      = 2
        self.rank              = get_rank()
        self.local_rank        = get_local_rank()
        self.world_size        = get_world_size()
        self.seed              = self.local_rank + random.randint(1, 1e4)
        # fmt on:

        # Here I print self.rank, self.local_rank and self.world_size for 1 and 2 GPUs
        # 2 GPUs Output: (0, 0, 2, 0) and (1, 1, 2, 1)
        # 1 GPU Output: (0, 0, 1, 0) only
        print(self.rank, self.local_rank, self.world_size, torch.cuda.current_device())
        assert batch_size % self.world_size == 0, f"batch size({batch_size}) % world_size({self.world_size}) == 0 required"
        batch_size_per_gpu = batch_size // self.world_size
        super(ImageNetPipeline, self).__init__(batch_size_per_gpu, num_threads, self.local_rank, exec_async=exec_async, exec_pipelined=exec_pipelined, prefetch_queue_depth=self.prefetch_num, seed=self.seed)
        data_dir = os.path.join(data_path, split)
        self.input = ops.FileReader(file_root=data_dir, shard_id=self.rank, num_shards=self.world_size, random_shuffle=shuffle, read_ahead=True)  # use shard_id to set total_imgs used in each self.rank
        self.decode = ops.ImageDecoder(device='cpu' if self.dali_cpu else 'mixed', output_type=self.order) # output images are `HWC` format

    def define_graph(self):
        jpegs, labels = self.input(name='Reader')
        images = self.decode(jpegs)
        return [images, labels]
```

**Comment by JanuszL** [comment]
This works fine for me:
```
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import numpy as np
import os
import random

import nvidia.dali.types as types
from nvidia.dali.pipeline import Pipeline

import torch
import torch.distributed as dist

_LOCAL_PROCESS_GROUP = None
"""
A torch process group that only includes processes that on the same machine as the current process.
This variable is set manually if multi-machine training is necessary.
"""

def get_local_rank() -> int:
    """
    Current local GPU ID of current machine:
    e.g., local_rank = 0-7 for 2 mahcines with 8 GPUs each.

    Note that sometimes there will be no local rank.
    Thus, we choose to return get_rank() as local rank in such cases.
    """
    if not dist.is_available():
        return 0
    if not dist.is_initialized():
        return 0
    if _LOCAL_PROCESS_GROUP is None:
        return dist.get_rank()
    return dist.get_rank(group=_LOCAL_PROCESS_GROUP)


def get_rank() -> int:
    """
    Current global GPU ID of Total GPUs:
    rank = machine_rank * num_gpu_per_machine + gpu_rank
    """
    if not dist.is_available():
        return 0
    if not dist.is_initialized():
        return 0
    return dist.get_rank()


def get_world_size() -> int:
    """
    The number of total GPUs on multiple machines.
    world_size = num_machine * num_gpus_per_machine
    """
    if not dist.is_available():
        return 1
    if not dist.is_initialized():
        return 1
    return dist.get_world_size()

class ImageNetPipeline(Pipeline):
    def __init__(self, data_path, split):
        # fmt off:
        self.is_train          = split == 'train'
        self.order             = types.RGB
        self.mean              = 0
        self.std               = 1
        self.img_size_train    = 224
        self.img_size_test     = 256
        batch_size             = 128 # This is total batch size over all GPUs
        num_threads            = 64
        shuffle                = self.is_train
        exec_async             = False
        exec_pipelined         = False
        self.dali_cpu          = True
        self.prefetch_num      = 2
        self.rank              = get_rank()
        self.local_rank        = get_local_rank()
        self.world_size        = get_world_size()
        self.seed              = self.local_rank + random.randint(1, 1e4)
        # fmt on:

        # Here I print self.rank, self.local_rank and self.world_size for 1 and 2 GPUs
        # 2 GPUs Output: (0, 0, 2, 0) and (1, 1, 2, 1)
        # 1 GPU Output: (0, 0, 1, 0) only
        print(self.rank, self.local_rank, self.world_size, torch.cuda.current_device())
        assert batch_size % self.world_size == 0, f"batch size({batch_size}) % world_size({self.world_size}) == 0 required"
        batch_size_per_gpu = batch_size // self.world_size
        super(ImageNetPipeline, self).__init__(batch_size_per_gpu, num_threads, self.local_rank, exec_async=exec_async, exec_pipelined=exec_pipelined, prefetch_queue_depth=self.prefetch_num, seed=self.seed)
        data_dir = os.path.join(data_path, split)
        self.input = ops.FileReader(file_root=data_dir, shard_id=self.rank, num_shards=self.world_size, random_shuffle=shuffle, read_ahead=True)  # use shard_id to set total_imgs used in each self.rank
        self.decode = ops.ImageDecoder(device='cpu' if self.dali_cpu else 'mixed', output_type=self.order) # output images are `HWC` format

    def define_graph(self):
        jpegs, labels = self.input(name='Reader')
        images = self.decode(jpegs)
        return [images, labels]

pipe = ImageNetPipeline("/home/dali_extra/db/single", "jpeg")
pipe.build()
out = pipe.run()
print(out)
```
and I run it with the following command:
`python -m torch.distributed.launch --nproc_per_node=1 test.py`
getting the output:
```
0 0 1 0
read 47 files from 19 directories
(<nvidia.dali.backend_impl.TensorListCPU object at 0x7f4394d03650>, <nvidia.dali.backend_impl.TensorListCPU object at 0x7f4394d03688>)
```

**Comment by ruiyuanlu** [comment]
Thanks. Actually, I use the python default `multiprocessing` library to start DDP training, which is fine when DALI is disabled. It seems DALI might need some environment settings processed by `torch.distributed.launch`. I'll try to add code to mimic the behavior of `torch.distributed.launch` ASAP to see if that's the reason.

**Comment by JanuszL** [comment]
If you can provide the full and self-contained reproduction then I can look into that.

> I use the python default multiprocessing library

Doesn't tell me much how you invoke everything.

**Comment by JanuszL** [comment]
@ruiyuanlu - if it still doesn't work for you please reopen.
