### ISSUE TITLE
Non matching dependency versions when docker-building Dali TensorFlow plugin

### ISSUE THREAD

**Issue by TheTimemaster** [NVIDIA/DALI#2448]
I am trying to build DALI from source with TF plugins using following command: 
`sudo CUDA_VERSION=11.0 BUILD_TF_PLUGIN=YES CREATE_RUNNER=YES ./build.sh`

When reached the step:
`Building DALI TF plugin for TF version na 1.15.4+nv20.10`

I am getting following exception:
```
+++ echo nvidia-tensorflow==1.15.4+nv20.10
+++ sed 's/.*=\([0-9]\+\)\.\([0-9]\+\).*/\1_\2/'
++ SUFFIX=1_15
++ LIB_PATH=/prebuilt/5.4/libdali_tf_1_15.so
++ source ./build_dali_tf.sh /prebuilt/5.4/libdali_tf_1_15.so
+++ COMPILER=g++
+++ PYTHON=python
+++ LIB_NAME=/prebuilt/5.4/libdali_tf_1_15.so
+++ SRCS='daliop.cc dali_dataset_op.cc'
+++ INCL_DIRS=-I/usr/local/cuda/include/
++++ mktemp -d -t dali_stub_XXXXXX
+++ DALI_STUB_DIR=/tmp/dali_stub_WQGPcB
+++ DALI_STUB_SRC=/tmp/dali_stub_WQGPcB/dali_stub.cc
+++ DALI_STUB_LIB=/tmp/dali_stub_WQGPcB/libdali.so
+++ python ../tools/stubgen.py ../include/dali/c_api.h --output /tmp/dali_stub_WQGPcB/dali_stub.cc
+++ DALI_CFLAGS=-I../include
+++ DALI_LFLAGS='-L/tmp/dali_stub_WQGPcB -ldali'
+++ g++ -std=c++11 -DNDEBUG -O2 -shared -fPIC /tmp/dali_stub_WQGPcB/dali_stub.cc -o /tmp/dali_stub_WQGPcB/libdali.so -I/usr/local/cuda/include/ -I../include
+++ TF_CFLAGS=($($PYTHON -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))'))
++++ python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
```

The whole process works, if this version is removed from `qa/setup_packages.py`

**Comment by JanuszL** [comment]
The problem is that the nvidia-tensorflow [works only on Ubuntu18.04 or newer](https://github.com/NVIDIA/tensorflow) and the custom op builder is meant mostly for building a custom plugin for TensorFlow using tensorflow/tensorflow:custom-op-gpu-ubuntu16 (as this is the only one that is a guarantee to yield a compatible binary with the upstream TensorFlow code), so that is why you see that error.
DALI delivers the TF plugin as a source code and prebuilds binary for selected TF versions. If there is no prebuild and you have an appropriate environment to build it on the fly it will be built. In the case of nvidia-tensorflow when you install it you have the env to build plugin on the fly, so I think we should just skip the plugin build for nvidia-tensorflow.
Will try to handle this in the build process, also [this](https://github.com/NVIDIA/DALI/pull/2449) seems to be not relevant in that case.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2451 tries to address this issue.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2451 should address this. Pease update your fork and see if that helps.

**Comment by JanuszL** [comment]
0.29 has been released and should address this issue.
