### ISSUE TITLE
ImageDecoder returns a tensor of ByteTensor?

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2460]
Hi,

Thanks for your help! I am decoding images with ops.Imagedecoder and find an issue.

It raises an error when I feed the tensor to my model:

~~~
RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.FloatTensor) should be the same.
~~~

I think it may be raised by ops.Imagedecoder just returns a tensor consisting of 0-255? Or how should I fix it? Thanks!

For convenience, the complete error log is attached:

~~~
Traceback (most recent call last):
  File "/mnt/yunle/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/admin/pose/tmp2/pytorch-pose-HigherHRNet/tools/dist_train.py", line 281, in main_worker
    do_train(cfg, model, train_loader, loss_factory, optimizer, epoch,
  File "/home/admin/pose/tmp2/pytorch-pose-HigherHRNet/tools/../lib/core/trainer.py", line 40, in do_train
    outputs = model(images)
  File "/mnt/yunle/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/yunle/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/mnt/yunle/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin/pose/tmp2/pytorch-pose-HigherHRNet/tools/../lib/models/pose_higher_hrnetv53.py", line 773, in forward
    x = self.conv1(x)
  File "/mnt/yunle/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/yunle/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/mnt/yunle/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 341, in conv2d_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.FloatTensor) should be the same
~~~

**Comment by JanuszL** [comment]
Hi,
I think you should check [RN50 example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html) and use CropMirrorNormalize to scale the outputs to 0-1.0 range.
