### ISSUE TITLE
Variable length video ?

### ISSUE THREAD

**Issue by miraodasilva** [NVIDIA/DALI#2464]
From what I can gather, loading variable length videos is not supported. Is this correct? If so, is there any way to work around this? For instance, is there a way to randomly sample N frames from every video so that the variable length is implicity dealt with and we produce consistent batches of N frames? I have done this in the pytorch dataloader for multiple projects. 

I would really like to use DALI since data loading is clearly the bottleneck for me at the moment, but I work almost exclusively with datasets featuring variable length video.

Thanks a lot.

**Comment by JanuszL** [comment]
Hi,
VideoReader works fine with videos of different lengths, what is not supported is variable frame rate videos.

>  is there a way to randomly sample N frames from every video so that the variable length is implicity dealt with and we produce consistent batches of N frames

DALI doesn't support this, what DALI does is to randomly select the first frame (taken into account step), and then N consecutive frames distant by stride. It should be possible to extend this to just randomly select any N frames from video, we would be more than happy to accept any PR that would introduce such functionality.

**Comment by miraodasilva** [comment]
> what DALI does is to randomly select the first frame (taken into account step), and then N consecutive frames distant by stride
Actually, this is exactly what I wanted to do, I just didn't understand that randomly picking the first frame and getting N consecutive frames was the default behavior. This being said, I still don't understand what the parameter "step" does. I read in the docs:

> step (int, optional, default = 1) – Distance between first frames of consecutive sequences.

But this doesn't really make it clearer for me. From what I understand, if we have video 1 and video 2, we randomly pick start frame A from video 1, we get N frames spaced by "stride", and the we move on to video 2 and do the same thing. Where does step come in to the picture? Sorry if I am missing something obvious.

**Comment by JanuszL** [comment]
DALI first collects are available sequences from all listed videos given step, stride and length. For example, video1 - 10 frames, video2 5 frames, length=3, step=1, stride=2. Sequences are:
- video1: [0 , 2, 4], [1, 3, 5], [2, 4, 5], [3, 5, 7], [4, 6, 8], [5, 7, 9]
- video2 [0 , 2, 4], [1, 3, 5]

Then DALI randomly picks one sequence and process it.

**Comment by miraodasilva** [comment]
I see, thanks a lot! 

I apologise for the incessant questions but I have just one more: I typically work with audiovisual content, and I would like to load paired data. Therefore, I need the file name, start frame and end frame of the sequence that was selected in order to get the specific audio segment that matches the X frames of video I just got. Is there a way to obtain this at each iteration? I checked the docs and it seems like enable_frame_num might be related to this, but it is not compatibly with the paramter filenames (which is what I use), only with file_root and file_list. Also I'm not sure if this would solve my issue.

Thanks a lot in advance!

**Comment by JanuszL** [comment]
Hi,
Yes, `enable_frame_num` should help you. Now it is not compatible with the plain `file_root` parameter. What you can do it to create a `file_list` based on your root dir content and pass it to DALI.
In the meantime, I created a PR that should lift that restriction - https://github.com/NVIDIA/DALI/pull/2468. Please check the nightly build after it is merged.

**Comment by miraodasilva** [comment]
Sorry for the late reply, I have been AFK for the past days. Thanks so much for your support and patience on this, I will try it out soon!

By the way, as far as you know, was there a reason for this restriction in the first place? Thanks again.

**Comment by JanuszL** [comment]
> By the way, as far as you know, was there a reason for this restriction in the first place? Thanks again.

I don't remember what was the reason, sorry.

**Comment by miraodasilva** [comment]
Thanks so much, I see this has been added in the new version. However, unfortunately I can only manage to get my example working with filenames, not with file_list or file_root. To be clear, this does not have to do with enable frame_num yet, I would just like to get a functional video reader. If I use a file_list with the exact same content of filenames (with 0 as a label) it does not work. My code is as follows:

```
import os
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
from nvidia.dali.plugin.pytorch import DALIGenericIterator


if __name__ == "__main__":
    batch_size = 32
    sequence_length = 25
    initial_prefetch_size = 16
    video_directory = "VoxCeleb2/video/dev/mp4_stabilized"
    shuffle = True
    n_iters = 6
    count = 0
    video_files = []
    for root, _, files in os.walk(video_directory):
        for f in files:
            if f.endswith(".mp4"):
                video_files += [os.path.join(root, f)]
                count += 1
        if count == 10:
            break

    video_list = "./my_list.txt"
    with open(video_list, "w") as f:
        for path in video_files:
            f.write(path + " 0\n")

    class VideoLoader(Pipeline):
        def __init__(self, batch_size, num_threads, device_id, filelist, shuffle):
            super(VideoLoader, self).__init__(batch_size, num_threads, device_id, seed=16)
            print(video_directory)
            self.input = ops.VideoReaderResize(
                device="gpu",
                filenames=video_files,
                sequence_length=sequence_length,
                shard_id=0,
                num_shards=1,
                random_shuffle=shuffle,
                initial_fill=initial_prefetch_size,
                resize_x=96,
                resize_y=96,
            )

        def define_graph(self):
            output = self.input(name="Reader")
            return output

    pipes = [VideoLoader(batch_size, 2, 0, video_list, shuffle)]
    pipes[0].build()
    dali_iter = DALIGenericIterator(pipes, ["data"], pipes[0].epoch_size("Reader"))
    for i, data in enumerate(dali_iter):
        print(data[0]["data"].size())

```

If I use "file_names=video_files", it works perfectly. If I use "file_list=video_list" I get 
```
Traceback (most recent call last):
  File "dali.py", line 61, in <module>
    dali_iter = DALIGenericIterator(pipes, ["data"], pipes[0].epoch_size("Reader"))
  File "miniconda3/envs/torch1-7/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 170, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "miniconda3/envs/torch1-7/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 189, in __next__
    category_outputs[self.output_map[j]] = out
IndexError: list index out of range
```
If I use "file_root=video_directory" I get
```
Error when constructing operator: VideoReaderResize encountered:
[/opt/dali/dali/operators/reader/loader/video_loader.h:173] Assert on "!file_info_.empty()" failed: No files were read.
```
The video_directory contains folders, with folders, with .mp4s. Sorry for the hassle but I have been working on this and looking through the docs for a while and I still don't get it. Thanks a lot in advance.

**Comment by miraodasilva** [comment]
I figured out my bug with file_list (embarassingly right after writing  the above comment): since I am loading the placeholder labels I need to return "output[0]" rather than just "output" in define_graph. However, I still don't understand what's wrong with file_root=video_directory.

**Comment by miraodasilva** [comment]
By the way, is there a reason enable_frame_num is incompatible with filenames?

**Comment by JanuszL** [comment]
> By the way, is there a reason enable_frame_num is incompatible with filenames?

The https://github.com/NVIDIA/DALI/pull/2468 **enables** frame numbers for filenames as log as `labels` are set. Without it, even if you have a timestamp but no label you cannot match it to the corresponding video file. It is still disabled for `file_root` as DALI assigns classes to the videos on its own and the user cannot match the class to the particular video file, so frame numbers/time stamps won't yield much information.

> However, I still don't understand what's wrong with file_root=video_directory.

The folder structure should have root_dir/classes/files, for example, you can pass `https://github.com/NVIDIA/DALI_extra/tree/master/db/video/multiple_framerate` as a root dir and it should work.

**Comment by miraodasilva** [comment]
I see, that makes sense, thanks a lot for the response. I got it working now. WIth label and frame number I can access the exact corresponding audio sequence. However, from what I can see this can only be done outside of the dataloader, so basically I would have to load the video using DALI, and then I would take the labels and frame numbers and load each audio file individually. Even though audio is lighter than video, this seems somewhat inefficient. Is there anyway to do what I describe within the DALI loader/pipeline itself, effectively achieving the Audiovisual loader I would like to have?

**Comment by JanuszL** [comment]
> Is there anyway to do what I describe within the DALI loader/pipeline itself, effectively achieving the Audiovisual loader I would like to have?

Currently, it is not possible to synchronize the two different readers inside DALI.

**Comment by miraodasilva** [comment]
I see. Are there any plans for this in the future? I expect it would be good not only for AV research but for many other types of paired data loading.

Anyway I really appreciate your help. I will benchmark my version of the audiovisual loader (half DALI half hardcoded) to see if there are improvements over a traditional pytorch AV loader. Thanks so much.

**Comment by JanuszL** [comment]
> I see. Are there any plans for this in the future? I expect it would be good not only for AV research but for many other types of paired data loading.

There is no timeline we can share yet, still, we are aware of this limitation and it is high on our ToDo list.

**Comment by hyperfraise** [comment]
This would be really useful for light inference with nvidia dali, where the reencoding takes away the advantage of this software.
