### ISSUE TITLE
Can not import 'nvidia.dali.plugin.tf'

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2493]
Hi,

When I am trying to import 'nvidia.dali.plugin.tf':
~~~
import nvidia.dali.plugin.tf as dali_tf
~~~

It raises an error:
~~~
Traceback (most recent call last):
  File "asr_e2e_pinyin_ctc_6x.py", line 233, in <module>
    tfASRDataSet = TFASRDataSet(tokenizer, tokenizer, pinyin_tokenizer, aiConfig.root_file_paths, aiConfig, mode='train')
  File "../../data/data_loader_asr_all.py", line 428, in __init__
    self.iterator = self.setDataSetIterator(aiConfig)
  File "../../data/data_loader_asr_all.py", line 469, in setDataSetIterator
    import nvidia.dali.plugin.tf as dali_tf
  File "/home/admin/miniconda3/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 23, in <module>
    from nvidia.dali_tf_plugin import dali_tf_plugin
ModuleNotFoundError: No module named 'nvidia.dali_tf_plugin'
~~~

How should I fix it?

**Comment by JanuszL** [comment]
Please install the DALI TensorFlow plugin as well according to [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#dali-tensorflow-plugin-nvidia-dali-tf-plugin)and you need to have TensorFlow installed first.
