### ISSUE TITLE
RuntimeError: CUDA runtime API error cudaErrorInvalidDevice (101): invalid device ordinal

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2521]
Hi,

Thanks for your help! I am facing a problem:

~~~
Traceback (most recent call last):
  File "/home/admin/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/admin/nas_experiments/pytorch-pose-HigherHRNet/tools/dist_train.py", line 238, in main_worker
    cfg, is_train=True, distributed=args.distributed
  File "/home/admin/nas_experiments/pytorch-pose-HigherHRNet/tools/../lib/dataset/build.py", line 124, in make_dataloader
    category='detection'
  File "/home/admin/miniconda3/lib/python3.7/site-packages/wutong_dali_pytorch/dataloader.py", line 145, in __init__
    self._build_dali_pipeline()
  File "/home/admin/miniconda3/lib/python3.7/site-packages/wutong_dali_pytorch/dataloader.py", line 159, in _build_dali_pipeline
    self.train_loader = iterator_train(pipelines=train_pipes, size=60353, fp16=self.fp16, mean=self.mean, std=self.std, pin_memory=self.pin_memory)
  File "/home/admin/miniconda3/lib/python3.7/site-packages/wutong_dali_pytorch/dali_pipe.py", line 197, in __init__
    self._dali_iterator = DALIDetectionIterator(pipelines=pipelines, size=size)
  File "/home/admin/miniconda3/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 477, in __init__
    last_batch_policy = last_batch_policy)
  File "/home/admin/miniconda3/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 162, in __init__
    _DaliBaseIterator.__init__(self, pipelines, size, reader_name, auto_reset, fill_last_batch, last_batch_padded, last_batch_policy)
  File "/home/admin/miniconda3/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 163, in __init__
    p.build()
  File "/home/admin/miniconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 479, in build
    self._prepare_graph(define_graph)
  File "/home/admin/miniconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 370, in _prepare_graph
    self._default_cuda_stream_priority)
RuntimeError: CUDA runtime API error cudaErrorInvalidDevice (101):
invalid device ordinal
~~~

Here is my code:
~~~
train_pipes = [COCOPipeline(batch_size=self.batch_size, num_threads=self.workers, device_id = i, num_gpus=self.num_gpus, masks=True, file_root=self.train_dir, annotations_file = os.path.join(self.root_dir, 'annotations', 'person_keypoints_train.json'))  for i in range(self.num_gpus)]
~~~

Thanks!

**Comment by JanuszL** [comment]
Hi,
How do launch training with DALI?
I guess you are using a distributed data parallel strategy. In this case please check this example https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html and create only one pipeline per process. Also, make sure that the `device_id` argument has the correct value.

**Comment by zhiheng-ldj** [comment]
> Hi,
> How do launch training with DALI?
> I guess you are using a distributed data parallel strategy. In this case please check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html) and create only one pipeline per process. Also, make sure that the `device_id` argument has the correct value.

Hi,
I am indeed using DDP. How should I create only one pipeline per process? Could you explain it more specifically?
Thanks!

**Comment by JanuszL** [comment]
As said, please check [this particular RN50 example](https://github.com/NVIDIA/DALI/blob/49192e45672022d4479ccd998ad1931661daf04f/docs/examples/use_cases/pytorch/resnet50/main.py).
