### ISSUE TITLE
auto_reset not work and weird WARNING when using DALIClassificationIterator

### ISSUE THREAD

**Issue by PistonY** [NVIDIA/DALI#2559]
Hi, I try to use DALI to speed up my ImageNet training.
But I found that `auto_reset=True` is not work for `DALIClassificationIterator` and I manually call `loader..reset()`, it would give me a warning `WARNING:root:DALI iterator does not support resetting while epoch is not finished. Ignoring...`

Here is my test code.

```python
class TrainPipe(Pipeline):
    def __init__(self, root, batch_size, num_workers, rank, world_size, size, color_jit, dali_cpu=False):
        super(TrainPipe, self).__init__(batch_size, num_workers, rank)
        self.input = ops.FileReader(file_root=root,
                                    shard_id=rank,
                                    num_shards=world_size,
                                    random_shuffle=True,
                                    pad_last_batch=True)

        dali_device = 'cpu' if dali_cpu else 'gpu'
        decoder_device = 'cpu' if dali_cpu else 'mixed'
        device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
        host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
        self.decode = ops.ImageDecoderRandomCrop(device=decoder_device, output_type=types.RGB,
                                                 device_memory_padding=device_memory_padding,
                                                 host_memory_padding=host_memory_padding,
                                                 num_attempts=100)
        self.resize = ops.Resize(device=dali_device,
                                 resize_x=size,
                                 resize_y=size,
                                 interp_type=types.INTERP_TRIANGULAR)

        self.color_jitter = ops.ColorTwist(device=dali_device)

        self.cmnp = ops.CropMirrorNormalize(device="gpu", dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(size, size),
                                            mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                                            std=[0.229 * 255, 0.224 * 255, 0.225 * 255])

        self.coin = ops.CoinFlip(probability=0.5)
        self.uniform = ops.Uniform(range=(max(0., 1 - color_jit), 1 + color_jit))

    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        images = self.resize(images)
        images = self.color_jitter(images,
                                   brightness=self.uniform(),
                                   contrast=self.uniform(),
                                   saturation=self.uniform())
        images = self.cmnp(images.gpu(), mirror=self.coin())
        return [images, self.labels.gpu()]


class ValPipe(Pipeline):
    def __init__(self, root, batch_size, num_workers, rank, crop):
        super(ValPipe, self).__init__(batch_size, num_workers, rank)
        self.input = ops.FileReader(file_root=root,
                                    shard_id=rank,
                                    num_shards=1,
                                    random_shuffle=False,
                                    pad_last_batch=True)
        self.decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)
        self.resize = ops.Resize(device="gpu",
                                 resize_shorter=int(crop / 0.875),
                                 interp_type=types.INTERP_TRIANGULAR)
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(crop, crop),
                                            mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                                            std=[0.229 * 255, 0.224 * 255, 0.225 * 255])

    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        images = self.resize(images)
        output = self.cmnp(images)
        return [output, self.labels.gpu()]

if __name__ == '__main__':
    from nvidia.dali.plugin.pytorch import DALIClassificationIterator, \
        LastBatchPolicy

    # train_pipe = TrainPipe('/data4/MiniImageNet/val', 512, 4, 1, 2, 224, 0.4)
    # train_pipe.build()
    # train_loader = DALIClassificationIterator(train_pipe, reader_name="Reader", auto_reset=True,
    #                                           last_batch_policy=LastBatchPolicy.DROP)
    #
    # for meta_data in train_loader:
    #     print(meta_data[0]["data"].shape)
    #     print(meta_data[0]["label"].squeeze(-1).long())
    #     # break
    #
    val_pipe = ValPipe('/data4/MiniImageNet/val', 512, 4, 0, 224)
    val_pipe.build()
    val_loader = DALIClassificationIterator(val_pipe, reader_name="Reader", auto_reset=True,
                                            last_batch_policy=LastBatchPolicy.PARTIAL)
    #
    for meta_data in val_loader:
        # print(meta_data[0]["data"].shape)
        label = meta_data[0]["label"].squeeze(-1).long()
        print(label)
        print(label.shape)
        # break

    val_loader.reset()
    print("First Done!")
    for meta_data in val_loader:
        # print(meta_data[0]["data"].shape)
        label = meta_data[0]["label"].squeeze(-1).long()
        print(label)
        print(label.shape)
```
I tested both `train_loader` and `val_loader` and results are same.
Could you please give me some advice.

**Comment by JanuszL** [comment]
Hi,

> But I found that auto_reset=True is not work for DALIClassificationIterator

Why do you think so? When I removed `val_loader.reset()` from your code the second iteration still works. If you additionally set `auto_reset=False` then the second iteration would be empty as the DALI iterator has been depleted.
Keep in mind that this reset only affects the iterator behavior, not the DALI pipeline which keeps running under the hood.

**Comment by PistonY** [comment]
Hi，I think we got different result, when I remove reset the next iteration is empty.

**Comment by JanuszL** [comment]
What DALI version do you have? I checked this in 0.28.

**Comment by PistonY** [comment]
Hi, Did you test train pipe?
I also found that `val_loader` works with `auto_reset=True`, but `train_loader` not.
Could you please run this and give me a result.
```python
if __name__ == '__main__':
    from nvidia.dali.plugin.pytorch import DALIClassificationIterator, \
        LastBatchPolicy

    train_pipe = TrainPipe('/data4/MiniImageNet/val', 512, 4, 1, 2, 224, 0.4)
    train_pipe.build()
    train_loader = DALIClassificationIterator(train_pipe, reader_name="Reader", auto_reset=True,
                                              last_batch_policy=LastBatchPolicy.DROP)

    #
    # val_pipe = ValPipe('/data4/MiniImageNet/val', 512, 4, 0, 224)
    # val_pipe.build()
    # val_loader = DALIClassificationIterator(val_pipe, reader_name="Reader", auto_reset=True,
    #                                         last_batch_policy=LastBatchPolicy.PARTIAL)

    for meta_data in train_loader:
        # print(meta_data[0]["data"].shape)
        label = meta_data[0]["label"].squeeze(-1).long()
        print(label)
        print(label.shape)
        # break

    print("First Done!")
    for meta_data in train_loader:
        # print(meta_data[0]["data"].shape)
        label = meta_data[0]["label"].squeeze(-1).long()
        print(label)
        print(label.shape)

```
This is mine.
```shell
read 5000 files from 100 directories
tensor([44,  8, 76, 24, 92, 25, 36, 50,  1, 89, 90, 24, 47, 16, 44, 18, 96, 11,
        85, 46, 13,  9, 14, 79,  9, 73, 52, 77, 74, 78, 38, 49, 88,  1,  4, 75,
        13, 18, 68, 94, 14, 79,  9, 15,  5, 96, 43, 93, 58, 92, 80, 61, 83, 17,
        55, 81, 44, 52, 19, 48, 32, 45, 88, 97, 73, 62, 66, 84, 92, 57, 62,  8,
        10, 21, 58, 65,  6, 57,  3,  0, 42,  9, 14,  8, 62, 37,  1,  3, 71, 99,
        33, 55, 61, 38, 35, 34, 58, 68, 49, 30, 44, 75, 59, 48,  9, 38, 14, 32,
        96, 92, 41, 90, 67, 20, 96, 28, 94, 52, 76, 72, 52, 35, 30, 84, 11, 82,
        81, 13, 42, 69, 50, 39, 51, 49, 41, 11, 26, 74, 91, 62, 96,  9, 59, 66,
        54, 91, 53, 30, 60,  6,  2, 99, 12, 33, 98, 51, 20, 37, 36, 20,  3, 56,
        83, 74, 31, 86, 15, 35, 84, 43, 75, 67, 74, 85, 24, 29, 61, 60, 21, 96,
        93, 43,  8, 87, 81,  0, 57, 53, 77, 42, 73, 24, 88, 66, 59, 39, 18, 98,
        10, 79, 76,  5, 52, 90, 26, 36, 91, 86,  4, 85, 24, 20, 60, 55, 44, 95,
        73, 51, 68, 35, 44, 79, 44, 40, 80, 64, 36,  3, 99,  1, 34, 67, 87,  3,
        29, 18, 11, 42,  7, 21,  5, 23, 70, 76, 20, 20, 56, 25,  0, 47, 86, 20,
        40, 42, 83, 37, 49, 55, 95, 20, 52, 95, 34, 26, 23, 14, 60, 56, 86, 72,
        11, 63, 28, 48, 96, 41, 23, 46, 73, 12, 53, 36, 29, 81,  9, 62, 99, 87,
        32, 47, 80, 52, 63, 99, 47, 87, 49, 29, 76, 12, 14, 40, 36, 16, 71, 67,
        53, 82, 36, 32, 90, 81, 82,  3, 61, 85, 64, 98, 61, 88, 93, 36, 68, 49,
        36, 22, 97, 72, 91, 50, 14, 80, 90, 55, 12, 97, 99, 27, 44,  2, 66, 65,
        72, 21, 33, 61, 25, 35, 63, 45, 49, 48, 89, 23, 53, 24,  5, 26, 64,  7,
        35, 31, 13, 47, 87,  1, 24, 93,  8, 29, 35, 96, 32, 11, 27, 71, 83, 87,
        87, 19,  8,  8, 98, 37, 68, 18,  5, 84, 78, 24,  5, 78, 15, 45, 40, 97,
        22, 59, 28, 23, 49, 64, 59, 79, 65, 90, 97,  5, 98, 90, 70, 41, 18, 79,
        44, 58, 12, 48, 87, 51, 30, 53,  4, 33, 97, 82, 42, 44, 27,  5, 48, 17,
        72, 22, 87, 59, 82, 64, 62,  4, 91, 44, 45, 47,  3, 94,  4, 44, 20, 22,
        30, 99,  3, 13, 14, 63, 81, 11,  7, 40, 41, 65, 62, 65, 84, 95,  9, 24,
        16, 90, 62, 93, 34, 16, 95, 29, 13, 21, 82,  2, 26, 48, 38, 20, 17, 43,
        31, 43, 51, 23,  6, 59,  8, 69, 92, 83, 64, 83,  8, 45, 11, 54,  3, 57,
        38, 56, 69, 25, 23, 89, 10, 16], device='cuda:1')
torch.Size([512])

.....

First Done!

Process finished with exit code 0

```

**Comment by JanuszL** [comment]
Hi,
Just reproduced the problem. Auto-reset seems not to work with `LastBatchPolicy.DROP`. https://github.com/NVIDIA/DALI/pull/2567 should fix that.
For now please manually reset the iterator. You can check the nightly build after the mentioned PR is merged.

**Comment by PistonY** [comment]
Thanks

**Comment by PistonY** [comment]
Hi, @JanuszL , Do you ever compare DALI pipe with Pytorch original pipe on ImageNet training result.
I define pytorch pipe as below:
```python
train_transform = transforms.Compose([
                transforms.RandomResizedCrop(input_size),
                transforms.RandomHorizontalFlip(),
                transforms.ColorJitter(0.4, 0.4, 0.4),
                transforms.ToTensor(),
                normalize,
            ])
train_set = ImageFolder(os.path.join(args.in_path, 'train'), transform=train_transform)
train_sampler = DistributedSampler(train_set)
train_loader = DataLoader(train_set, args.batch_size, False, pin_memory=True,
                          num_workers=args.num_workers, drop_last=True, sampler=train_sampler)

val_transform = transforms.Compose([
                transforms.Resize(int(input_size / 0.875)),
                transforms.CenterCrop(input_size),
                transforms.ToTensor(),
                normalize,
            ])
val_set = ImageFolder(os.path.join(args.in_path, 'val'), transform=val_transform)
val_loader = DataLoader(val_set, args.batch_size, False, pin_memory=True, num_workers=args.num_workers,
                        drop_last=False)
```
DALI pipe as I wrote in this issue.
I train on entire ImageNet dataset not miniImageNet, the result of DALI drop 1% accuracy than pytorch pipe.
If you have interest [this](https://github.com/PistonY/ModelZoo.pytorch/blob/master/scripts/distribute_train_script.py) is my script.
Could you please give me some advice about this.
Why this happened? Do I have something wrong with building DALI pipe?

**Comment by JanuszL** [comment]
Your pipeline looks good. We have not compared the accuracy with such a pipeline definition. The one we test regularly is [this one](https://github.com/NVIDIA/DALI/tree/master/docs/examples/use_cases/pytorch) using full, raw ImageNet - we usually get >= 75.8 without any special hyperparameters selection. You can also check https://github.com/NVIDIA/DeepLearningExamples repo where DALI is used the RN50 network family in different frameworks - MXNet, PyTorch, and TensorFlow without accuracy drop.

**Comment by PistonY** [comment]
Thx @JanuszL , I've already fix this.
Does auto_reset bug fix in version of 0.19?

**Comment by JanuszL** [comment]
@PistonY it is still under review, it may be included in 0.30 or 0.31.

**Comment by PistonY** [comment]
Thanks for your help @JanuszL

**Comment by PistonY** [comment]
Hi @JanuszL , Does DALI support dynamic input size with RandomResizedCrop, what I mean is that the size may random choice from a list/tuple in this batch(this batch data size may (32, 3, 128, 128)), and next batch are different(may (32, 3, 224, 224))?

**Comment by JanuszL** [comment]
> Hi @JanuszL , Does DALI support dynamic input size with RandomResizedCrop, what I mean is that the size may random choice from a list/tuple in this batch(this batch data size may (32, 3, 128, 128)), and next batch are different(may (32, 3, 224, 224))?

RandomResizedCrop supports only random selection from the range, not a fixed set of sizes. Do you want to randomly select resize scale or crop? Maybe you don't need to use RandomResizedCrop but Resize and Crop?

**Comment by PistonY** [comment]
> > Hi @JanuszL , Does DALI support dynamic input size with RandomResizedCrop, what I mean is that the size may random choice from a list/tuple in this batch(this batch data size may (32, 3, 128, 128)), and next batch are different(may (32, 3, 224, 224))?
> 
> RandomResizedCrop supports only random selection from the range, not a fixed set of sizes. Do you want to randomly select resize scale or crop? Maybe you don't need to use RandomResizedCrop but Resize and Crop?

My scale and crop are fixed, but the final resize size is dynamic. That's mean before resize is totally same with `RandomResizedCrop` but the resize size is not a fixed number.

**Comment by JanuszL** [comment]
What you can do is try using [`ImageDecoderRandomCrop`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.ImageDecoderRandomCrop) and the regular resize with your custom scale. Or compose RandomResizedCrop using Slice, Resize, and arithmetic operators to generate parameters for slice based on input image shape (obtained by either Shape or PeekImageShape operators).

**Comment by PistonY** [comment]
Thx @JanuszL , I'll try that later.

**Comment by PistonY** [comment]
Hi @JanuszL , based on before discuss. I tried as below:
I use `ops.Uniform(values=sizes)` as a random number generator and call it at `define_graph` then give the size value to `Resize`, but `CropMirrorNormalize` seems not support get value when call it?

```python
class DynamicTrainPipe(Pipeline):
    def __init__(self, root, batch_size, num_workers, rank, world_size, sizes, color_jit, dali_cpu=False):
        super().__init__(batch_size, num_workers, rank)
        self.input = ops.FileReader(file_root=root,
                                    shard_id=rank,
                                    num_shards=world_size,
                                    random_shuffle=True,
                                    pad_last_batch=True)

        dali_device = 'cpu' if dali_cpu else 'gpu'
        decoder_device = 'cpu' if dali_cpu else 'mixed'
        device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
        host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
        self.decode = ops.ImageDecoderRandomCrop(device=decoder_device,
                                                 output_type=types.RGB,
                                                 device_memory_padding=device_memory_padding,
                                                 host_memory_padding=host_memory_padding,
                                                 num_attempts=100)

        self.resize = ops.Resize(device=dali_device, interp_type=types.INTERP_TRIANGULAR)

        self.color_jitter = ops.ColorTwist(device=dali_device)

        self.cmnp = ops.CropMirrorNormalize(
            device="gpu",
            dtype=types.FLOAT,
            output_layout=types.NCHW,
            # crop=(size, size),
            mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
            std=[0.229 * 255, 0.224 * 255, 0.225 * 255])

        self.coin = ops.CoinFlip(probability=0.5)
        self.uniform = ops.Uniform(range=(max(0., 1 - color_jit), 1 + color_jit))
        self.dy_size = ops.Uniform(values=sizes)

    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        size = self.dy_size()
        images = self.decode(self.jpegs)
        images = self.resize(images, resize_x=size, resize_y=size)
        images = self.color_jitter(images, brightness=self.uniform(), contrast=self.uniform(), saturation=self.uniform())
        images = self.cmnp(images.gpu(), mirror=self.coin(), crop=(size, size))
        return [images, self.labels.gpu()]

if __name__ == '__main__':
    from nvidia.dali.plugin.pytorch import (DALIClassificationIterator, LastBatchPolicy)
    train_pipe = DynamicTrainPipe('/data4/MiniImageNet/val', 64, 4, 0, 1, [128, 160, 192, 224], 0.4)
    with logger.catch():
        train_pipe.build()
    train_loader = DALIClassificationIterator(train_pipe,
                                              reader_name="Reader",
                                              auto_reset=True,
                                              last_batch_policy=LastBatchPolicy.DROP)

    for meta_data in train_loader:
        print(meta_data[0]["data"].shape)
        label = meta_data[0]["label"].squeeze(-1).long()
        print(label)
        print(label.shape)
        break
```
I got the error below:
```shell
2021-03-03 17:04:12.817 | ERROR    | __main__:<module>:135 - An error has been caught in function '<module>', process 'MainProcess' (22840), thread 'MainThread' (139736456836864):
Traceback (most recent call last):

> File "/home/xuyang/Projects/ModelZoo.deepmotion/engine/utils/dali_pipe.py", line 135, in <module>
    train_pipe.build()
    │          └ <function Pipeline.build at 0x7f16b09080d0>
    └ <__main__.DynamicTrainPipe object at 0x7f16edc71550>

  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 479, in build
    self._prepare_graph(define_graph)
    │    │              └ None
    │    └ <function Pipeline._prepare_graph at 0x7f16b090ef70>
    └ <__main__.DynamicTrainPipe object at 0x7f16edc71550>
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 386, in _prepare_graph
    outputs = define_graph()
              └ <bound method DynamicTrainPipe.define_graph of <__main__.DynamicTrainPipe object at 0x7f16edc71550>>

  File "/home/xuyang/Projects/ModelZoo.deepmotion/engine/utils/dali_pipe.py", line 114, in define_graph
    images = self.cmnp(images.gpu(), mirror=self.coin(), crop=(size, size))
             │    │    │      │             │    │             │     └ <nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>
             │    │    │      │             │    │             └ <nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>
             │    │    │      │             │    └ <nvidia.dali.ops.python_op_factory.<locals>.Operator object at 0x7f16afe6c3d0>
             │    │    │      │             └ <__main__.DynamicTrainPipe object at 0x7f16edc71550>
             │    │    │      └ <function DataNode.gpu at 0x7f16b33773a0>
             │    │    └ <nvidia.dali.pipeline.DataNode object at 0x7f163ccdbc10>
             │    └ <nvidia.dali.ops.python_op_factory.<locals>.Operator object at 0x7f16afe6c370>
             └ <__main__.DynamicTrainPipe object at 0x7f16edc71550>

  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/ops.py", line 522, in __call__
    op_instances.append(_OperatorInstance(input_set, self, **kwargs))
    │            │      │                 │          │       └ {'mirror': <nvidia.dali.pipeline.DataNode object at 0x7f163ccdbdc0>, 'crop': (<nvidia.dali.pipeline.DataNode object at 0x7f16...
    │            │      │                 │          └ <nvidia.dali.ops.python_op_factory.<locals>.Operator object at 0x7f16afe6c370>
    │            │      │                 └ [<nvidia.dali.pipeline.DataNode object at 0x7f16ae6b7760>]
    │            │      └ <class 'nvidia.dali.ops._OperatorInstance'>
    │            └ <method 'append' of 'list' objects>
    └ []
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/ops.py", line 306, in __init__
    _add_spec_args(op._schema, self._spec, spec_args)
    │              │  │        │    │      └ {'crop': (<nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>, <nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>)}
    │              │  │        │    └ OpSpec for CropMirrorNormalize:
    │              │  │        │        Inputs:
    │              │  │        │        Outputs:
    │              │  │        │        Arguments:
    │              │  │        │          std: [58.395000, 57.119999, 57.375000, ]
    │              │  │        │          mean: [123...
    │              │  │        └ <nvidia.dali.ops._OperatorInstance object at 0x7f163ccdbd90>
    │              │  └ <nvidia.dali.backend_impl.OpSchema object at 0x7f16ae6bbfb0>
    │              └ <nvidia.dali.ops.python_op_factory.<locals>.Operator object at 0x7f16afe6c370>
    └ <function _add_spec_args at 0x7f16b08adb80>
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/ops.py", line 282, in _add_spec_args
    converted_value = _type_convert_value(dtype, value)
                      │                   │      └ (<nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>, <nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>)
                      │                   └ <DALIDataType._FLOAT_VEC: 16>
                      └ <function _type_convert_value at 0x7f16b33694c0>
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/types.py", line 91, in _type_convert_value
    return _known_types[dtype][1](val)
           │            │         └ (<nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>, <nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>)
           │            └ <DALIDataType._FLOAT_VEC: 16>
           └ {<DALIDataType.INT8: 4>: ('int', <class 'int'>), <DALIDataType.INT16: 5>: ('int', <class 'int'>), <DALIDataType.INT32: 6>: ('...
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/types.py", line 29, in _to_list_instance
    return [func(v) for v in val]
            │                └ (<nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>, <nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>)
            └ <class 'float'>
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/types.py", line 29, in <listcomp>
    return [func(v) for v in val]
            │    │      └ <nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>
            │    └ <nvidia.dali.pipeline.DataNode object at 0x7f16ae6b79a0>
            └ <class 'float'>

TypeError: float() argument must be a string or a number, not 'DataNode'
Traceback (most recent call last):
  File "/home/xuyang/Projects/ModelZoo.deepmotion/engine/utils/dali_pipe.py", line 136, in <module>
    train_loader = DALIClassificationIterator(train_pipe,
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py", line 369, in __init__
    super(DALIClassificationIterator, self).__init__(pipelines, ["data", "label"],
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py", line 162, in __init__
    _DaliBaseIterator.__init__(self, pipelines, size, reader_name, auto_reset, fill_last_batch, last_batch_padded, last_batch_policy)
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/plugin/base_iterator.py", line 163, in __init__
    p.build()
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 479, in build
    self._prepare_graph(define_graph)
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 386, in _prepare_graph
    outputs = define_graph()
  File "/home/xuyang/Projects/ModelZoo.deepmotion/engine/utils/dali_pipe.py", line 114, in define_graph
    images = self.cmnp(images.gpu(), mirror=self.coin(), crop=(size, size))
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/ops.py", line 522, in __call__
    op_instances.append(_OperatorInstance(input_set, self, **kwargs))
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/ops.py", line 306, in __init__
    _add_spec_args(op._schema, self._spec, spec_args)
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/ops.py", line 282, in _add_spec_args
    converted_value = _type_convert_value(dtype, value)
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/types.py", line 91, in _type_convert_value
    return _known_types[dtype][1](val)
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/types.py", line 29, in _to_list_instance
    return [func(v) for v in val]
  File "/home/xuyang/miniconda3/envs/pytorch/lib/python3.8/site-packages/nvidia/dali/types.py", line 29, in <listcomp>
    return [func(v) for v in val]
TypeError: float() argument must be a string or a number, not 'DataNode'
```

**Comment by JanuszL** [comment]
Crop doesn't support per sample crop window size. For that, you need to use a slice that accepts (data, anchor, shape). You can provide a random shape and anchor or just use a NumPy array as constant, like slice(input, [0, 0], [10, 10]).

**Comment by PistonY** [comment]
Does `define_graph` do the per sample process, I need a batch have same shape, does it possible?

**Comment by JanuszL** [comment]
@PistonY,

`define_graph` is used only to define the flow between the operators. The code inside is not executed in the loop. The whole DALI processing happens in batches, which is a basic unit of the execution flow.

**Comment by PistonY** [comment]
> Crop doesn't support per sample crop window size. For that, you need to use a slice that accepts (data, anchor, shape). You can provide a random shape and anchor or just use a NumPy array as constant, like slice(input, [0, 0], [10, 10]).

Hi, @JanuszL 
Do you mean `nvidia.dali.ops.Slice`? I can not understand how to use it, does somewhere have a example?

**Comment by JanuszL** [comment]
Hi,
You can use the search box field in our documentation to find all examples with Slice. You can start from [this one](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html?highlight=slice) or [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/detection_pipeline.html?highlight=slice).a

**Comment by PistonY** [comment]
I think I know what you mean, I tried remove `CropMirrorNormalize` but still got an error. You mean I need to use `Slice` replace with `Resize` but that is not what I want, I need to resize image after decode them not straightly crop them.

**Comment by JanuszL** [comment]
@PistonY - I think I bit lost about what exactly you want to do. Can you describe step by step how your data processing flow should look like?

**Comment by PistonY** [comment]
Thanks for your patient @JanuszL 
This is a ImageNet classification processing pipe not COCO detection task.

1. I need to decode them.
2. I need to apply `RandomCrop` on them. The `scale` and `ratio` are fixed for all images.
3. I need to random select one size form a list like `size=[128, 192, 224]`, then resize one batch images to the size I selected.
4. I need to `random mirror` each image and `normalize` them.

The only different from normal ImageNet processing pipe is I need to get different image size of each batch.

**Comment by JanuszL** [comment]
In your case something like this should work:
```
import nvidia.dali.pipeline as pipeline
import nvidia.dali.types as types
import nvidia.dali.fn as fn
import numpy as np
import random


batch_size = 4
pipe = pipeline.Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
with pipe:
  images, labels = fn.readers.file(file_root="test",
                                   shard_id=0,
                                   num_shards=1,
                                   random_shuffle=False,
                                   name="Reader")
  images = fn.decoders.image_random_crop(images,
                                         device="mixed", output_type=types.RGB,
                                         random_aspect_ratio=[0.8, 1.25],
                                         random_area=[0.1, 1.0],
                                         num_attempts=100)

  def gen():
    val = random.choice([128, 196, 224])
    return [np.array([val ,val], dtype=np.float32) for _ in range(batch_size)]
  size = fn.external_source(gen)
  images = fn.resize(images,
                     size=size,
                     interp_type=types.INTERP_TRIANGULAR)
  images = fn.crop_mirror_normalize(images,
                                    dtype=types.FLOAT,
                                    output_layout="CHW",
                                    mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                    std=[0.229 * 255,0.224 * 255,0.225 * 255],
                                    mirror=fn.random.coin_flip(probability=0.5))
  pipe.set_outputs(images)
pipe.build()
for _ in range (10):
  out = pipe.run()[0]
  out = out.as_cpu().as_array()
  print(out.shape)
```
or if you want to have a different size per each sample try:
```
import nvidia.dali.pipeline as pipeline
import nvidia.dali.types as types
import nvidia.dali.fn as fn
import numpy as np
import random


batch_size = 4
pipe = pipeline.Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
with pipe:
  images, labels = fn.readers.file(file_root="test",
                                   shard_id=0,
                                   num_shards=1,
                                   random_shuffle=False,
                                   name="Reader")
  images = fn.decoders.image_random_crop(images,
                                         device="mixed", output_type=types.RGB,
                                         random_aspect_ratio=[0.8, 1.25],
                                         random_area=[0.1, 1.0],
                                         num_attempts=100)

  size = fn.random.uniform(values=[128, 196, 224], shape=[1])
  size = fn.cat(size, size)
  images = fn.resize(images,
                     size=size,
                     interp_type=types.INTERP_TRIANGULAR)
  images = fn.crop_mirror_normalize(images,
                                    dtype=types.FLOAT,
                                    output_layout="CHW",
                                    mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                    std=[0.229 * 255,0.224 * 255,0.225 * 255],
                                    mirror=fn.random.coin_flip(probability=0.5))
  pipe.set_outputs(images)
pipe.build()
for _ in range (10):
  out = pipe.run()[0]
  for o in out:
     print(o.as_cpu().shape())
```

**Comment by PistonY** [comment]
Thanks @JanuszL , the first one is what I want.
Here is the whole script I write.
```python
class DynamicTrainPipe:
    def __init__(self, root, batch_size, num_workers, rank, world_size, sizes, color_jit, dali_cpu=False):
        dali_device = 'cpu' if dali_cpu else 'gpu'
        decoder_device = 'cpu' if dali_cpu else 'mixed'

        device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
        host_memory_padding = 140544512 if decoder_device == 'mixed' else 0

        color_range = (max(0., 1 - color_jit), 1 + color_jit)
        pipe = Pipeline(batch_size=batch_size, num_threads=num_workers, device_id=rank)
        with pipe:
            images, labels = fn.file_reader(file_root=root,
                                            shard_id=rank,
                                            num_shards=world_size,
                                            name="Reader",
                                            random_shuffle=True,
                                            pad_last_batch=True)

            images = fn.image_decoder_random_crop(images,
                                                  device=decoder_device,
                                                  output_type=types.RGB,
                                                  device_memory_padding=device_memory_padding,
                                                  host_memory_padding=host_memory_padding,
                                                  random_aspect_ratio=[0.8, 1.25],
                                                  random_area=[0.1, 1.0],
                                                  num_attempts=100)

            size = fn.random.uniform(values=sizes, shape=[1])
            size = fn.permute_batch(size, indices=[0] * batch_size)
            size = fn.cat(size, size)
            images = fn.resize(images, device=dali_device, size=size, interp_type=types.INTERP_TRIANGULAR)
            images = fn.color_twist(images,
                                    device=dali_device,
                                    brightness=fn.random.uniform(range=color_range, shape=[1]),
                                    contrast=fn.random.uniform(range=color_range, shape=[1]),
                                    saturation=fn.random.uniform(range=color_range, shape=[1]))
            images = fn.crop_mirror_normalize(images,
                                              device=dali_device,
                                              dtype=types.FLOAT,
                                              output_layout=types.NCHW,
                                              mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                                              std=[0.229 * 255, 0.224 * 255, 0.225 * 255],
                                              mirror=fn.random.coin_flip(probability=0.5))
            pipe.set_outputs(images, labels.gpu())
        pipe.build()
        self.loader = DALIClassificationIterator(pipe,
                                                 reader_name="Reader",
                                                 dynamic_shape=True,
                                                 auto_reset=True,
                                                 last_batch_policy=LastBatchPolicy.DROP)

    def __next__(self):
        meta_data = next(self.loader)
        data = meta_data[0]["data"]
        label = meta_data[0]["label"].squeeze(-1).long()
        return data, label

    def __iter__(self):
        return self
```
I like this Functional API, I could package the code to `Pytorch Style`.
Though I still don't know why only change length of size to `fn.resize` can control batch size or sample size.It's truly cool.

**Comment by JanuszL** [comment]
> Though I still don't know why only change length of size to fn.resize can control batch size or sample size.It's truly cool.

Do you mean:
```
 size = fn.random.uniform(values=sizes, shape=[1])
 size = fn.permute_batch(size, indices=[0] * batch_size)
 size = fn.cat(size, size)
```
these lines?
In this case, `permute_batch` extracts the value from the first sample and duplicates it through the whole batch.

**Comment by PistonY** [comment]
Thanks for help @JanuszL .
