### ISSUE TITLE
TypeError: current_stream() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by gbyy422990** [NVIDIA/DALI#2602]
Hi, i am trying to use dali(0.28.0) wth cuda10 and pytorch1.3, but i got error like below:
```
Traceback (most recent call last):
  File "train_cs.py", line 157, in <module>
    train_loader = DALIClassificationIterator(pipe, size=-1)
  File "/home/work/anaconda/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 375, in __init__
    last_batch_policy = last_batch_policy)
  File "/home/work/anaconda/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 170, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/home/work/anaconda/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 232, in __next__
    stream = torch.cuda.current_stream(device=pyt_tensors[category].device)
TypeError: current_stream() got an unexpected keyword argument 'device'
```

**Comment by JanuszL** [comment]
Hi,
I tested https://download.pytorch.org/whl/cu100/torch-1.3.0%2Bcu100-cp36-cp36m-linux_x86_64.whl with this toy script:
```
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec

class TrainPipe(Pipeline):
    def __init__(self, root, batch_size, num_workers, rank, world_size, size, color_jit, dali_cpu=False):
        super(TrainPipe, self).__init__(batch_size, num_workers, rank)
        self.input = ops.FileReader(file_root=root,
                                    shard_id=rank,
                                    num_shards=world_size,
                                    random_shuffle=False,
                                    pad_last_batch=True)

        dali_device = 'cpu' if dali_cpu else 'gpu'
        decoder_device = 'cpu' if dali_cpu else 'mixed'
        device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
        host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
        self.decode = ops.ImageDecoderRandomCrop(device=decoder_device, output_type=types.RGB,
                                                 device_memory_padding=device_memory_padding,
                                                 host_memory_padding=host_memory_padding,
                                                 num_attempts=100)
        self.resize = ops.Resize(device=dali_device,
                                 resize_x=size,
                                 resize_y=size,
                                 interp_type=types.INTERP_TRIANGULAR)

        self.color_jitter = ops.ColorTwist(device=dali_device)

        self.cmnp = ops.CropMirrorNormalize(device="gpu", dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(size, size),
                                            mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                                            std=[0.229 * 255, 0.224 * 255, 0.225 * 255])

        self.coin = ops.CoinFlip(probability=0.5)
        self.uniform = ops.Uniform(range=(max(0., 1 - color_jit), 1 + color_jit))

    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        images = self.resize(images)
        images = self.color_jitter(images,
                                   brightness=self.uniform(),
                                   contrast=self.uniform(),
                                   saturation=self.uniform())
        images = self.cmnp(images.gpu(), mirror=self.coin())
        return [images, self.labels.gpu()]


class ValPipe(Pipeline):
    def __init__(self, root, batch_size, num_workers, rank, crop):
        super(ValPipe, self).__init__(batch_size, num_workers, rank)
        self.input = ops.FileReader(file_root=root,
                                    shard_id=rank,
                                    num_shards=1,
                                    random_shuffle=False,
                                    pad_last_batch=True)
        self.decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)
        self.resize = ops.Resize(device="gpu",
                                 resize_shorter=int(crop / 0.875),
                                 interp_type=types.INTERP_TRIANGULAR)
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(crop, crop),
                                            mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                                            std=[0.229 * 255, 0.224 * 255, 0.225 * 255])

    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        images = self.resize(images)
        output = self.cmnp(images)
        return [output, self.labels.gpu()]

if __name__ == '__main__':
    from nvidia.dali.plugin.pytorch import DALIClassificationIterator, \
        LastBatchPolicy

    train_pipe = TrainPipe('/opt/dali_extra/db/single/jpeg', 10, 4, 0, 1, 224, 0.4)
    train_loader = DALIClassificationIterator(train_pipe, reader_name="Reader", auto_reset=True,
                                              last_batch_policy=LastBatchPolicy.DROP)

    for meta_data in train_loader:
        print(meta_data[0]["data"].shape)
        print(meta_data[0]["label"].squeeze(-1).long())
    print("First Done!")
    # train_loader.reset()
    for meta_data in train_loader:
        print(meta_data[0]["data"].shape)
        print(meta_data[0]["label"].squeeze(-1).long())
    print("Second Done!")
```
It works fine. Could you provide the exact torch binary you have used? Can you try to run and check the result?
I have also tested 1.1 and 1.2 with the same successful result. However, 1.0 doesn't work as current_stream has a different signature in that PyTorch version.
Please update your PyTorch to a more recent version if possible or rollback DALI to some older version that doesn't need that PyTorch function (0.21).

**Comment by gbyy422990** [comment]
@JanuszL I used a wrong Pytorch version, I have tested 1.1, 1.2 and 1.3 without any problem. I will close this issue.
