### ISSUE TITLE
can not install dali 0.29

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2642]
Hi:

Thanks for your help. I can not install dali 0.29 by `pip install --default-timeout=100 --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda100`

Here is the error log.

~~~
(ori_dali) admin@zhiheng-tf-dev-748bddd6bb-cvsc2:~/dataset_dev/lmdb-dataset$ pip install --default-timeout=100 --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda100
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com, https://developer.download.nvidia.com/compute/redist
Collecting nvidia-dali-cuda100
  Downloading https://developer.download.nvidia.cn/compute/redist/nvidia-dali-cuda100/nvidia_dali_cuda100-0.29.0-1852439-py3-none-manylinux2014_x86_64.whl (386.4 MB)
     |▏                               | 1.4 MB 1.6 kB/s eta 2 days, 19:36:16
ERROR: Exception:
Traceback (most recent call last):
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 339, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 172, in get_dependencies
    for r in candidate.iter_dependencies(with_requires)
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 171, in <listcomp>
    r
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 257, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 319, in _prepare_distribution
    self._ireq, parallel_builds=True,
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 89, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/site-packages/pip/_internal/distributions/wheel.py", line 30, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/admin/miniconda3/envs/ori_dali/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
~~~

Besides, I will also lost connection during installation even with --default-timeout=100. Do you have some advice to improve the downloading speed? Thanks!!

**Comment by JanuszL** [comment]
Hi,
I guess there is a problem with your network provider (proxy or firewall). You may try to download https://developer.download.nvidia.cn/compute/redist/nvidia-dali-cuda100/nvidia_dali_cuda100-0.29.0-1852439-py3-none-manylinux2014_x86_64.whl directly to see if that helps.

**Comment by JanuszL** [comment]
If it still doesn't work please reopen.
