### ISSUE TITLE
Error Installing DALI Tensorflow plugin

### ISSUE THREAD

**Issue by LucasSloan** [NVIDIA/DALI#2678]
OS: Ubuntu 20.04
Cuda Version: release 11.1, V11.1.105
Tensorflow Version: 2.4.1

I was able to run the pip command to install DALI just fine, but when I ran the command to install the tensorflow plugin I got the following error:

```
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9yswhsu2/nvidia-dali-tf-plugin-cuda110/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9yswhsu2/nvidia-dali-tf-plugin-cuda110/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nd28juzi
       cwd: /tmp/pip-install-9yswhsu2/nvidia-dali-tf-plugin-cuda110/
  Complete output (56 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/nvidia
  creating build/lib.linux-x86_64-3.8/nvidia/dali_tf_plugin
  copying nvidia/dali_tf_plugin/dali_tf_plugin.py -> build/lib.linux-x86_64-3.8/nvidia/dali_tf_plugin
  copying nvidia/dali_tf_plugin/__init__.py -> build/lib.linux-x86_64-3.8/nvidia/dali_tf_plugin
  running egg_info
  writing nvidia_dali_tf_plugin_cuda110.egg-info/PKG-INFO
  writing dependency_links to nvidia_dali_tf_plugin_cuda110.egg-info/dependency_links.txt
  writing requirements to nvidia_dali_tf_plugin_cuda110.egg-info/requires.txt
  writing top-level names to nvidia_dali_tf_plugin_cuda110.egg-info/top_level.txt
  reading manifest file 'nvidia_dali_tf_plugin_cuda110.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'nvidia_dali_tf_plugin_cuda110.egg-info/SOURCES.txt'
  copying nvidia/dali_tf_plugin/Acknowledgements.txt -> build/lib.linux-x86_64-3.8/nvidia/dali_tf_plugin
  copying nvidia/dali_tf_plugin/COPYRIGHT -> build/lib.linux-x86_64-3.8/nvidia/dali_tf_plugin
  copying nvidia/dali_tf_plugin/LICENSE -> build/lib.linux-x86_64-3.8/nvidia/dali_tf_plugin
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-9yswhsu2/nvidia-dali-tf-plugin-cuda110/setup.py", line 37, in <module>
      setup(name='nvidia-dali-tf-plugin-cuda110',
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-9yswhsu2/nvidia-dali-tf-plugin-cuda110/setup.py", line 24, in run
      helper = InstallerHelper(plugin_dest_dir = os.path.join(self.build_lib, 'nvidia', 'dali_tf_plugin'))
    File "/tmp/pip-install-9yswhsu2/nvidia-dali-tf-plugin-cuda110/dali_tf_plugin_install_tool.py", line 32, in __init__
      self.tf_compiler = get_tf_compiler_version()
    File "/tmp/pip-install-9yswhsu2/nvidia-dali-tf-plugin-cuda110/dali_tf_plugin_utils.py", line 52, in get_tf_compiler_version
      s = str(subprocess.check_output(cmd, shell=True))
    File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 512, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command 'strings -a /usr/lib/python3/dist-packages/tensorflow/libtensorflow_framework.so.2 | grep "GCC: ("' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for nvidia-dali-tf-plugin-cuda110
```

I loaded up /usr/lib/python3/dist-packages/tensorflow/libtensorflow_framework.so.2, and it doesn't have any instances of "GCC: (", and in fact, it seems to be a binary, not a text file.  Any ideas what I should do?

**Comment by JanuszL** [comment]
Hi,
> and in fact, it seems to be a binary, not a text file

We are not treating it as a text file. we first extract all strings and then grep it to check what compiler version was used `strings -a /usr/lib/python3/dist-packages/tensorflow/libtensorflow_framework.so.2 | grep "GCC: ("`.
I just tried to reproduce the problem but bellow works just fine:
```
docker run --rm -ti ubuntu:20.04
apt update && apt install -y curl wget python3 python3-distutils libxml2 curl perl gcc g++ &&
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py &&\
curl -LO https://developer.download.nvidia.com/compute/cuda/11.2.1/local_installers/cuda_11.2.1_460.32.03_linux.run && \
    chmod +x cuda_*.run && \
    ./cuda_*.run --silent --no-opengl-libs --toolkit && \
pip install tensorflow-gpu==2.4.1 && \
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda110 && \
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-tf-plugin-cuda110
```

**Comment by LucasSloan** [comment]
I was using tensorflow from [Lambda Stack](https://lambdalabs.com/lambda-stack-deep-learning-software), I fixed the issue by installing from tensorflow directly.
