### ISSUE TITLE
DALI parse much more samples than original mxrecord

### ISSUE THREAD

**Issue by twmht** [NVIDIA/DALI#2806]
Hi,

I have a mxnet record file (https://www.dropbox.com/s/wpx6tqjf0y5mf6r/faces_ms1m-refine-v2_112x112.zip?dl=0). there are 5822653 images in the record file.

there is how i check the number of images

```python
def load_mx_rec(rec_path):

    imgrec = mx.recordio.MXIndexedRecordIO(os.path.join(rec_path, 'train.idx'), os.path.join(rec_path, 'train.rec'), 'r')
    img_info = imgrec.read_idx(0)
    header,_ = mx.recordio.unpack(img_info)
    max_idx = int(header.label[0])
    if True:
        #  for idx in tqdm(range(1,max_idx)):
        for idx in range(1,max_idx):
            img_info = imgrec.read_idx(idx)
            header, img = mx.recordio.unpack_img(img_info)
            label = int(header.label)
            if img.shape != (112,112,3):
                print (img.shape)
                assert(0)
            print (f'idx = {idx}, img_shape = {img.shape}')

```

However, when using Dali, it has  5908396 images when calling `dali_iter.size`, Here is how i use dali

```python
class CommonPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(CommonPipeline, self).__init__(batch_size, num_threads, device_id)

        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)

    def base_define_graph(self, inputs, labels):
        images = self.decode(inputs)
        return (images, labels)


db_folder = '/home/acer/nfs-share/faces_emore/'
class MXNetReaderPipeline(CommonPipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus):
        super(MXNetReaderPipeline, self).__init__(batch_size, num_threads, device_id)
        self.input = ops.MXNetReader(path = [db_folder+"train.rec"], index_path=[db_folder + 'train.idx'], random_shuffle = True, shard_id = device_id, num_shards = num_gpus)

    def define_graph(self):
        images, labels = self.input(name="Reader")
        return self.base_define_graph(images, labels)

pipes = [MXNetReaderPipeline(1, 2, 0, 1)]
pipes[0].build()
dali_iter = DALIGenericIterator(pipes, ['data', 'label'], pipes[0].epoch_size("Reader"))
print (dali_iter.size)
```

therefore it threw the decoding exceptions when training.

```
Traceback (most recent call last):
  File "../dali.py", line 134, in <module>
    for i, data in enumerate(dali_iter):
  File "/home/acer/.pyenv/versions/pytorch/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 181, in __next__
    outputs = self._get_outputs()
  File "/home/acer/.pyenv/versions/pytorch/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 250, in _get_outputs
    outputs.append(p.share_outputs())
  File "/home/acer/.pyenv/versions/pytorch/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 693, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator ImageDecoder encountered:
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:536] [/opt/dali/dali/image/jpeg.cc:132] Assert on "jpeg::GetImageInfo(encoded_buffer, length, &width, &height, &components) == true" failed
```

my dali version is 0.31.0

**Comment by twmht** [comment]
after removing the first header and rewrite rec file. not sure which one is the root cause. but the error is gone.
