### ISSUE TITLE
Schema for operator 'decoders__Image' not registere

### ISSUE THREAD

**Issue by ThiagoMateo** [NVIDIA/DALI#2933]
hello, i tried to [create](https://github.com/ThiagoMateo/dali_issue/blob/main/serialize_dali_model.py) dali preprocess [model](https://github.com/ThiagoMateo/dali_issue/tree/main/models/preprocess) for triton 20.12.
i check it [locally](https://github.com/ThiagoMateo/dali_issue/blob/main/test_locally.py), it is ok.
but when i deploy using triton. there is an error bellow:
```
Traceback (most recent call last):
  File "client.py", line 47, in <module>
    results = triton_client.infer(model_name=model_name,
  File "/home/tienduchoang/miniconda3/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 1061, in infer
    raise_error_grpc(rpc_error)
  File "/home/tienduchoang/miniconda3/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNKNOWN] runtime error: Critical error when building pipeline:
Error when adding operator: decoders__Image" encountered:
[/opt/dali/dali/pipeline/operator/op_schema.cc:43] Assert on "it != schema_map.end()" failed: Schema for operator 'decoders__Image' not registered
Stacktrace (16 entries):
[frame 0]: /opt/tritonserver/backends/dali/dali/libdali.so(+0xbd68e) [0x7fdfa217068e]
[frame 1]: /opt/tritonserver/backends/dali/dali/libdali.so(dali::SchemaRegistry::GetSchema(std::string const&)+0x134) [0x7fdfa22173d4]
[frame 2]: /opt/tritonserver/backends/dali/dali/libdali.so(+0x130766) [0x7fdfa21e3766]
[frame 3]: /opt/tritonserver/backends/dali/dali/libdali.so(dali::OpGraph::AddOp(dali::OpSpec const&, std::string const&)+0x25) [0x7fdfa21e4d55]
[frame 4]: /opt/tritonserver/backends/dali/dali/libdali.so(dali::Pipeline::Build(std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > >)+0x17a) [0x7fdfa223dd5a]
[frame 5]: /opt/tritonserver/backends/dali/dali/libdali.so(daliCreatePipeline+0x1e6) [0x7fdfa2281ad6]
[frame 6]: /opt/tritonserver/backends/dali/libtriton_dali.so(+0x2febc) [0x7fe100090ebc]
[frame 7]: /opt/tritonserver/backends/dali/libtriton_dali.so(+0x2eb66) [0x7fe10008fb66]
[frame 8]: /opt/tritonserver/backends/dali/libtriton_dali.so(+0x2ece2) [0x7fe10008fce2]
[frame 9]: /opt/tritonserver/backends/dali/libtriton_dali.so(+0x104c9) [0x7fe1000714c9]
[frame 10]: /opt/tritonserver/backends/dali/libtriton_dali.so(TRITONBACKEND_ModelInstanceExecute+0x2ee) [0x7fe10007195e]
[frame 11]: /opt/tritonserver/bin/../lib/libtritonserver.so(+0x2da9b7) [0x7fe15072b9b7]
[frame 12]: /opt/tritonserver/bin/../lib/libtritonserver.so(+0xf1240) [0x7fe150542240]
[frame 13]: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6d84) [0x7fe14ff8bd84]
[frame 14]: /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7fe150426609]
[frame 15]: /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fe14fc79293]

Current pipeline object is no longer valid.
```

can you guy help me to solve this problem?

**Comment by JanuszL** [comment]
Hi,
You need to either update DALI to the latest version in your TRITON 20.12 image or use the DALI API that corresponds to the version you have. The documentation for older DALI's version can be found [here](https://docs.nvidia.com/deeplearning/dali/archives/index.html).
