### ISSUE TITLE
NVJPEG error "6" : NVJPEG_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#3160]
```
Epoch: [5][1900/5892]	Time 0.166 (0.172)	Data 0.000 (0.000)	Loss 3.6258 (3.6594)	Prec@1 36.133 (36.790)	Prec@5 63.672 (62.476)	Learning rate 0.40000
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:925] NVJPEG error "6" : NVJPEG_STATUS_EXECUTION_FAILED n01990800/n01992773_7551.JPEG
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:925] NVJPEG error "6" : NVJPEG_STATUS_EXECUTION_FAILED n04591157/n04591157_6031.JPEG
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:925] NVJPEG error "6" : NVJPEG_STATUS_EXECUTION_FAILED n03599486/n09265620_35729.JPEG
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:925] NVJPEG error "6" : NVJPEG_STATUS_EXECUTION_FAILED n02454379/n02454379_2058.JPEG
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:925] NVJPEG error "6" : NVJPEG_STATUS_EXECUTION_FAILED n02391049/n02391234_973.JPEG
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:925] NVJPEG error "6" : NVJPEG_STATUS_EXECUTION_FAILED n02093859/n10345015_7328.JPEG
Traceback (most recent call last):
  File "train_imagenet.py", line 425, in <module>
    main()
  File "train_imagenet.py", line 390, in main
    train_func(args, model, train_loader, optimizer, lr_scheduler, epoch, model_ema)
  File "train_val_utils.py", line 312, in train
    loss.backward()
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/tiger/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: an illegal memory access was encountered (launch_kernel at /pytorch/aten/src/ATen/native/cuda/CUDALoops.cuh:217)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7effe0be9536 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xd2fe14 (0x7effe1d74e14 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #2: void at::native::gpu_kernel_impl<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::add_kernel_cuda, 4u>, float (float, float), float> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::add_kernel_cuda, 4u>, float (float, float), float> const&) + 0x19e1 (0x7effe2d3fc01 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #3: void at::native::gpu_kernel<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::add_kernel_cuda, 4u>, float (float, float), float> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::add_kernel_cuda, 4u>, float (float, float), float> const&) + 0x12b (0x7effe2d40d3b in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #4: void at::native::gpu_kernel_with_scalars<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::add_kernel_cuda, 4u>, float (float, float), float> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::add_kernel_cuda, 4u>, float (float, float), float> const&) + 0xeb (0x7effe2d40feb in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x1b6bcd9 (0x7effe2bb0cd9 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #6: at::native::add_kernel_cuda(at::TensorIterator&, c10::Scalar) + 0x1a (0x7effe2bb1a3a in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xb6bb35 (0x7f001e03ab35 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: at::native::add_out(at::Tensor&, at::Tensor const&, at::Tensor const&, c10::Scalar) + 0x7b (0x7f001e02c20b in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0xf74d0d (0x7effe1fb9d0d in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #10: <unknown function> + 0x2be3b2a (0x7f00200b2b2a in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #11: torch::autograd::AccumulateGrad::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x524 (0x7f002025d2c4 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x2d89c05 (0x7f0020258c05 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x417 (0x7f0020254c27 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7f0020256ce2 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::Engine::thread_init(int) + 0x39 (0x7f002024f359 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7f002c98e998 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #17: <unknown function> + 0xc819d (0x7f002d86719d in /opt/tiger/conda/lib/libstdc++.so.6)
frame #18: <unknown function> + 0x7fa3 (0x7f002f183fa3 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #19: clone + 0x3f (0x7f002f0b44cf in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7effe0be9536 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x7ae (0x7effe0e2cfbe in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7effe0bd9abd in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5236b2 (0x7f002c9a26b2 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x523756 (0x7f002c9a2756 in /opt/tiger/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x1a184f (0x559f2fb1884f in /opt/tiger/conda/bin/python3)
frame #6: <unknown function> + 0x10db08 (0x559f2fa84b08 in /opt/tiger/conda/bin/python3)
frame #7: <unknown function> + 0x1a1831 (0x559f2fb18831 in /opt/tiger/conda/bin/python3)
frame #8: <unknown function> + 0xfd1a8 (0x559f2fa741a8 in /opt/tiger/conda/bin/python3)
frame #9: <unknown function> + 0x10e3c7 (0x559f2fa853c7 in /opt/tiger/conda/bin/python3)
frame #10: <unknown function> + 0x10e3dd (0x559f2fa853dd in /opt/tiger/conda/bin/python3)
frame #11: <unknown function> + 0x10e3dd (0x559f2fa853dd in /opt/tiger/conda/bin/python3)
frame #12: PyDict_SetItem + 0x502 (0x559f2fad9ed2 in /opt/tiger/conda/bin/python3)
frame #13: PyDict_SetItemString + 0x4f (0x559f2fada70f in /opt/tiger/conda/bin/python3)
frame #14: PyImport_Cleanup + 0x9e (0x559f2fb1e9ce in /opt/tiger/conda/bin/python3)
frame #15: Py_FinalizeEx + 0x67 (0x559f2fb9a087 in /opt/tiger/conda/bin/python3)
frame #16: <unknown function> + 0x235f93 (0x559f2fbacf93 in /opt/tiger/conda/bin/python3)
frame #17: _Py_UnixMain + 0x3c (0x559f2fbad2bc in /opt/tiger/conda/bin/python3)
frame #18: __libc_start_main + 0xeb (0x7f002efdf09b in /lib/x86_64-linux-gnu/libc.so.6)
frame #19: <unknown function> + 0x1db062 (0x559f2fb52062 in /opt/tiger/conda/bin/python3)
```

**Comment by pawopawo** [comment]
```python
class HybridTrainPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data_dir, crop, dali_cpu=False, args=None):
        super(HybridTrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        self.input = ops.FileReader(file_root=data_dir, shard_id=dist.get_rank(), num_shards=args.world_size, random_shuffle=True)
        #let user decide which pipeline works him bets for RN version he runs
        dali_device = 'cpu' if dali_cpu else 'gpu'
        decoder_device = 'cpu' if dali_cpu else 'mixed'
        # This padding sets the size of the internal nvJPEG buffers to be able to handle all images from full-sized ImageNet
        # without additional reallocations
        device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
        host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
        self.decode = ops.ImageDecoderRandomCrop(device=decoder_device, output_type=types.RGB,
                                                 device_memory_padding=device_memory_padding,
                                                 host_memory_padding=host_memory_padding,
                                                 random_aspect_ratio=[0.8, 1.25],
                                                 random_area=[0.1, 1.0],
                                                 num_attempts=100)
        self.res = ops.Resize(device=dali_device, resize_x=crop, resize_y=crop, interp_type=types.INTERP_TRIANGULAR)
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(crop, crop),
                                            image_type=types.RGB,
                                            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                            std=[0.229 * 255,0.224 * 255,0.225 * 255])
        self.coin = ops.CoinFlip(probability=0.5)
        print('DALI "{0}" variant'.format(dali_device))

    def define_graph(self):
        rng = self.coin()
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        images = self.res(images)
        output = self.cmnp(images.gpu(), mirror=rng)
        return [output, self.labels]
class HybridValPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data_dir, crop, size, args=None):
        super(HybridValPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        self.input = ops.FileReader(file_root=data_dir, shard_id=dist.get_rank(), num_shards=args.world_size, random_shuffle=False)
        self.decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)
        self.res = ops.Resize(device="gpu", resize_shorter=size, interp_type=types.INTERP_TRIANGULAR)
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(crop, crop),
                                            image_type=types.RGB,
                                            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                            std=[0.229 * 255,0.224 * 255,0.225 * 255])

    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        images = self.res(images)
        output = self.cmnp(images)
        return [output, self.labels]
def getDatasetDali(args, data_dir):
    crop_size = 224
    val_size = 256
    train_dir = os.path.join(data_dir, "ILSVRC2012_img_train")
    val_dir = os.path.join(data_dir, "ILSVRC2012_img_val")
    pipe = HybridTrainPipe(batch_size=args.batch_size, num_threads=args.workers, device_id=args.local_rank,
                           data_dir=train_dir, crop=crop_size, dali_cpu=False, args=args)
    pipe.build()
    train_loader = DALIClassificationIterator(pipe, size=int(pipe.epoch_size("Reader") / args.world_size))
    pipe = HybridValPipe(batch_size=args.test_batch_size, num_threads=args.workers, device_id=args.local_rank,
                         data_dir=val_dir,
                         crop=crop_size, size=val_size, args=args)
    pipe.build()
    val_loader = DALIClassificationIterator(pipe, size=int(pipe.epoch_size("Reader") / args.world_size))
    return train_loader, val_loader
```

environment:
`nvidia-dali-cuda100      1.3.0
`

**Comment by mzient** [comment]
@pawopawo Thanks for reporting the problem. 
To help help you with resolving the issue, we need some information:
1. Is the error repeatable (does it occur in the same iteration)?
2. Does it still occur with host decoder (`device="cpu"`)? The errors in CUDA are reported asynchronously, so it's possible that what you're seeing is not an error in NVJPEG.
3. Can you try ImageDecoder followed by RandomResizedCrop instead of ImageDecoderRandomCrop followed by Resize?

**Comment by pawopawo** [comment]
1. Yes, it occur in the same iteration, but in different epoch
2. Yes. When set --dali_cpu=true, it still occurs.
3. Thanks, I will have a try

**Comment by mzient** [comment]
@pawopawo Thanks for the information.
With dali_cpu you can't get NVJPEG errors - it must be something else. Do you happen to have the error message generated with `dali_cpu==True`?

**Comment by pawopawo** [comment]
No matter if dali_cpu is True or False, there will be the above error.

**Comment by mzient** [comment]
> Yes. When set --dali_cpu=true, it still occurs.
Perhaps the code above is different from what you're running, but here DALI device doesn't depend on a command line argument - dali_cpu is hardcoded in the call:
```Python
    pipe = HybridTrainPipe(batch_size=args.batch_size, num_threads=args.workers, device_id=args.local_rank,
                           data_dir=train_dir, crop=crop_size, dali_cpu=False, args=args)
```
Shouldn't it be:
```Python
    pipe = HybridTrainPipe(batch_size=args.batch_size, num_threads=args.workers, device_id=args.local_rank,
                           data_dir=train_dir, crop=crop_size, dali_cpu=args.dali_cpu, args=args)
```
Even with that the validation pipeline still uses NVJPEG - could you try to use host decoder, too?
```
class HybridValPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data_dir, crop, size, args=None):
        super(HybridValPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        self.input = ops.FileReader(file_root=data_dir, shard_id=dist.get_rank(), num_shards=args.world_size, random_shuffle=False)
        self.decode = ops.ImageDecoder(device="cpu", output_type=types.RGB)   # <---------------------------- change to CPU here
        self.res = ops.Resize(device="gpu", resize_shorter=size, interp_type=types.INTERP_TRIANGULAR)
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(crop, crop),
                                            image_type=types.RGB,
                                            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                            std=[0.229 * 255,0.224 * 255,0.225 * 255])

    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs).gpu() # <------------------------ move to gpu
        images = self.res(images)
        output = self.cmnp(images)
        return [output, self.labels]
```

**Comment by pawopawo** [comment]
Thanks
