### ISSUE TITLE
RuntimeError: CUDA runtime API error cudaErrorInitializationError (3):

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#3163]
```
Traceback (most recent call last):
  File "train_imagenet.py", line 465, in <module>
    main()
  File "train_imagenet.py", line 341, in main
    train_loader, val_loader = train_val_utils.getDatasetDali_v2(args, args.data)
  File "/imagenet_pytorch_on_hdfs/train_val_utils.py", line 241, in getDatasetDali_v2
    pipe.build()
  File "/opt/tiger/conda/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 658, in build
    self._init_pipeline_backend()
  File "/opt/tiger/conda/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 573, in _init_pipeline_backend
    self._default_cuda_stream_priority)
RuntimeError: CUDA runtime API error cudaErrorInitializationError (3):
initialization error
```

**Comment by pawopawo** [comment]
```

@pipeline_def
def create_dali_pipeline(data_dir, crop, size, shard_id, num_shards, dali_cpu=False, is_training=True):
    images, labels = fn.readers.file(file_root=data_dir,
                                     shard_id=shard_id,
                                     num_shards=num_shards,
                                     random_shuffle=is_training,
                                     pad_last_batch=True,
                                     name="Reader",
                                     seed=100)
    dali_device = 'cpu' if dali_cpu else 'gpu'
    decoder_device = 'cpu' if dali_cpu else 'mixed'
    # ask nvJPEG to preallocate memory for the biggest sample in ImageNet for CPU and GPU to avoid reallocations in runtime
    device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
    host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
    # ask HW NVJPEG to allocate memory ahead for the biggest image in the data set to avoid reallocations in runtime
    preallocate_width_hint = 5980 if decoder_device == 'mixed' else 0
    preallocate_height_hint = 6430 if decoder_device == 'mixed' else 0
    if is_training:
        images = fn.decoders.image_random_crop(images,
                                               device=decoder_device, output_type=types.RGB,
                                               device_memory_padding=device_memory_padding,
                                               host_memory_padding=host_memory_padding,
                                               preallocate_width_hint=preallocate_width_hint,
                                               preallocate_height_hint=preallocate_height_hint,
                                               random_aspect_ratio=[0.8, 1.25],
                                               random_area=[0.1, 1.0],
                                               num_attempts=100,
                                               seed=100)
        images = fn.resize(images,
                           device=dali_device,
                           resize_x=crop,
                           resize_y=crop,
                           interp_type=types.INTERP_TRIANGULAR,
                           seed=100)
        mirror = fn.random.coin_flip(probability=0.5, seed=100)
    else:
        images = fn.decoders.image(images,
                                   device=decoder_device,
                                   output_type=types.RGB)
        images = fn.resize(images,
                           device=dali_device,
                           size=size,
                           mode="not_smaller",
                           interp_type=types.INTERP_TRIANGULAR)
        mirror = False

    images = fn.crop_mirror_normalize(images.gpu(),
                                      dtype=types.FLOAT,
                                      output_layout="CHW",
                                      crop=(crop, crop),
                                      mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                      std=[0.229 * 255,0.224 * 255,0.225 * 255],
                                      mirror=mirror)
    labels = labels.gpu()
    return images, labels


def getDatasetDali_v2(args, data_dir):
    print("train image size:", args.image_size)
    crop_size = args.image_size
    val_size = int(math.ceil(args.image_size / 0.875))

    if data_dir =='/':
        train_dir = os.path.join(data_dir, "ILSVRC2012_img_train")
        val_dir = os.path.join(data_dir, "ILSVRC2012_img_val")
    else:
        train_dir = os.path.join(data_dir, "imagenet1k_ssld_v2")
        val_dir = os.path.join('/', "ILSVRC2012_img_val")


    pipe = create_dali_pipeline(batch_size=args.batch_size,
                                num_threads=args.workers,
                                device_id=args.local_rank,
                                seed=12 + args.local_rank,
                                data_dir=train_dir,
                                crop=crop_size,
                                size=val_size,
                                dali_cpu=args.dali_cpu,
                                shard_id=dist.get_rank(),
                                num_shards=args.world_size,
                                is_training=True)
    pipe.build()
    train_loader = DALIClassificationIterator(pipe, reader_name="Reader", last_batch_policy=LastBatchPolicy.PARTIAL)


    # args.image_size = 384###
    print("test image size:", args.image_size)
    crop_size = args.image_size
    val_size = int(math.ceil(args.image_size / 0.875))

    pipe = create_dali_pipeline(batch_size=args.batch_size,
                                num_threads=args.workers,
                                device_id=args.local_rank,
                                seed=12 + args.local_rank,
                                data_dir=val_dir,
                                crop=crop_size,
                                size=val_size,
                                dali_cpu=args.dali_cpu,
                                shard_id=dist.get_rank(),
                                num_shards=args.world_size,
                                is_training=False)
    pipe.build()
    val_loader = DALIClassificationIterator(pipe, reader_name="Reader", last_batch_policy=LastBatchPolicy.PARTIAL)
    return train_loader, val_loader
```

**Comment by mzient** [comment]
@pawopawo Please provide more details. What DL framework are you using? Which driver version do you have and which CUDA version is expected by the framework? CUDA initialization error doesn't point to an issue in DALI but rather with the configuration of the system.

**Comment by pawopawo** [comment]
```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.19.117.bsk.6-amd64-x86_64-with-debian-10.3
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 418.116.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] torch                     1.8.0                    pypi_0    pypi
[conda] torchvision               0.9.0                    pypi_0    pypi
```

**Comment by mzient** [comment]
> Nvidia driver version: 418.116.00
CUDA 10.2 requires at least 440

**Comment by mzient** [comment]
Here's a table of toolkit/driver compatibility from CUDA documentation. Running such an old driver may be the cause of all of your issues.

CUDA Toolkit | Linux x86_64 Required Driver Version
-- | --
CUDA 11.3 | >= 450.80.02
CUDA 11.2 | >= 450.80.02
CUDA 11.1 (11.1.0) | >= 450.80.02
CUDA 11.0 (11.0.3) | >= 450.36.06
CUDA 10.2 (10.2.89) | >= 440.33
CUDA 10.1 (10.1.105) | >= 418.39
CUDA 10.0 (10.0.130) | >= 410.48
CUDA 9.2 (9.2.88) | >= 396.26
CUDA 9.1 (9.1.85) | >= 390.46
CUDA 9.0 (9.0.76) | >= 384.81
CUDA 8.0 (8.0.61 GA2) | >= 375.26
CUDA 8.0 (8.0.44) | >= 367.48
CUDA 7.5 (7.5.16) | >= 352.31
CUDA 7.0 (7.0.28) | >= 346.46
