### ISSUE TITLE
AttributeError when use parallel in external_source.

### ISSUE THREAD

**Issue by Doom9234** [NVIDIA/DALI#3187]
Dear author, When I use `parallel` in `external_source`,   I got an lambda related `AttributeError`. I dont see any lambda function in my script. Can you give me some suggestions about how to properly use `parallel` in external source?

here is the test loader:

```
import torch
from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy
from nvidia.dali.pipeline import pipeline_def
import nvidia.dali.types as types
import nvidia.dali.fn as fn

import json
import numpy as np
import random
from functools import partial


class ExternalInputIterator(object):
    def __init__(self, shard_id, shard_num, seed, image_list, text_list):
        self.file_list = list(zip(image_list, text_list))
        self.data_set_len = len(self.file_list)
        self.shard_id = shard_id
        self.shard_num = shard_num

    def __iter__(self):
        self.file_list_shard = self.file_list[self.data_set_len * self.shard_id // self.shard_num:
                                self.data_set_len * (self.shard_id + 1) // self.shard_num]
        self.i = 0
        self.n = len(self.file_list_shard)
        return self

    def __next__(self):
        images = []
        image_path = self.file_list_shard[self.i][0]
        f = open(image_path, 'rb')
        image = np.frombuffer(f.read(), dtype = np.uint8)
        self.i += 1
        if self.i >= self.n:
            raise StopIteration
        return [image]


@pipeline_def
def create_dali_pipeline(eii, size, dali_cpu=False, is_training=True):
    dali_device = 'cpu' if dali_cpu else 'gpu'
    decoder_device = 'cpu' if dali_cpu else 'mixed'
    device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
    host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
    images = fn.external_source(source=eii, num_outputs=1, cycle='raise', parallel=True, batch=False)
    images = fn.decoders.image_random_crop(images,
                                           device=decoder_device, output_type=types.RGB,
                                           random_aspect_ratio=[1.0, 1.0],
                                           random_area=[0.75, 1.0],
                                           num_attempts=100)
    images = fn.resize(images,
                       device=dali_device,
                       resize_x=size,
                       resize_y=size,
                       interp_type=types.INTERP_TRIANGULAR)
    mirror = fn.random.coin_flip(probability=0.5)

    images = fn.crop_mirror_normalize(images.gpu(),
                                      dtype=types.FLOAT,
                                      output_layout="CHW",
                                      crop=(size, size),
                                      mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                      std=[0.229 * 255,0.224 * 255,0.225 * 255],
                                      mirror=mirror)
    return images


if __name__ == "__main__":
    data_list = json.loads(open("test_file_list.json").read())
    eii = ExternalInputIterator(shard_id=0, shard_num=8, seed=2021, text_list=data_list, image_list=data_list)
    pipe = create_dali_pipeline(batch_size=384,
                                num_threads=4,
                                device_id=1,
                                py_start_method='spawn',
                                size=224,
                                dali_cpu=True,
                                is_training=True,
                                prefetch_queue_depth=8,
                                py_num_workers=10,
                                eii=eii)
    pipe.build()
```

```
Traceback (most recent call last):
  File "loader_test.py", line 80, in <module>
    pipe.build()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 656, in build
    self.start_py_workers()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 629, in start_py_workers
    self._start_py_workers()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 556, in _start_py_workers
    self._parallel_input_callbacks, self._prefetch_queue_depth, self._py_start_method, self._py_num_workers)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/nvidia/dali/_multiproc/pool.py", line 370, in from_groups
    pool = ProcPool(callbacks, queue_depths, num_workers, start_method, initial_chunk_size)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/nvidia/dali/_multiproc/pool.py", line 210, in __init__
    self._start_processes()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/nvidia/dali/_multiproc/pool.py", line 255, in _start_processes
    process.start()
  File "/opt/conda/envs/py36/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/opt/conda/envs/py36/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/envs/py36/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/envs/py36/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/envs/py36/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/conda/envs/py36/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_get_callback_from_source.<locals>.<lambda>'
```

**Comment by klecki** [comment]
Hi @Doom9234,
this is omission in handling of the External Source. Unfortunately, we can't support iterables as `source` in that case - it would mean that the worker threads try to use the copies of the same iterable without any communication - so we can't control which samples to produce there.

What we support is named callables (functions, objects defining `__call__`), that accept one argument - it will be [SampleInfo](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/data_types.html#nvidia.dali.types.SampleInfo) object describing the sample index to produce.

Currently we can support objects and functions that are picklable (usually this means it should be a function in global/top-level scope).

We plan to extend the documentation, add a tutorial and better error messages soon.

**Comment by Doom9234** [comment]
Hi @klecki ,
Thx for the reply.  After I fixed the external source, I used `DALIGenericIterator` to wrap the pipeline with `parallel`  External Source, but the `reset()` method seems not working,  I tried to set `self.n = 0` before `StopIteration`, but I dont know if it is the correct way to reset.

```
class ExternalInputIterator(object):
    def __init__(self, shard_id, shard_num, seed, image_list, text_list):
        image_list = json.loads(open(image_list).read())
        text_list = json.loads(open(text_list).read())
        self.file_list = list(zip(image_list, text_list))
        self.data_set_len = len(self.file_list)
        self.shard_id = shard_id
        self.shard_num = shard_num
        random.seed(seed)
        self.i = 0
        random.shuffle(self.file_list)
        self.file_list_shard = self.file_list[self.data_set_len * self.shard_id // self.shard_num:
                                self.data_set_len * (self.shard_id + 1) // self.shard_num]
        self.n = len(self.file_list_shard)

    def __call__(self):
        images = []
        image_path = self.file_list_shard[self.i][0]
        f = open(image_path, 'rb')
        image = np.frombuffer(f.read(), dtype = np.uint8)
        self.i += 1
        if self.i >= self.n:
           self.n = 0
            raise StopIteration
        return [image]

```

**Comment by JanuszL** [comment]
Hi @Doom9234,

The `reset` function of the `DALIGenericIterator` doesn't affect the external source operator state.
Either you need to expose the reset function for the `ExternalInputIterator` or autoreset as in your case.

**Comment by Doom9234** [comment]
Hi @JanuszL ,
Thx for your reply, I think expose the reset func maybe a proper way to reset the loader.
