### ISSUE TITLE
How to read data with multiple ndarrays linked to one label?

### ISSUE THREAD

**Issue by abebe9849** [NVIDIA/DALI#3222]
When an image such as jpeg is linked to the label,I think the pipeline is like this
```
class DALIPipeline(Pipeline):
  def __init__(self):
     self.input=nvidia.dali.ops.readers.File(file_root='.', file_list='dali.txt')
     self.decode = nvidia.dali.ops.decoders.Image(device = "mixed", output_type = types.DALIImageType.RGB)
  def define_graph(self):
     images, labels = self.input(name="Reader")
     images = self.decode(images)
```

but, I don't know how to cope with the case that image1.npy &image2.npy are linked to a label(0 or 1 or 2...)

I have train.csv which has like below

```
target,file_path,extra_file_path
1,~~/id0.npy,~~~/id0.npy
0,~~/id1.npy,~~~/id1.npy
0,~~/id2.npy,~~~/id2.npy

```

**Comment by JanuszL** [comment]
Hi @abebe9849,

I'm sorry but I don't fully understand your case. Do you want to mix labels for a given sample - image1.npy should belong to classes 0 and 1 at the same time?

**Comment by abebe9849** [comment]
thank you for your reply
I want to replace the following torch dataset with dali.


```

class Dataset(torch.utils.data.Dataset):
    def __init__(self, df):
        self.df = df
    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        file_path = self.df['file_path'].values[idx]
　　ex_file_path = self.df['file_path2'].values[idx]

        image = np.load(file_path).astype(np.float32)
        ex_image = np.load(ex_file_path).astype(np.float32)
        image = np.concatenate([image,ex_image])

        image = torch.from_numpy(image.transpose(2,0,1)).float()

        label_ = self.df["target"].values[idx]
        label = torch.tensor(label_)

        return image, label

```

**Comment by JanuszL** [comment]
Hi @abebe9849,

You can parse your train.csv in python, extract labels and files and use two parallel file readers:
```
files1 = [...]
files2= [...]
labels = [...]


@pipeline_def
def simple_pipeline():
   file1, _ = fn.readers.numpy(files=files1, labels=labels, seed=x)
   file2, labels = fn.readers.numpy(files=files1, labels=labels, seed=x)
```
and use cat/stack operation to merge files together.

**Comment by abebe9849** [comment]
Thanks
I tried below. 
```
folds = pd.read_csv("../folds.csv")
files = folds["file_path"].values#list of image path[../id0.npy,../id1.npy...]
labels = folds["target"].values#[0,0,1,1,0...]

@pipeline_def
def simple_pipeline():
   ##file1, _ = fn.readers.numpy(files=files1, labels=labels, seed=2020)
   file = fn.readers.numpy(files=files, labels=labels, seed=2020)
   return file


pipes = simple_pipeline(batch_size=16,num_threads=1) 
pipes.build()
pipe_out = pipes.run()
d = pipe_out
```
but, I got these error.

```
Traceback (most recent call last):
  File "~~/python3.8/site-packages/nvidia/dali/ops.py", line 425, in __init__
    arg_inp = _Constant(arg_inp, device="cpu")
  File "~~/python3.8/site-packages/nvidia/dali/types.py", line 492, in Constant
    return ConstantNode(device, value, dtype, shape, layout, **kwargs)
  File "~~/python3.8/site-packages/nvidia/dali/types.py", line 376, in ConstantNode
    actual_type = to_dali_type(value.dtype)
  File "~~/site-packages/nvidia/dali/types.py", line 351, in to_dali_type
    raise TypeError("'{}' could not be converted into any known DALIDataType.".format(framework_type));
TypeError: 'object' could not be converted into any known DALIDataType.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "debug.py", line 29, in <module>
    pipes = simple_pipeline(batch_size=16,num_threads=1) 
  File "~~/python3.8/site-packages/nvidia/dali/pipeline.py", line 1304, in create_pipeline
    pipe_outputs = func(*args, **fn_kwargs)
  File "debug.py", line 25, in simple_pipeline
    file = fn.readers.numpy(files=files, labels=labels, seed=2020)
  File "~~/python3.8/site-packages/nvidia/dali/fn.py", line 76, in op_wrapper
    return op_class(**init_args)(*inputs, **call_args)
  File "~~python3.8/site-packages/nvidia/dali/ops.py", line 627, in __call__
    op_instances.append(_OperatorInstance(input_set, self, **kwargs))
  File "~~/python3.8/site-packages/nvidia/dali/ops.py", line 427, in __init__
    raise TypeError(
TypeError: Expected inputs of type `DataNode` or convertible to constant nodes. Received input `files` of type 'ndarray'.
```

**Comment by JanuszL** [comment]
Hi @abebe9849,

I think your `files` and `labels` values are `ndarray` while they should be a plain python list of strings and integers.
Can you just try and see how that works:
```
files = ["../id0.npy", "../id1.npy"]
labels = [0, 1]

@pipeline_def
def simple_pipeline():
   file = fn.readers.numpy(files=files, labels=labels, seed=2020)
   return file


pipes = simple_pipeline(batch_size=16,num_threads=1) 
pipes.build()
pipe_out = pipes.run()
d = pipe_out
```
