### ISSUE TITLE
Dealing with fn.external_source situation when infinite wait times need to be avoided

### ISSUE THREAD

**Issue by stefan-lange-dataeng** [NVIDIA/DALI#3317]
We have a setup with a custom iterator which retrieves tasks from a python `multiprocessing.Queue`. 
The iterator's `__next__` method looked like this:

```
class DaliSourceIterator():
...
def __next__(self):  
    task = self._task_queue.get()
    ...  
    return np_img, np_id
...
```

This iterator is then used via fn.external_source in a Pipeline like this:

```
def DaliPipe(batch_size: int, num_threads: int, device_id: int, source_iter: Iterator, yolact_mask_size: int):
    pipe = Pipeline(batch_size, num_threads, device_id, prefetch_queue_depth=1)
    with pipe:
        img, id = fn.external_source(source=source_iter, num_outputs=2, batch=False)
        ...
        pipe.set_outputs(img_tensor_float, img_shape, id)
    return pipe
```

The source_iter is consumed by a ```nvidia.dali.plugin.pytorch.DALIGenericIterator```:

```
def _init_dali(self, yolact_size):
        self.dali_source = DaliSourceIterator(self.task_queue)
        self.dali_pipe = DaliPipe(batch_size=1, num_threads=self.image_decode_threads,
            device_id=0, source_iter=self.dali_source, yolact_mask_size=yolact_size)

self._init_dali(yolact_size)
pytorch_iter = DALIGenericIterator(self.dali_pipe, ['img', 'shape', 'id'], last_batch_policy=LastBatchPolicy.PARTIAL)
for data_arr in pytorch_iter:
        ...
```

Often it happens that the queue remains empty for a longer time (e. g. > 5s). We want to avoid blocking on the queue, and therefore we changed the call to self._task_queue.get():

```
def __next__(self):
    task = None
    try:
        task = self._task_queue.get(True, 1)
    except queue.Empty:
        raise StopIteration
    ...
    return np_img, np_id
```

However, it is now unclear how/where to handle the ```StopIteration```. Trying to catch it in the processing logic of the ```DALIGenericIterator``` seems not to work - we get a stack trace like this:

```
File "/opt/miniconda3/envs/yolact/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 183, 
in __init__ self._first_batch = DALIGenericIterator.__next__(self) 
File "/opt/miniconda3/envs/yolact/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 194, 
in __next__ outputs = self._get_outputs() 
File "/opt/miniconda3/envs/yolact/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 260, 
in _get_outputs raise e 
File "/opt/miniconda3/envs/yolact/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 255, 
in _get_outputs outputs.append(p.share_outputs()) 
File "/opt/miniconda3/envs/yolact/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 860, 
in share_outputs raise StopIteration
```

How/where should we handle the ```StopIteration```?
Is it a suitable approach at all to use a ```StopIteration``` for our purpose?
If not, how can we enforce that wait time for new input in the queue can be limited (limited in the sense that we want to make sure that all images which had arrived in the queue before get completely processed without one or more getting stuck in the pipeline)?

**Comment by JanuszL** [comment]
Hi @stefan-lange-dataeng,

You should not adjust `DALIGenericIterator` - it already catches `StopIteration` so iterating over `DALIGenericIterator` ends when the data source is empty.
So when the data source raises `StopIteration`, the below `for` loop ends.
```
it = DALIGenericIterator(...)
for data in it:
    (....)
```
There is an additional logic inside the pipeline and `DALIGenericIterator` that make sure that data (in case of pipelining what is the default setting) inside the pipeline is properly processed through all stages.

In your case, I don't think you need to do anything inside the DALI itself. Then your data source raises `StopIteration` is should be properly propagated and calling `__next__` on `DALIGenericIterator` will re-raise it or the loop will end like in the example above.

**Comment by stefan-lange-dataeng** [comment]
Hi @JanuszL,

thanks a lot for the quick answer.
What puzzles me is that in my case, the StopIteration does not seem to get handled automatically as described by you, but instead an exception is thrown (see stack trace pasted above).

Can it have to do with the initialization of the `DALIGenericIterator`? In the latest attempt, I tried:

```
pytorch_iter = DALIGenericIterator(
    pipelines=[self.dali_pipe], 
    output_map=['img', 'shape', 'id'], 
    auto_reset=True,
    last_batch_policy=LastBatchPolicy.PARTIAL, 
    last_batch_padded=True)
```

But it leads to the same error.
Can you think of other parameters (for iterators, pipeline, ...) which may be wrongly configured?

Regards, Stefan

**Comment by JanuszL** [comment]
Hi @stefan-lange-dataeng,

Please check a code sniped that works in my case:
```
from nvidia.dali.pipeline import pipeline_def
import nvidia.dali.fn as fn
import numpy as np
from nvidia.dali.plugin.pytorch import DALIGenericIterator as DALIGenericIterator, LastBatchPolicy as LastBatchPolicy

batch_size = 2
test_data_shape = [2, 3, 4]

class EII():
    def __init__(self, batch_size):
        self.counter = 0
        self.batch_size = batch_size

    def __iter__(self):
        # return a copy, so that the iteration number doesn't collide
        return EII(self.batch_size)

    def __next__(self):
        out = [np.random.randint(0, 255, size = test_data_shape, dtype = np.uint8) for _ in range(batch_size)]
        self.counter += 1
        if self.counter > 5:
            raise StopIteration
        return out

@pipeline_def
def get_pipeline():
    data = fn.external_source(source = EII(batch_size))
    return data

pipe = get_pipeline(batch_size=batch_size, num_threads=4, device_id=0)
dataloader = DALIGenericIterator(pipe, ["data"],
    auto_reset=True,
    last_batch_policy=LastBatchPolicy.PARTIAL,
    last_batch_padded=True)

for i, d in enumerate(dataloader):
    print(i)```

Maybe there is something you do in your code that I missed in my example. If you can provide a self-contained example that would show what you want to achieve it would be much easier to guide you.

**Comment by stefan-lange-dataeng** [comment]
Hi @JanuszL,

please find here a condensed, oversimplified version of the code which reproduces the issue.
It attempts to simulate the situation that tasks sometimes appear in the task queue with a delay, and we want to achieve that every task is reliably processed with a guaranteed upper bound for latency (it is not just about throughput for all tasks but for latency limitation for individual tasks).

File main.py:

```
import logging
from logging import handlers
import multiprocessing as mp
import os
from task_consumer_simple import TaskConsumerSimple
from task_producer_simple import TaskProducerSimple

TASK_WORKER_NUM = 1

if __name__ == '__main__':

    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)
    task_queue = mp.Queue()

    processes = []
    max_wait_consumer = 1
    processes.append(TaskConsumerSimple(task_queue, max_wait_consumer))

    num_iterations = 1000
    delay_every_n = 19
    max_delay_producer = 5
    batch_size = 2
    test_data_shape = [2, 3, 4]
    processes.extend(TaskProducerSimple(idx, batch_size, test_data_shape, num_iterations, task_queue,
        delay_every_n, max_delay_producer, logger) for idx in range(TASK_WORKER_NUM))

    for p in processes:
        p.start()
    # Check if any process stopped
    mp.connection.wait(p.sentinel for p in processes)
    logger.warning("One of the processes stopped. Stopping all others")
    for p in processes:
        p.terminate()
```

File dali_util.py:

```
import logging
import multiprocessing as mp
import os
import queue
from typing import Iterator
import numpy as np
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.fn as fn

class DaliSourceIterator():

    def __init__(self, task_queue: mp.Queue, max_wait):
        self._task_queue = task_queue
        self.task_dict = dict()
        self._id_counter = 0
        self._max_wait = max_wait
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.DEBUG)

    def __iter__(self):
        return DaliSourceIterator(self._task_queue, self._max_wait)

    def __next__(self):
        task = None
        try:
            task = self._task_queue.get(True, self._max_wait)
        except queue.Empty:
            self.logger.error('External input iterator. No tasks remaining in task queue, stopping iterator.')
            raise StopIteration
        #self.logger.error(f'External input iterator. Found task in task queue, processing it.')
        return np.asarray(task)

def DaliPipe(batch_size: int, num_threads: int, device_id: int, source_iter: Iterator):
    pipe = Pipeline(batch_size, num_threads, device_id, prefetch_queue_depth=1)
    with pipe:
        res = fn.external_source(source=source_iter)
        pipe.set_outputs(res)
    return pipe
```

File task_producer_simple.py:

```
import multiprocessing as mp
import numpy as np
import os
import time
import logging

class TaskProducerSimple(mp.Process):
    def __init__(self, idx, batch_size, test_data_shape, num_iterations, task_queue, delay_every_n, max_delay, logger, *args, **kwargs):
        self.idx = idx
        self.batch_size = batch_size
        self.test_data_shape = test_data_shape
        self.num_iterations = num_iterations
        self.task_queue = task_queue
        self.delay_every_n = delay_every_n
        self.max_delay = max_delay
        self.logger = logger
        super(TaskProducerSimple, self).__init__(*args, **kwargs)
    def run(self):
        request_count = 0
        for i in range(0, self.num_iterations):
            request_count += 1
            if (request_count % self.delay_every_n == 0):
                #self.logger.error(f'Task producer. Request count: {request_count}, delay every {self.delay_every_n} requests')
                num_s_sleep = np.random.randint(0, self.max_delay+1)
                self.logger.error(f'Task producer. Sleeping {num_s_sleep}s.')
                time.sleep(num_s_sleep)
            out = [np.random.randint(0, 255, size = self.test_data_shape, dtype = np.uint8) for _ in range(self.batch_size)]
            #self.logger.error('Task producer. Putting task into task queue')
            self.task_queue.put(out)
```

File task_consumer_simple.py:

```
import logging
import multiprocessing as mp
import numpy as np
from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy

from dali_util import DaliSourceIterator, DaliPipe

class TaskConsumerSimple(mp.Process):
    def __init__(self, task_queue: mp.Queue, max_wait=2, *args, **kwargs):
        super(TaskConsumerSimple, self).__init__(*args, **kwargs)
        self.task_queue = task_queue
        self.max_wait = max_wait
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.DEBUG)

    def _init_dali(self, max_wait):
        self.dali_source = DaliSourceIterator(self.task_queue, max_wait)
        self.dali_pipe = DaliPipe(batch_size=2, num_threads=4,
                                  device_id=0, source_iter=self.dali_source)

    def run(self):
        while True:
            try:
                self._init_dali(self.max_wait)
                #self.logger.error('Task consumer. Initialized DaliSourceIterator (external input)')
                pytorch_iter = DALIGenericIterator(
                    pipelines=[self.dali_pipe],
                    output_map=["data"])
                    #auto_reset=True,
                    #last_batch_policy=LastBatchPolicy.PARTIAL, 
                    #last_batch_padded=True)
                #self.logger.error('Task consumer. Initialized DALIGenericIterator')         
                for i, d in enumerate(pytorch_iter):
                    #print(f'{i}: {d}')
                    print(f'{i}')
            except RuntimeError as e:
                self.logger.exception("Task consumer. Error while processing task.")
```

This leads in my environment to the following exception:

```
Traceback (most recent call last):
  File "/opt/conda/envs/yolact/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 183, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/opt/conda/envs/yolact/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 194, in __next__
    outputs = self._get_outputs()
  File "/opt/conda/envs/yolact/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 260, in _get_outputs
    raise e
  File "/opt/conda/envs/yolact/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 255, in _get_outputs
    outputs.append(p.share_outputs())
  File "/opt/conda/envs/yolact/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 860, in share_outputs
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/yolact/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/jupyter/dali_test_simplified/task_consumer_simple.py", line 28, in run
    output_map=["data"])
  File "/opt/conda/envs/yolact/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 185, in __init__
    assert False, "It seems that there is no data in the pipeline. This may happen if `last_batch_policy` is set to PARTIAL and the requested batch size is greater than the shard size."
AssertionError: It seems that there is no data in the pipeline. This may happen if `last_batch_policy` is set to PARTIAL and the requested batch size is greater than the shard size.
```

Regards, Stefan

**Comment by JanuszL** [comment]
Hi @stefan-lange-dataeng,

I see where the problem is.
The `DALIGenericIterator` schedules the processing of the first batch of data when is created so during the training the first call to the `__next__` method returns data instantly. However when there is no data, for example, `external_source` raises `StopItearation` during the first call the error is thrown. To overcome this you can set ```prepare_first_batch=False,``` in the `DALIGenericIterator` so the DALI pipeline execution is not scheduled ahead of time and delayed to the first call of the `__next__` method of `DALIGenericIterator`, where `StopItearation` is correctly handled by your code.

Following `task_consumer_simple.py` should do what you want (also you don't have to recreate the DALI pipeline and iterator every time):
```
import logging
import multiprocessing as mp
import numpy as np
from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy

from dali_util import DaliSourceIterator, DaliPipe


test_data_shape = [2, 3, 4]
class EII():
    def __init__(self, batch_size):
        self.counter = 0
        self.batch_size = batch_size

    def __iter__(self):
        # return a copy, so that the iteration number doesn't collide
        return EII(self.batch_size)

    def __next__(self):
        out = [np.random.randint(0, 255, size = test_data_shape, dtype = np.uint8) for _ in range(self.batch_size)]
        self.counter += 1
        if self.counter > 5:
            raise StopIteration
        return out

class TaskConsumerSimple(mp.Process):
    def __init__(self, task_queue: mp.Queue, max_wait=2, *args, **kwargs):
        super(TaskConsumerSimple, self).__init__(*args, **kwargs)
        self.task_queue = task_queue
        self.max_wait = max_wait
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.DEBUG)

    def _init_dali(self, max_wait):
        self.dali_source = DaliSourceIterator(self.task_queue, max_wait)
        self.dali_pipe = DaliPipe(batch_size=2, num_threads=4,
                                  device_id=0, source_iter=self.dali_source)

    def run(self):
        self._init_dali(self.max_wait)
        pytorch_iter = DALIGenericIterator(
            pipelines=[self.dali_pipe],
            prepare_first_batch=False,
            auto_reset=True,
            output_map=["data"])
        while True:
            try:
                for i, d in enumerate(pytorch_iter):
                    print(f'{i}')
                print("data end")
            except RuntimeError as e:
                self.logger.exception("Task consumer. Error while processing task.")
```

**Comment by stefan-lange-dataeng** [comment]
Hi @JanuszL,

thank you, this indeed seems to fix the issue.
Interesting and good that the pipeline/iterators do not need to be reinitialized on each "while True" loop iteration.
Impressive how quickly you are able to spot the issue, thanks a lot for the extremely fast reaction, much appreciated.
I realize I have a lot to learn still, not everything feels fully intuitive yet ;-)

Regards, Stefan

**Comment by JanuszL** [comment]
@stefan-lange-dataeng,

We are glad to help. Feel free to raise issues or questions in case of further problems.

Cheers,
Janusz
