### ISSUE TITLE
Assert on "png" failed

### ISSUE THREAD

**Issue by WangChyanhassth-2say** [NVIDIA/DALI#3381]
Hi,
I would like to ask about my code using DALI and it's tensorflow plugin.
At first I created .tfrecords and .idx files of my dataset.
And when i run the pipe it comes like this:
```
Traceback (most recent call last):
  File "dali_train.py", line 68, in <module>
    main()
  File "dali_train.py", line 29, in main
    x_train,y_train = dali_dataload.get_tensors(tfrecord_train, max_batch_size, train_idx)
  File "/workspace/dali_dataload.py", line 24, in get_tensors
    images, labels = pipe.run()
  File "/usr/local/python3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 917, in run
    return self.outputs()
  File "/usr/local/python3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 816, in outputs
    return self._outputs()
  File "/usr/local/python3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 900, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator decoders__Image encountered:
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:548] [/opt/dali/dali/image/image_factory.cc:39] Assert on "png" failed
```
here's my dali_dataload.py
```
def get_tensors(tfrecord, batch_size, tfrecord_idx):
	pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
	with pipe:
		inputs = fn.readers.tfrecord(
			path=tfrecord,
			index_path=tfrecord_idx,
			features = {
				"image/encoded" : tfrec.FixedLenFeature((), tfrec.string, ""),
				"image/class/label": tfrec.FixedLenFeature([1], tfrec.int64,  -1)})
		jpegs = inputs["image/encoded"]
		labels = inputs["image/class/label"]
		images = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
		resized = fn.resize(images, device="gpu", size=(224,224), mode='stretch')
	pipe.set_outputs(resized, labels)
	pipe.build()
	images, labels = pipe.run()
	images = images.as_cpu().as_array()
	labels = labels.as_array()
	return (resizes, labels)
```
get_tfrecords.py
```
def image_path_load(train_path, classes, is_shuffle=True):
    images_path = []
    labels = []
    print('Reading training images')
    for fld in classes:  # assuming data directory has a separate folder for each class, and that each folder is named after the class
        index = classes.index(fld)
        print('Loading {} files (Index: {})'.format(fld, index))
        path = os.path.join(train_path, fld)
        files = os.listdir(path)
        read_number = 0
        for file in tqdm(files):

            image_file_path = os.path.join(path, file)


            if file[-4:] != ".jpg" and file[-4:] != ".png":
                continue
            read_number += 1
            images_path.append(image_file_path)
            label = index
            labels.append(label)
    if is_shuffle:
        images_path, labels = shuffle(images_path, labels)
    labels = np.array(labels)
    return images_path, labels

def image_to_tfrecord(image_path_list, labels, tfrecord_save_path, tfrecord_image_number, is_augmentation=False):
    bestnum = tfrecord_image_number
    num = 0
    recordfilenum = 0

    if not os.path.exists(tfrecord_save_path):
        os.mkdir(tfrecord_save_path)

    ftrecordfilename = ("traindata.tfrecords")
    writer = tf.io.TFRecordWriter(os.path.join(tfrecord_save_path, ftrecordfilename))
    for image_path, label in tqdm(zip(image_path_list, labels)):
        num = num + 1
        if num > bestnum:
            num = 1
            recordfilenum = recordfilenum + 1
            writer.close()
            ftrecordfilename = ("traindata.tfrecords")
            writer = tf.io.TFRecordWriter(os.path.join(tfrecord_save_path, ftrecordfilename))

        # img = Image.open(image_path, 'r')
        # print(image_path)
        img = cv2.imread(image_path)
        img = cv2.resize(img, (224, 224))
        size = img.shape
        img_raw = img.tobytes()
        example = tf.train.Example(
            features=tf.train.Features(feature={
                'label': tf.train.Feature(int64_list=tf.train.Int64List(value=[label])),
                'img_raw': tf.train.Feature(bytes_list=tf.train.BytesList(value=[img_raw])),
                'img_width': tf.train.Feature(int64_list=tf.train.Int64List(value=[size[0]])),
                'img_height': tf.train.Feature(int64_list=tf.train.Int64List(value=[size[1]]))
            }))
        writer.write(example.SerializeToString())
    writer.close()

if __name__ == '__main__':
    datasets = ['train', 'val']
    data_path = '/workspace/pose'
    tfrecord_save_path = 'tfrecord'
    is_augmentation = False
    if not os.path.exists(tfrecord_save_path):
        os.mkdir(tfrecord_save_path)
    tfrecord_image_number = config.IMAGE_NUMBER
    classes = config.CLASSES
    for dataset in datasets:
        image_path = os.path.join(data_path, dataset)
        images_path_list, labels = image_path_load(image_path, classes)
        save_paths = os.path.join(tfrecord_save_path, dataset)
        image_to_tfrecord(images_path_list, labels, save_paths, tfrecord_image_number, is_augmentation)
```
my tensorflow version is 1.13.0, with cuda10.0 and cudnn_v7.6.3.30

**Comment by JanuszL** [comment]
Hi @WangChyanhassth-2say,

I see that you store only `label` and `img_raw` while you read `image/encoded` and `image/class/label`. These sets need to match. In the case of DALI `fn.readers.tfrecord` if the requested feature in the given entry is not found the empty tensor is returned. So in this case you are trying to decode an empty tensor that yields an error.
Moreover, I see you store raw images while you try to read and decode. So you need to either store encoded images or read them without decoding and use [the `reshape`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.reshape) operator together with the data from `img_width` and `img_height` to transform a 1D array into the 2D image.

**Comment by WangChyanhassth-2say** [comment]
> Hi @WangChyanhassth-2say,
> 
> I see that you store only `label` and `img_raw` while you read `image/encoded` and `image/class/label`. These sets need to match. In the case of DALI `fn.readers.tfrecord` if the requested feature in the given entry is not found the empty tensor is returned. So in this case you are trying to decode an empty tensor that yields an error. Moreover, I see you store raw images while you try to read and decode. So you need to either store encoded images or read them without decoding and use [the `reshape`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.reshape) operator together with the data from `img_width` and `img_height` to transform a 1D array into the 2D image.

thx for your reply!
I now use the call **tf.gfile.FastGFile(image_path, 'rb').read()** to save the data, and it works well.
so the code of dali_dataload.py becomes:
```
def get_tensors(tfrecord, batch_size, tfrecord_idx):
    pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
    with pipe:
        inputs = fn.readers.tfrecord(
            path=tfrecord,
            index_path=tfrecord_idx,
            features = {
                "label": tfrec.FixedLenFeature([1], tfrec.int64,  -1),
                "img" : tfrec.FixedLenFeature((), tfrec.string, "")})
        jpegs = inputs["img"]
        labels = inputs["label"]
        images = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
        resized = fn.resize(images, device="gpu", size=(224,224), mode='stretch')
    pipe.set_outputs(resized, labels)
    pipe.build()
    images, labels = pipe.run()
    images = images.as_cpu().as_array()
    labels = labels.as_array()

    return (images, labels)
```
it can run now, thank you very much!

**Comment by WangChyanhassth-2say** [comment]
nope, I now run it and cause this:
```
Traceback (most recent call last):
  File "dali_train.py", line 68, in <module>
    main()
  File "dali_train.py", line 29, in main
    x_train,y_train = dali_dataload.get_tensors(tfrecord_train, config.TRAIN_NUMBER, train_idx)
  File "/workspace/dali_dataload.py", line 24, in get_tensors
    images, labels = pipe.run()
  File "/usr/local/python3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 917, in run
    return self.outputs()
  File "/usr/local/python3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 816, in outputs
    return self._outputs()
  File "/usr/local/python3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 900, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator decoders__Image encountered:
CUDA allocation failed
Current pipeline object is no longer valid.
```
