### ISSUE TITLE
RuntimeError from coco_loader on custom dataset: Assert on "Size() > 0" failed: No files found.

### ISSUE THREAD

**Issue by giaxxi** [NVIDIA/DALI#3413]
Hello,
I'm working with TLT and I'm getting the following error from DALI.

```
Namespace(amp=False, backbone='resnet50', backbone_path=None, batch_size=32, benchmark_iterations=20, benchmark_warmup=20, checkpoint=None, data='coco_my_dataset', epochs=65, eval_batch_size=32, evaluation=[21, 31, 37, 42, 48, 53, 59, 64], json_summary=None, learning_rate=0.0026, local_rank=0, log_interval=20, mode='training', momentum=0.9, multistep=[43, 54], no_cuda=False, num_workers=4, save=None, seed=None, warmup=None, weight_decay=0.0005)
Using seed = 3477
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "main.py", line 295, in <module>
    train(train_loop_func, logger, args)
  File "main.py", line 158, in train
    train_loader = get_train_loader(args, args.seed - 2**31)
  File "/workspace/src/data.py", line 34, in get_train_loader
    train_pipe.build()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 408, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: [/opt/dali/dali/operators/reader/loader/coco_loader.h:73] Assert on "Size() > 0" failed: No files found.
Stacktrace (32 entries):
.....
```

<hr>

**How I got there**

I'm running https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Detection/SSD#the-script-mainpy
`python main.py --data coco` this runs without issues with the original coco2017 dataset.

But when I switch to my custom dataset I got the error and I'm actually unable to find out any problem in my dataset:
`python main.py --data my_coco_dataset`
**Maybe understanding the error message helps me find the problem**

<hr>

**Here is my setup**
Custom dataset following the instruction here:
https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Detection/SSD#getting-the-data

My folder structure is
```
my_coco_dataset
    |-annotations
        |-instance_train2017
        |-instances_val2017
    |-train2017
    |-val2017
```
I checked annotations with pycocotools to be sure indexes are created.
I checked all annotated image files exist.

Here are the keys of my annotations:
```
my_coco_ann.keys()
# dict_keys(['info', 'images', 'categories', 'licenses', 'annotations'])

my_coco_ann['images'][0].keys()
# dict_keys(['id', 'width', 'height', 'file_name'])

my_coco_ann['annotations'][0].keys()
# dict_keys(['id', 'image_id', 'bbox', 'area', 'iscrowd', 'category_id', 'segmentation'])
```

I'm  not using segmentation, so
```
my_coco_ann['annotations'][0]['segmentation']
#=> []
```

Thank you.

**Comment by JanuszL** [comment]
Hi @giaxxi,

As I see [the mentioned SSD code](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Detection/SSD) assumes a certain layout of data.
You can see it [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Detection/SSD/src/data.py#L26) and it expects:
```
root:
  |- annotations/instances_train2017.json
  |- train2017
```
and the files paths in the annotation file should be relative to the `root/train2017`. I guess that may be the problem in your case.

**Comment by giaxxi** [comment]
Hello @JanuszL,
thanks a lot for the answer, I checked many times filenames and folders: paths looks correct.

I tried with some typo in the files and folders name or other errors to check what kind of errors it raises, here what I found:
1. When I pass a wrong folder name as `coco_` instead of `coco` I got:
   - >RuntimeError: [/opt/dali/dali/operators/reader/loader/coco_loader.cc:245] Assert on "f" failed: **Could not open JSON annotations file: "coco_/annotations/instances_train2017.json"**
2. When I misspell the image folder name `train2017_` instead of `train2017` I got:
   - >RuntimeError: Critical error in pipeline: [/opt/dali/dali/util/mmaped_file.cc:105] **File mapping failed: coco/train2017_/000000069311.jpg**
 3. When I delete some images from the folder:
    - same error as point 2, as expected.

So, it seems like the error I'm getting is not related to missing annotation json file or missing images. It's something different.

I checked also file permission and opened each and every image, to be sure of not having empty files. I also checked that each annotation maps to an existing file.

No way to get rid of this error:
> RuntimeError: [/opt/dali/dali/operators/reader/loader/coco_loader.h:73] **Assert on "Size() > 0" failed: No files found.**

Can help to understand it's meaning?

**Comment by giaxxi** [comment]
I finally saw the elephant in the room: **the integer I used as `id` and `image_id` was too big.**

I was using a 24 digit integer as index (from a series of timestamps conversion while tagging the dataset), I then mapped the original id to new id with integer starting from `0` and the trick was done.

**Warning**: while remapping the ids I added new keys `image_id_original` and `id_original` which still caused the error, so I had to get rid of the backup keys.

Maybe nobody will encounter this problem or maybe this can suggest a way to make the error message a more understandable.
