### ISSUE TITLE
Differences between fn.WarpAffine and cv2.warpAffine

### ISSUE THREAD

**Issue by okanlv** [NVIDIA/DALI#3527]
Hi,
I have created two different pipelines, almost same as the one in [this test script](https://github.com/NVIDIA/DALI/blob/main/dali/test/python/test_operator_warp.py) to test out the difference between `fn.warp_affine` and `cv2.warpAffine` methods. I have used the same test logic, but slightly modified it to make it simpler. However, two pipelines generates different results. I have used the following code
```python3
import argparse
import platform

import cv2
import numpy as np
import nvidia.dali as dali
import nvidia.dali.fn as fn
import nvidia.dali.ops as ops
import nvidia.dali.types as types
from nvidia.dali import pipeline_def


# ref: https://github.com/NVIDIA/DALI/blob/9bb29e7f695cff53cdafccedd21dd4d6c154b134/dali/test/python/test_utils.py#L92
def check_input(batch1, batch2, batch_size=None, eps=1e-07, max_allowed_error=None):
    def is_error(mean_err, max_err, eps, max_allowed_error):
        if max_allowed_error is not None:
            if max_err > max_allowed_error:
                return True
        elif mean_err > eps:
            return True
        return False

    if batch_size is None:
        batch_size = len(batch1)

    for i in range(batch_size):
        # This allows to handle list of Tensors, list of np arrays and TensorLists
        left = np.array(batch1[i])
        right = np.array(batch2[i])
        is_failed = False
        assert left.shape == right.shape, \
            "Shape mismatch {} != {}".format(left.shape, right.shape)
        assert left.size == right.size, \
            "Size mismatch {} != {}".format(left.size, right.size)
        if left.size != 0:
            try:
                # abs doesn't handle overflow for uint8, so get minimal value of a-b and b-a
                diff1 = np.abs(left - right)
                diff2 = np.abs(right - left)
                absdiff = np.minimum(diff2, diff1)
                err = np.mean(absdiff)
                max_err = np.max(absdiff)
                min_err = np.min(absdiff)
                total_errors = np.sum(absdiff != 0)
            except:
                is_failed = True
            if is_failed or is_error(err, max_err, eps, max_allowed_error):
                error_msg = ("Mean error: [{}], Min error: [{}], Max error: [{}]" +
                             "\n Total error count: [{}], Tensor size: [{}], Error calculation failed: [{}]").format(
                    err, min_err, max_err, total_errors, absdiff.size, is_failed)
                assert False, error_msg


# ref: https://github.com/NVIDIA/DALI/blob/9bb29e7f695cff53cdafccedd21dd4d6c154b134/dali/test/python/test_operator_warp.py#L54
def ToCVMatrix(matrix):
    offset = np.matmul(matrix, np.array([[0.5], [0.5], [1]]))
    result = matrix.copy()
    result[0][2] = offset[0] - 0.5
    result[1][2] = offset[1] - 0.5
    return result


# ref: https://github.com/NVIDIA/DALI/blob/9bb29e7f695cff53cdafccedd21dd4d6c154b134/dali/test/python/test_operator_warp.py#L61
def CVWarp(output_type, input_type, warp_matrix=None, inv_map=False):
    def warp_fn(img, matrix):
        size = (320, 240)
        matrix = ToCVMatrix(matrix)
        if output_type == dali.types.FLOAT or input_type == dali.types.FLOAT:
            img = np.float32(img)
        out = cv2.warpAffine(img, matrix, size, borderMode=cv2.BORDER_CONSTANT, borderValue=[42, 42, 42],
                             flags=(cv2.INTER_LINEAR | cv2.WARP_INVERSE_MAP) if inv_map else cv2.INTER_LINEAR);
        if output_type == dali.types.UINT8 and input_type == dali.types.FLOAT:
            out = np.uint8(np.clip(out, 0, 255))
        return out

    if warp_matrix:
        m = np.array(warp_matrix)

        def warp_fixed(img):
            return warp_fn(img, m)

        return warp_fixed

    return warp_fn


def main(filepath):
    images = []
    f = open(filepath, 'rb')
    img = np.frombuffer(f.read(), dtype=np.uint8)
    images.append(img)
    iterator = iter(images)

    input_shape = (240, 320)
    warp_matrix = (0.1, 0.9, 10, 0.8, -0.2, -20)

    # similar to https://github.com/NVIDIA/DALI/blob/9bb29e7f695cff53cdafccedd21dd4d6c154b134/dali/test/python/test_operator_warp.py#L82
    @pipeline_def(batch_size=1, num_threads=2, device_id=0)
    def WarpPipeline(device):
        m = fn.external_source(source=iterator, batch=False)
        m = fn.decoders.image(m, device=device, output_type=types.BGR)
        m = fn.warp_affine(m,
                           size=input_shape,
                           matrix=warp_matrix,
                           fill_value=42,
                           interp_type=types.INTERP_LINEAR,
                           dtype=dali.types.FLOAT,
                           inverse_map=False)
        return m

    warp_pipeline = WarpPipeline(device='cpu')
    warp_pipeline.build()
    warp_out, = warp_pipeline.run()

    warp = ops.PythonFunction(
        function=CVWarp(dali.types.FLOAT, dali.types.UINT8, [[0.1, 0.9, 10], [0.8, -0.2, -20]], False),
        output_layouts="HWC")

    iterator = iter(images)

    # similar to https://github.com/NVIDIA/DALI/blob/9bb29e7f695cff53cdafccedd21dd4d6c154b134/dali/test/python/test_operator_warp.py#L124
    @pipeline_def(batch_size=1, num_threads=2, device_id=0, exec_async=False, exec_pipelined=False)
    def CVPipeline(device):
        m = fn.external_source(source=iterator, batch=False)
        m = fn.decoders.image(m, device=device, output_type=types.BGR)
        m = warp(m)
        return m

    cv_pipeline = CVPipeline(device='cpu')
    cv_pipeline.build()
    cv_out, = cv_pipeline.run()

    check_input(warp_out, cv_out)
    print('Successful')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('file_path', type=str, help='image path', default='')
    args = parser.parse_args()

    print("Using python ({}), DALI ({}), numpy ({}), opencv ({})".format(platform.python_version(),
                                                                         dali.__version__,
                                                                         np.__version__,
                                                                         cv2.__version__))

    main(args.file_path)
```
This's the result I'm getting
```shell
>>>python dali_affine_preprocess.py path/to/img
Using python (3.8.10), DALI (1.7.0), numpy (1.21.2), opencv (4.5.3)
Traceback (most recent call last):
  File "dali_affine_preprocess.py", line 147, in <module>
    main(args.file_path)
  File "dali_affine_preprocess.py", line 133, in main
    check_input(warp_out, cv_out)
  File "dali_affine_preprocess.py", line 51, in check_input
    assert False, error_msg
AssertionError: Mean error: [0.04456837475299835], Min error: [0.0], Max error: [3.419525146484375]
 Total error count: [199616], Tensor size: [230400], Error calculation failed: [False]
```
I have also check out other issue related with this problem #2648 , but couldn't understand why the [warping test](https://github.com/NVIDIA/DALI/blob/main/dali/test/python/test_operator_warp.py) should pass but my test is failing. Just for reference, I have not tested the former warping test locally.
@mzient Do you have any suggestions?

One more thing, In [warp_affine documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html?highlight=warp_affine#nvidia.dali.fn.warp_affine), the default value for `fill_value` parameter is stated as `0.0` but it seems like it's not `0.0`. It generates different results when `fill_value` is given as `0.0` and when it's not given. The explanation might be correct though.

**Comment by mzient** [comment]
@okanlv Hello,
The difference arises because OpenCV's linear interpolation is approximated. Last time I checked, the interpolation in OpenCV was achieved by calculating the source locations at fixed point precisions, with just 5 extra bits for the fractional part. If the interpolation weights have only 5 bits (the step is 1/32), then we should have 1/64 rounding error. Assuming you have neighboring values of 0 and 255, the maximum error due to this approximation would be 255/64 = ~4.

The large error occurs at the boundary between the image and the background. I've checked that using a natural image (without sharp transitions) and clamping border mode (instead of constant) reduced the error from initial ~3 to 0.6.

Regarding the last part - the fact that there _is_ a default value in the docs is a mistake. The description is correct: when fill_value is not provided (or is `None`), then the operator doesn't use any border value and clamps source coordinates.

**Comment by okanlv** [comment]
@mzient Thanks for the quick response. I understand the difference between DALI and opencv warping much clearly now. It could be great to state this difference in the documentation imo. Also, is that the reason DALI asserts the mean difference between these warping methods is smaller than 8 during [unit tests](https://github.com/NVIDIA/DALI/blob/06428180b8efab7d70b185b6cb0403dcfdd2a9fb/dali/test/python/test_operator_warp.py#L182)?

**Comment by mzient** [comment]
@okanlv I agree that we should probably more verbose about the way we handle sampling locations - namely, that in DALI (0,0) is a _corner_ of the first pixel, not its center. When it comes to numerical issues, I don't think it's our responsibility to explain the inaccuracies of _other_ libraries, however popular they may be.

Regarding unit tests - I need to take a closer look. It seems like a bug and we're specifying mean error instead max error.

**Comment by okanlv** [comment]
That makes sense. Thanks a lot for the help.

**Comment by JanuszL** [comment]
I have updated the documentation https://github.com/NVIDIA/DALI/pull/3639.
