### ISSUE TITLE
Assert on "meta" failed: Operator Reader  not found or does not expose valid metadata

### ISSUE THREAD

**Issue by ielym** [NVIDIA/DALI#3607]
When I try to use `DALI` following the document [Using DALI in PyTorch](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-basic_example.html) , but got a error :

```python
read 6 files from 2 directories
read 6 files from 2 directories
Traceback (most recent call last):
  File "ttt.py", line 84, in <module>
    dali_iter = DALIGenericIterator(pipelines=pipes, output_map=['data', 'label'], reader_name="Reader")
  File "/usr/local/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 174, in __init__
    prepare_first_batch=prepare_first_batch)
  File "/usr/local/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 173, in __init__
    self._extract_from_reader_and_validate()
  File "/usr/local/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 183, in _extract_from_reader_and_validate
    readers_meta = [p.reader_meta(self._reader_name) for p in self._pipes]
  File "/usr/local/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 183, in <listcomp>
    readers_meta = [p.reader_meta(self._reader_name) for p in self._pipes]
  File "/usr/local/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 386, in reader_meta
    return self._pipe.reader_meta(name)
RuntimeError: [/opt/dali/dali/python/backend_impl.cc:1458] Assert on "meta" failed: Operator Reader  not found or does not expose valid metadata.
Stacktrace (39 entries):
[frame 0]: /usr/local/lib/python3.7/site-packages/nvidia/dali/backend_impl.cpython-37m-x86_64-linux-gnu.so(+0x6f9b9) [0x7f84d4a0f9b9]
[frame 1]: /usr/local/lib/python3.7/site-packages/nvidia/dali/backend_impl.cpython-37m-x86_64-linux-gnu.so(+0x2fc54) [0x7f84d49cfc54]
[frame 2]: /usr/local/lib/python3.7/site-packages/nvidia/dali/backend_impl.cpython-37m-x86_64-linux-gnu.so(+0x8d66d) [0x7f84d4a2d66d]
[frame 3]: python(_PyMethodDef_RawFastCallKeywords+0x33b) [0x55b27054212b]
[frame 4]: python(_PyObject_FastCallKeywords+0x22e) [0x55b27054248e]
[frame 5]: python(+0x5bf2b) [0x55b270527f2b]
[frame 6]: python(_PyEval_EvalFrameDefault+0x5acb) [0x55b27052ddbb]
[frame 7]: python(_PyEval_EvalCodeWithName+0x920) [0x55b2705ef270]
[frame 8]: python(_PyFunction_FastCallKeywords+0x8d) [0x55b270541c7d]
[frame 9]: python(+0x5bf75) [0x55b270527f75]
[frame 10]: python(_PyEval_EvalFrameDefault+0xeac) [0x55b27052919c]
[frame 11]: python(_PyEval_EvalCodeWithName+0x920) [0x55b2705ef270]
[frame 12]: python(_PyFunction_FastCallKeywords+0x8d) [0x55b270541c7d]
[frame 13]: python(+0x5bf75) [0x55b270527f75]
[frame 14]: python(_PyEval_EvalFrameDefault+0x27d9) [0x55b27052aac9]
[frame 15]: python(_PyEval_EvalCodeWithName+0x920) [0x55b2705ef270]
[frame 16]: python(_PyFunction_FastCallKeywords+0x8d) [0x55b270541c7d]
[frame 17]: python(+0x5bf75) [0x55b270527f75]
[frame 18]: python(_PyEval_EvalFrameDefault+0xeac) [0x55b27052919c]
[frame 19]: python(_PyEval_EvalCodeWithName+0x920) [0x55b2705ef270]
[frame 20]: python(_PyFunction_FastCallKeywords+0x8d) [0x55b270541c7d]
[frame 21]: python(+0x5bf75) [0x55b270527f75]
[frame 22]: python(_PyEval_EvalFrameDefault+0x25bc) [0x55b27052a8ac]
[frame 23]: python(_PyEval_EvalCodeWithName+0x920) [0x55b2705ef270]
[frame 24]: python(_PyFunction_FastCallDict+0x147) [0x55b270541a27]
[frame 25]: python(_PyObject_Call_Prepend+0xf5) [0x55b270544515]
[frame 26]: python(+0xd0a26) [0x55b27059ca26]
[frame 27]: python(+0xc4307) [0x55b270590307]
[frame 28]: python(_PyObject_FastCallKeywords+0x136) [0x55b270542396]
[frame 29]: python(+0x5bf2b) [0x55b270527f2b]
[frame 30]: python(_PyEval_EvalFrameDefault+0x25bc) [0x55b27052a8ac]
[frame 31]: python(_PyEval_EvalCodeWithName+0x920) [0x55b2705ef270]
[frame 32]: python(PyEval_EvalCode+0x27) [0x55b2705ef4d7]
[frame 33]: python(PyRun_FileExFlags+0xb5) [0x55b2706260d5]
[frame 34]: python(PyRun_SimpleFileExFlags+0xff) [0x55b27062626f]
[frame 35]: python(+0x6a77e) [0x55b27053677e]
[frame 36]: python(_Py_UnixMain+0x4d) [0x55b2705369cd]
[frame 37]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f84d50cf0b3]
[frame 38]: python(_start+0x2e) [0x55b2705306de]

```

My code :

```
from nvidia.dali import pipeline_def, Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.types as types
from nvidia.dali.plugin.pytorch import DALIGenericIterator

import numpy as np

@pipeline_def
def caffe_pipeline(image_dir):
    device_id = Pipeline.current().device_id
    jpegs, labels = fn.readers.file(file_root=image_dir)
    images = fn.decoders.image(jpegs, device='mixed')

    images = fn.resize(images, resize_shorter=256, interp_type=types.INTERP_LINEAR)
    images = fn.crop_mirror_normalize(
                                        images,
                                        crop_pos_x=fn.random.uniform(range=(0.0, 1.0)),
                                        crop_pos_y=fn.random.uniform(range=(0.0, 1.0)),
                                        mirror=fn.random.coin_flip(),
                                        dtype=types.FLOAT,
                                        crop=(224, 224),
                                        mean=[0., 0., 0.],
                                        std=[1., 1., 1.],
                                )

    return images, labels

if __name__ == '__main__':

    image_dir = r"/app/datasets/dali"
    num_threads = 2
    gpus = [0, 1]  # number of GPUs
    BATCH_SIZE = 8  # batch size per GPU

    pipes = [caffe_pipeline(image_dir=image_dir, batch_size=BATCH_SIZE, num_threads=num_threads, device_id=device_id) for device_id in gpus]

    for pipe in pipes:
        pipe.build()

    dali_iter = DALIGenericIterator(pipelines=pipes, output_map=['data', 'label'], reader_name="Reader")

    for i, data in enumerate(dali_iter):
        for d in data:
            label = d["label"]
            image = d["data"]
            print(label.size(), image.size())

    print("OK")




```

This may be caused by the  `render_name` parameter,  so I also tried to set the `size=6` and without using the `reader_name`, it could work well. 

So, what's the reason of my issue?

I'm using a docker container with Python=3.7.5 and nvidia-dali-cuda110==1.9.0，besides,  my Driver Version: 470.57.02  and  CUDA Version: 11.4.

**Comment by JanuszL** [comment]
Hi @ielym,
You should name your reader, so:
```
jpegs, labels = fn.readers.file(file_root=image_dir, name="Reader")
```
Should fix your problem.
