### ISSUE TITLE
Pip install question

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/DALI#3779]
Hi, I'm having an issue that's probably very simple to fix, but I haven't been able to figure out how. When I try to install DALI inside a docker container, I'm not seeing current versions and the install fails without much information:

```
root@277cc30244e7:/# pip install nvidia-pyindex
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: nvidia-pyindex in /root/.local/lib/python3.8/site-packages (1.0.9)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@277cc30244e7:/# pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/ nvidia-dali-cuda110==1.12.0
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://developer.download.nvidia.com/compute/redist/
ERROR: Could not find a version that satisfies the requirement nvidia-dali-cuda110==1.12.0 (from versions: 0.0.1.dev4, 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-dali-cuda110==1.12.0
```

It seems that only old versions `0.0.1.dev4, 0.0.1.dev5` are found.

Or, without adding a version tag:
```

root@277cc30244e7:/# pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/ nvidia-dali-cuda110
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://developer.download.nvidia.com/compute/redist/
Collecting nvidia-dali-cuda110
  Downloading nvidia-dali-cuda110-0.0.1.dev5.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-n6y_2iu7/nvidia-dali-cuda110_79ca847abcaf4083bd840abb337e4cfb/setup.py", line 150, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.
      
      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install nvidia-dali-cuda110
      ```
      
      Please refer to NVIDIA DALI installation guide for instructions:
      https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html
      ###########################################################################################
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Really appreciate any tips to get this working!

**Comment by austinmw** [comment]
Nevermind looks like this is being tracked at #3776
