### ISSUE TITLE
tensorflow example web page error 

### ISSUE THREAD

**Issue by huangsongjue** [NVIDIA/DALI#393]
Seems the command line
mpiexec --allow-run-as-root --bind-to socket -np 8 python resnet.py \
                                                     --layers=50 \
                                                     --data_dir=/data/imagenet \
                                                     --precision=fp16 \
                                                     --log_dir=/output/resnet50 \
                                                     --dali_cpu
 
in https://github.com/NVIDIA/DALI/tree/master/docs/examples/tensorflow/demo missing a “--data_idx_dir" argument? as I got following error:

Training
Traceback (most recent call last):
  File "resnet.py", line 111, in <module>
    nvutils.train(resnet_v1, args)
  File "/nfs/memverge/home/songjue/DALI-bak/docs/examples/tensorflow/demo_bak/nvutils/runner.py", line 266, in train
    hooks=training_hooks)
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1234, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1075, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1162, in _call_input_fn
    return input_fn(**kwargs)
  File "/nfs/memverge/home/songjue/DALI-bak/docs/examples/tensorflow/demo_bak/nvutils/runner.py", line 260, in <lambda>
    dali_cpu=dali_cpu, idx_filenames=train_idx_filenames)
  File "/nfs/memverge/home/songjue/DALI-bak/docs/examples/tensorflow/demo_bak/nvutils/image_processing.py", line 158, in image_set
    raise ValueError("Must provide idx_filenames for DALI's reader")
ValueError: Must provide idx_filenames for DALI's reader

**Comment by Kh4L** [comment]
Hi @huangsongjue 

You are right, this argument is actually required by the script. You need to provide an argument `data_idx_dir`: this directory should include the index files corresponding to each TFRecord file present in`data_dir`.

The files present in this directory will be through `TFRecordReader`'s argument`index_path` https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.TFRecordReader

**Comment by JanuszL** [comment]
Fixed by #397.
