### ISSUE TITLE
tensorflow example runtime error: docs/examples/tensorflow/demo

### ISSUE THREAD

**Issue by huangsongjue** [NVIDIA/DALI#394]
I got following error when I was trying to run the example code under docs/examples/tensorflow/demo.
  
### System info:
Dali: 0.7.0dev
CPU: Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz  * 2
Memory: 128GB
GPU: NVIDIA V100 (16GB) x 1
OS: CenOS 7.5
CUDA: 9.2
CuDNN: 7.3
Tensorflow: 1.12

### Command line:

python resnet.py \\
            --layers=50 \\
            --data_dir=/memverge/home/songjue/data/dali/tfrecord/ \\
            --data_idx_dir=/memverge/home/songjue/data/dali/idx \\
            --precision=fp16 \\
            --log_dir=log \\
            --dali_cpu

### stack:
PY 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0]
TF 1.12.0
Script arguments:
  --batch_size 256
  --layers 50
  --precision fp16
  --display_every 10
  --data_idx_dir /memverge/home/songjue/data/dali/idx
  --dali_cpu True
  --data_dir /memverge/home/songjue/data/dali/tfrecord/
  --iter_unit epoch
  --num_iter 90
  --log_dir log
Training
Traceback (most recent call last):
  File "resnet.py", line 111, in <module>
    nvutils.train(resnet_v1, args)
  File "/nfs/memverge/home/songjue/DALI-bak/docs/examples/tensorflow/demo_bak/nvutils/runner.py", line 266, in train
    hooks=training_hooks)
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1234, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1075, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/memverge/home/songjue/anaconda3-p35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1162, in _call_input_fn
    return input_fn(**kwargs)
  File "/nfs/memverge/home/songjue/DALI-bak/docs/examples/tensorflow/demo_bak/nvutils/runner.py", line 260, in <lambda>
    dali_cpu=dali_cpu, idx_filenames=train_idx_filenames)
  File "/nfs/memverge/home/songjue/DALI-bak/docs/examples/tensorflow/demo_bak/nvutils/image_processing.py", line 168, in image_set
    training=training)
  File "/nfs/memverge/home/songjue/DALI-bak/docs/examples/tensorflow/demo_bak/nvutils/image_processing.py", line 143, in __init__
    device_id=hvd.rank())
TypeError: dali() got an unexpected keyword argument 'pipeline'

**Comment by owenustc** [comment]
me too?  I don't know why??

**Comment by Kh4L** [comment]
Hi @huangsongjue  @owenustc

I think that you are using the v0.6 script version with a DALI install <= 0.5

In the v0.6; we updated the daliop TensorFlow plugin to use directly the pipeline instead of  the serialized version of it, hence the unexpected keyword argument  `pipeline` (that was previously named serialized pipeline).

More info: #310 that was part of https://github.com/NVIDIA/DALI/releases/tag/v0.6.0

**Comment by JanuszL** [comment]
Hi,
Please check if your example is taken from the same version as DALI installed. If it still doesn't work please reopen.
