### ISSUE TITLE
 error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by TOMMYWHY** [NVIDIA/DALI#4165]
I tried install in ubuntu env.  error as below.

~~~bash
 pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://developer.download.nvidia.com/compute/redist
Collecting nvidia-dali-cuda110
  Downloading nvidia-dali-cuda110-0.0.1.dev5.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-hgilpkub\nvidia-dali-cuda110_b2cb9e65619a45a6bcf523b634fe7a7a\setup.py", line 150, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.
      
      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install nvidia-dali-cuda110
      ```
      
      Please refer to NVIDIA DALI installation guide for instructions:
      https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html
      ###########################################################################################
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


~~~

**Comment by DarkenHunter** [comment]
@TOMMYWHY How did you solve this having the same issue

**Comment by JanuszL** [comment]
Hi @DarkenHunter,

I see that you are using the Windows platform. Unfortunately, DALI doesn't support it, which is why you receive the generic placeholder package.
You can try using [WSL with CUDA](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) instead.
