### ISSUE TITLE
"DALI in action" example in README.rst and NVIDIA website has a few issues

### ISSUE THREAD

**Issue by 99991** [NVIDIA/DALI#4267]
The "DALI in action" example in the README and on the [NVIDIA website](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/) has a few issues.

* The strings `'label’`, `'Reader’` and `'label’` are incorrectly terminated with the `’`-symbol instead of single quotes.
* The `shuffle` parameter of the function `fn.readers.file` does not exist. Perhaps it has been deprecated? It is probably called `shuffle_after_epoch` now.
* Mixed indentation (4 spaces and 2 spaces)
* `data_dir` is not defined. There should be an explanation about the expected data format and folder structure.

Also the error messages are not very helpful. For example, once I fixed the issues above, I get:

```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    [get_dali_pipeline(data_dir, (244,244))], ['data', 'label'],
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 1469, in create_pipeline
    pipe_outputs = func(*args, **fn_kwargs)
  File "test.py", line 16, in get_dali_pipeline
    images = fn.resize(images, resize_x=crop_size, resize_y=crop_size)
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/fn.py", line 88, in fn_wrapper
    return op_wrapper(*inputs, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/fn.py", line 80, in op_wrapper
    return op_class(**init_args)(*inputs, **call_args)
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/ops.py", line 621, in __init__
    _add_spec_args(self._schema, self._spec, kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/ops.py", line 398, in _add_spec_args
    converted_value = _type_convert_value(dtype, value)
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/types.py", line 108, in _type_convert_value
    return _known_types[dtype][1](val)
TypeError: float() argument must be a string or a number, not 'tuple'
```

I can not tell if my data format is incorrect, if the example is incorrect or if the library is broken.

A few other error messages I encountered in case someone is searching the GitHub issues for answers like I tried previously:

* Incorrect terminating string quote character (should replace `’` with `'`)

```
    [get_dali_pipeline(data_dir, (244,244))], ['data', 'label’],
                                                                ^
SyntaxError: EOL while scanning string literal
```

* Replace `shuffle` with `shuffle_after_epoch`

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    [get_dali_pipeline(data_dir, (244,244))], ['data', 'label'],
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 1469, in create_pipeline
    pipe_outputs = func(*args, **fn_kwargs)
  File "test.py", line 13, in get_dali_pipeline
    images, labels = fn.readers.file(file_root=data_dir, shuffle=True, name="Reader")
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/fn.py", line 88, in fn_wrapper
    return op_wrapper(*inputs, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/fn.py", line 80, in op_wrapper
    return op_class(**init_args)(*inputs, **call_args)
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/ops.py", line 621, in __init__
    _add_spec_args(self._schema, self._spec, kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/nvidia/dali/ops.py", line 393, in _add_spec_args
    dtype = schema.GetArgumentType(key)
RuntimeError: [/opt/dali/dali/pipeline/operator/op_schema.cc:160] Assert on "HasArgument(name)" failed: Argument "shuffle" is not supported by operator "readers__File".
Stacktrace (39 entries):
[frame 0]: /home/user/.local/lib/python3.8/site-packages/nvidia/dali/libdali.so(+0x84a2f) [0x7f858b0dda2f]
[frame 1]: /home/user/.local/lib/python3.8/site-packages/nvidia/dali/libdali.so(dali::OpSchema::GetArgumentType(std::string const&) const+0x2b4) [0x7f858b1a2dc4]
[frame 2]: /home/user/.local/lib/python3.8/site-packages/nvidia/dali/backend_impl.cpython-38-x86_64-linux-gnu.so(+0xb3fb4) [0x7f8577562fb4]
[frame 3]: /home/user/.local/lib/python3.8/site-packages/nvidia/dali/backend_impl.cpython-38-x86_64-linux-gnu.so(+0xa7c15) [0x7f8577556c15]
[frame 4]: python3(PyCFunction_Call+0x59) [0x5f6929]
[frame 5]: python3(_PyObject_MakeTpCall+0x296) [0x5f74f6]
[frame 6]: python3() [0x50c383]
[frame 7]: python3(_PyEval_EvalFrameDefault+0x5786) [0x570b26]
[frame 8]: python3(_PyFunction_Vectorcall+0x1b6) [0x5f6cd6]
[frame 9]: python3(_PyEval_EvalFrameDefault+0x72d) [0x56bacd]
[frame 10]: python3(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 11]: python3(_PyFunction_Vectorcall+0x393) [0x5f6eb3]
[frame 12]: python3() [0x59ca27]
[frame 13]: python3() [0x5a9a07]
[frame 14]: python3(PyObject_Call+0x25e) [0x5f627e]
[frame 15]: python3(_PyEval_EvalFrameDefault+0x1f35) [0x56d2d5]
[frame 16]: python3(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 17]: python3(_PyFunction_Vectorcall+0x393) [0x5f6eb3]
[frame 18]: python3(PyObject_Call+0x62) [0x5f6082]
[frame 19]: python3(_PyEval_EvalFrameDefault+0x1f35) [0x56d2d5]
[frame 20]: python3(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 21]: python3(_PyFunction_Vectorcall+0x393) [0x5f6eb3]
[frame 22]: python3(_PyEval_EvalFrameDefault+0x187f) [0x56cc1f]
[frame 23]: python3(_PyFunction_Vectorcall+0x1b6) [0x5f6cd6]
[frame 24]: python3(PyObject_Call+0x62) [0x5f6082]
[frame 25]: python3(_PyEval_EvalFrameDefault+0x1f35) [0x56d2d5]
[frame 26]: python3(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 27]: python3(_PyFunction_Vectorcall+0x393) [0x5f6eb3]
[frame 28]: python3(_PyEval_EvalFrameDefault+0x72d) [0x56bacd]
[frame 29]: python3(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 30]: python3(PyEval_EvalCode+0x27) [0x6902a7]
[frame 31]: python3() [0x67f951]
[frame 32]: python3() [0x67f9cf]
[frame 33]: python3() [0x67fa71]
[frame 34]: python3(PyRun_SimpleFileExFlags+0x197) [0x681b97]
[frame 35]: python3(Py_RunMain+0x212) [0x6b9d32]
[frame 36]: python3(Py_BytesMain+0x2d) [0x6ba0bd]
[frame 37]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f858cc5e083]
[frame 38]: python3(_start+0x2e) [0x5fc5fe]
```

* Define `data_dir` and provide expected data format (no idea, I gave up searching after a few minutes)

```
    [get_dali_pipeline(data_dir, (244,244))], ['data', 'label'],
NameError: name 'data_dir' is not defined
```

**Comment by jantonguirao** [comment]
@99991 Thanks for reporting this. I've created a PR that should fix those issues https://github.com/NVIDIA/DALI/pull/4268

**Comment by 99991** [comment]
@jantonguirao Wow, that was fast. With your PR, it worked right away! My only minor nitpick would be that the standard indentation for python is [4 spaces](https://peps.python.org/pep-0008/#indentation) instead of 2 spaces.

In case people are not familiar with Git LFS and environment variables, I'll leave the following shell commands here for reference. They will download the test dataset and the example from the README and run it.

```bash
# Install Git Large File Storage
sudo apt install git-lfs
# Download test dataset
git clone --depth 1 https://github.com/NVIDIA/DALI_extra.git
cd DALI_extra
# Set DALI_EXTRA_PATH environment variable
export DALI_EXTRA_PATH="$(pwd)"
cd ..
# Download README.rst
wget https://raw.githubusercontent.com/NVIDIA/DALI/main/README.rst
# Extract example from README.rst into dali_in_action.py
# In the future, the layout of README.rst might change and break the next line.
# If this happens, simply copy the example into a python file by hand.
sed -n '/DALI in action::/,/Highlights/p' README.rst | sed '1,2d;$d' | sed 's/^  //' > dali_in_action.py
python3 dali_in_action.py
```
