### ISSUE TITLE
Using DALI: NVJPEG error "5" : NVJPEG_STATUS_ALLOCATOR_FAILURE /data/val.rec at index 50758080

### ISSUE THREAD

**Issue by Shan19900305** [NVIDIA/DALI#4295]
set num_threads == 2 ok, but got this error when num_threads == 2 .
code: https://github.com/mlperf/training_results_v0.7/blob/master/NVIDIA/benchmarks/resnet/implementations/mxnet/common/dali.py
system info: https://github.com/mlperf/training_results_v0.7/blob/master/NVIDIA/systems/dgxa100_ngc20.06_mxnet.json
Do i miss some config in dali or nvjpeg?

more detail:
Traceback (most recent call last):
  File "train_imagenet.py", line 196, in <module>
    fit.fit(args, kv, model, initializer, lambda_fnc_dali_get_rec_iter, devs, arg_params, aux_params)
  File "/workspace/image_classification/common/fit.py", line 1262, in fit
    (train, val) = data_loader(args, kv)
  File "/workspace/image_classification/common/dali.py", line 323, in <lambda>
    return lambda args, kv: get_rec_iter(args, trainpipes, valpipes, data_paths, kv)
  File "/workspace/image_classification/common/dali.py", line 354, in get_rec_iter
    dali_val_iter = DALIClassificationIterator(valpipes, worker_val_examples, fill_last_batch = False) if args.data_val else None
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/mxnet.py", line 492, in __init__
    last_batch_padded = last_batch_padded)
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/mxnet.py", line 274, in __init__
    self._first_batch = self.next()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/mxnet.py", line 104, in next
    return self.__next__()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/mxnet.py", line 302, in __next__
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 529, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline: Error in thread 0: [/opt/dali/dali/operators/decoder/nvjpeg/decoupled_api/nvjpeg_decoder_decoupled_api.h:597] NVJPEG error "5" : NVJPEG_STATUS_ALLOCATOR_FAILURE /data/val.rec at index 50758080
Stacktrace (7 entries):

**Comment by JanuszL** [comment]
Hi @Shan19900305,

It probably means that you just run out of GPU memory. The DALI mixed image decoder that uses GPU scales the memory consumption with the number of threads. So if you see this error with n threads try to use less.

**Comment by Shan19900305** [comment]
I see a lot of GPU memory left. Just using 20g memory of A100 40G card.

**Comment by JanuszL** [comment]
The decoder uses also CPU memory, maybe it is it?
Can you try out this standalone example and see if that works https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_recordio.html?
To be honest, I'm not that well familiar with the configuration of the scripts used in the MLPerf, I think the best would be to start from https://github.com/NVIDIA/DeepLearningExamples.

**Comment by Shan19900305** [comment]
ok, i will read the tutorial and try later, thank you a lot.
