### ISSUE TITLE
TypeError: cannot pickle 'nvidia.dali.backend_impl.TensorListCPU' object

### ISSUE THREAD

**Issue by keshavvinayak01** [NVIDIA/DALI#4609]
I have a TensorListCPU that I'm using as my sample source to start a pipeline, with num_workers > 0.

The code looks something like this:

```python3
class PreprocessedCallable:
    def __init__(self, batch_size, samples, type=np.float32):
        self.samples = samples
        self.full_iterations = len(self.samples) // batch_size
        self.last_seen_epoch = None
        self.type = type
    def __call__(self, sample_info):
        # Can try to implement caching here?
        sample_idx = sample_info.idx_in_epoch
        if sample_info.iteration >= self.full_iterations:
            raise StopIteration()
        
        # Samples are shuffled every epoch
        if self.last_seen_epoch != sample_info.epoch_idx:
            self.last_seen_epoch = sample_info.epoch_idx
            self.perm = np.random.permutation([i for i in range(len(self.samples))])
        label = 1
        return np.array(self.samples[self.perm[sample_idx]], self.type), np.array(label,dtype=np.int32), np.array(sample_idx,dtype=np.int32)

class PreprocessedCVoicePipeline(Pipeline):
    def __init__(
        self, batch_size, num_threads, num_workers, device_id,
        prefetch_depth=2, cache_step=-1, samples=[]):
        super(PreprocessedCVoicePipeline, self).__init__(
            batch_size,
            num_threads,
            device_id,
            seed=12,
            prefetch_queue_depth=prefetch_depth,
            py_start_method='spawn',
            py_num_workers=num_workers,
            enable_memory_stats=True
        )
        self.input = PreprocessedCallable(batch_size, samples)

    def define_graph(self):
        audios, labels, _ = fn.external_source(
            source=self.input,num_outputs=3,batch=False,parallel=True,dtype=[types.FLOAT, types.INT32, types.INT32])
        """
        Some other pre-processing steps below 
        ---
        ---
        """
        return audios , labels


# preproc_samples is a dictionary with integer keys mapped to TensorCPU objects (images)
preprocessed_pipe = PreprocessedCVoicePipeline(
        batch_size=args.batch_size,
        num_threads=args.threads,
        num_workers=args.num_workers,
        device_id=types.CPU_ONLY_DEVICE_ID,
        prefetch_depth=args.prefetch_depth,
        cache_step=args.cache_step,
        cached_samples=TensorListCPU(list(preproc_samples.values()))
    )

preprocessed_pipe.build()
preprocessed_iter = DALIClassificationIterator(
    preprocessed_pipe,last_batch_padded=True, last_batch_policy=LastBatchPolicy.PARTIAL, prepare_first_batch=False)

```

This code works well with `py_num_workers` set to 0; but throws the following errors for any value > 0:

```bash
                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                  
  File "pipeline.py", line 173, in <module>                                                                                                                         
    regular_experiment(args, main_logger)                                                                                                                             
  File "pipeline.py", line 97, in cache_experiment                                                                                                                  
    preprocessed_pipe.build()                                                                                                                                             
  File "/home/ashish/Desktop/input-pipeline-experiments/venv/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 822, in build                               
    self.start_py_workers()                                                                                                                                         
  File "/home/ashish/Desktop/input-pipeline-experiments/venv/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 795, in start_py_workers                    
    self._start_py_workers()                                                                                                                                        
  File "/home/ashish/Desktop/input-pipeline-experiments/venv/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 680, in _start_py_workers                   
    self._py_pool = WorkerPool.from_groups(self._parallel_input_callbacks,                                                                                          
  File "/home/ashish/Desktop/input-pipeline-experiments/venv/lib/python3.8/site-packages/nvidia/dali/_multiproc/pool.py", line 623, in from_groups                  
    pool = ProcPool.from_contexts(contexts, num_workers, start_method, py_callback_pickler)                                                                         
  File "/home/ashish/Desktop/input-pipeline-experiments/venv/lib/python3.8/site-packages/nvidia/dali/_multiproc/pool.py", line 367, in from_contexts                
    worker_contexts = create_worker_contexts(mp, contexts, num_workers, callback_pickler)                                                                           
  File "/home/ashish/Desktop/input-pipeline-experiments/venv/lib/python3.8/site-packages/nvidia/dali/_multiproc/pool.py", line 264, in create_worker_contexts       
    source_desc.source = callback_pickler.dumps(source_desc.source)                                                                                                 
  File "/home/ashish/Desktop/input-pipeline-experiments/venv/lib/python3.8/site-packages/nvidia/dali/pickling.py", line 61, in dumps                                
    return self._dumps(obj, **self.dumps_kwargs)                                                                                                                    
  File "/home/ashish/Desktop/input-pipeline-experiments/venv/lib/python3.8/site-packages/nvidia/dali/pickling.py", line 26, in dumps                                
    reducers.DaliCallbackPickler(f, protocol, **kwargs).dump(obj)                                                                                                   
TypeError: cannot pickle 'nvidia.dali.backend_impl.TensorListCPU' object                                                                                            
```

I'm using a TensorListCPU object for multiprocessing because [using Python data structures is a well known](https://github.com/pytorch/pytorch/issues/13246) bad call for multiprocessing workloads. (Memory explosion) 

In case there is no support for using TensorListCPU for multiprocessing, can you provide alternatives for my usecase? Keep in mind that this structure contains tensors of Varying lengths which is I won't be able to use stacked Torch Tensors or numpy arrays(non-object).

Hope my doubt was clear, thanks!

**Comment by stiepan** [comment]
Hi @keshavvinayak01 

Thanks for reaching out.

The TensorList is not serializable, so it won't work with parallel external source in `spawn` mode. I have a couple of ideas to work around it, that depend on the details of your use case.

1. How about making the preporcessing of data part of the callback? Maybe it makes sense not to preprocess the data in advance and store them all in a single tensor list but load and preprocess samples in the callback? Could it benefit from the fact that the samples are computed in multiple workers in parallel?

2. If not, maybe using the paralell external source is unnecessary? After all, it seems that all there is to do for the external source is to feed data from the memory. So `parallel=False` should not be much of a constraint. Especially if you use `no_copy=True` with the external source operator to avoid copying the samples when feeding them into DALI pipeline.

3. Following on the observation from the second point, you may consider using parallel external source in `batch=True` mode with just a single worker and not be concerned about copying the data just for a one worker. In that case the little logic the callback has to handle, such as shuffling between the epochs, will be done in a separate process to make sure it does not impede the perf of the pipeline.

4. You could try using `py_start_method=fork` - the serialization issues will go away. However, it is brittle in a sense that once you touch CUDA, you cannot fork the process. In particular, there are the odds that other frameworks may initialize CUDA when you import them.

5. As a last resort, you could explicitly pass the samples through the `multiprocessing.shared_memory` to avoid copies. I prototyped a snippet that does that, but I did not test it, simply run it.
```
from multiprocessing import shared_memory as shm
import numpy as np
from nvidia.dali.pipeline import pipeline_def
from nvidia.dali import fn


class PreprocessedCallable:
    def __init__(self, samples, type):
        self.samples = samples
        assert len(samples) > 0
        self.type = type
        self.shm_buffer = None
        self.shm_buffer_name = None

    def __getstate__(self):
        shapes = [sample.shape for sample in self.samples]
        nbytes = [sample.nbytes for sample in self.samples]
        # dictionary that will be pickled and passed to worker processes
        members = self.__dict__.copy()
        # the samples won't be serialized
        del members["samples"]
        members["shapes"] = shapes
        members["nbytes"] = nbytes
        total_nbytes = sum(nbytes)
        self.shm_buffer = shm.SharedMemory(create=True, size=total_nbytes)
        self.shm_buffer_name = self.shm_buffer.name
        # pass the name of the shared memory chunk
        members["shm_buffer_name"] = self.shm_buffer_name
        mem_view = self.shm_buffer.buf
        offset = 0
        # copy samples into the shared memory
        for sample in self.samples:
            sample_nbytes = sample.nbytes
            buffer = mem_view[offset:(offset + sample_nbytes)]
            assert sample.dtype == self.type
            shared_array = np.ndarray(
                sample.shape, dtype=sample.dtype, buffer=buffer)
            shared_array.ravel()[:] = sample.ravel()[:]
            offset += sample_nbytes
        return members

    def __setstate__(self, state):
        nbytes, shapes = state.pop("nbytes"), state.pop("shapes")
        self.__dict__.update(state)
        self.shm_buffer = shm.SharedMemory(self.shm_buffer_name)
        mem_view = self.shm_buffer.buf
        self.samples = []
        offset = 0
        assert len(nbytes) == len(shapes)
        for sample_nbytes, sample_shape in zip(nbytes, shapes):
            buffer = mem_view[offset:(offset + sample_nbytes)]
            sample = np.ndarray(
                sample_shape, dtype=self.type, buffer=buffer)
            self.samples.append(sample)
            offset += sample_nbytes

    def __call__(self, sample_info):
        sample_idx = sample_info.idx_in_epoch
        #FIXME getting around the end-of-epoch and shuffling logic for simplicity
        # of the presentation
        sample_idx %= len(self.samples)
        return self.samples[sample_idx]

    def unlink(self):
        if self.shm_buffer is not None:
            self.shm_buffer.close()
            self.shm_buffer.unlink()



@pipeline_def(py_start_method="spawn", py_num_workers=4)
def pipeline(source):
    samples = fn.external_source(
        source=source,
        batch=False, parallel=True)
    return samples


def preprocess_data():
    return [np.full((1024, 1024, 256), i, dtype=np.float32) for i in range(2)]

if __name__ == '__main__':
    preprocessed = preprocess_data()
    source = PreprocessedCallable(preprocessed, np.float32)
    pipe = pipeline(source, batch_size=4, num_threads=4, device_id=0)
    pipe.build()
    out, = pipe.run()
    print(out)
    del pipe
    source.unlink()
```

**Comment by keshavvinayak01** [comment]
Thanks for the quick response.

I used the shared memory buffer as you mentioned, and it works!

**Comment by keshavvinayak01** [comment]
Hi, one last problem with the above approach that you suggested. My memory usage is doubled. I can see the output of `free -tmh`, that the `shared` section is filled with the preprocessed data, however the space `preprocessed` object is not freed. I tried calling `del` followed by `gc.collect()` but it doesn't free that memory. Is there are reference by other workers to that object that I'm unaware of?

**Comment by keshavvinayak01** [comment]
For others who might end up using this code, 
The code written by @stiepan causes allocation in both the shared memory buffer as well as the anonymous memory. To prevent the latter allocation, I called the pre-processing function (per item) within the buffer allocation loop of the `__getstate__` function, which does not lead to the additional allocations.

Thanks again!

**Comment by stiepan** [comment]
Hi @keshavvinayak01,

Thanks for letting us know. From the comment alone, I cannot pin-point what is the cause of extra allocation. Would you mind sharing a snippet here for us and future readers? 

Thanks!

**Comment by keshavvinayak01** [comment]
Sure, I've abstracted out some private details of implementation, but broadly the code looks like this : 

```python3
# Followed from https://github.com/NVIDIA/DALI/issues/4609
class SharedExternalCallable:
    def __init__(self, batch_size, samples, buffer_size, partial_processing_pipe, type=np.float32):
        self.samples = samples
        assert len(samples) > 0
        preprocessing_pipe = partial_processing_pipe(
            args.threads,
            types.CPU_ONLY_DEVICE_ID,
            samples=samples
        )
        preprocessing_pipe.build()
        self.preprop_iter = DALIGenericIterator(preprocessing_pipe, prepare_first_batch=False, output_map=['data', 'label', 'index'])
        
        self.type = type
        self.batch_size = batch_size
        self.full_iterations = len(self.samples) // batch_size
        self.last_seen_epoch = None
        self.shm_buffer = None
        self.shm_buffer_name = None

    def __getstate__(self):
        """
        Same as above
        """
        offset = 0

        dtype = None
        fill_size = 0
        for i, data in enumerate(self.preprop_iter):
            index = data[0]['index'][0][0].item()
            sample = data[0]['data'].squeeze(0)
            if not dtype:
                dtype = np.array(sample).dtype
            sample_nbytes = sample.nelement()*sample.element_size()
            
            if self.fill_size + sample_nbytes >= self.buffer_size:
                break

            shapes.append(sample.shape)
            nbytes.append(sample_nbytes)
            buffer = mem_view[offset:(offset + sample_nbytes)]
            shared_array = np.ndarray(
                sample.shape, dtype=dtype, buffer=buffer)
            shared_array.ravel()[:] = sample.ravel()[:]
            offset += sample_nbytes
            
            self.fill_size += sample_nbytes
        del members['preprop_iter']
        members["shapes"] = shapes
        members["nbytes"] = nbytes
        members["dtype"] = dtype
        return members
    
    # this will be run by the workers on a set-up
    def __setstate__(self, state):
        nbytes, shapes, dtype = state.pop("nbytes"), state.pop("shapes"), state.pop("dtype")
        """
        Same as above
        """
        self.update_iter_size()

    def __call__(self, sample_info):
        """
        Mostly the same as I posted originally
        """

    def unlink(self):
        if self.shm_buffer is not None:
            self.shm_buffer.close()
            self.shm_buffer.unlink()

    def update_iter_size(self):
        # updated to only load samples that were pushed into the updated preprocessed list.
        self.full_iterations = len(self.samples) // self.batch_size

```

only the  `__getstate__` function is modified such that it loads preprocessed samples from another pipeline (batch_size=1), and stores them into the shared memory buffer.

Hope this helps!
