### ISSUE TITLE
Error when executing CPU operator readers__Numpy, instance name: "ReaderY", encountered:

### ISSUE THREAD

**Issue by shanmukh05** [NVIDIA/DALI#4685]
I am trying to train [nnUNet ](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Segmentation/nnUNet). I got the following error:

```
Traceback (most recent call last):
  File "../main.py", line 129, in <module>
    main()
  File "../main.py", line 111, in main
    trainer.fit(model, datamodule=data_module)
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 195, in run
    self.on_run_start(*args, **kwargs)
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 211, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1812, in reset_train_dataloader
    self.train_dataloader = self._data_connector._request_dataloader(RunningStage.TRAINING)
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 453, in _request_dataloader
    dataloader = source.dataloader()
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 530, in dataloader
    return method()
  File "/data1/students/sainath/nnUNet/data_loading/data_module.py", line 78, in train_dataloader
    return fetch_dali_loader(self.train_imgs, self.train_lbls, self.train_mgmt_lbls, self.args.batch_size, "train", **self.kwargs)
  File "/data1/students/sainath/nnUNet/data_loading/dali_loader.py", line 279, in fetch_dali_loader
    return LightningWrapper(
  File "/data1/students/sainath/nnUNet/data_loading/dali_loader.py", line 236, in __init__
    super().__init__(pipe, **kwargs)
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py", line 183, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py", line 194, in __next__
    outputs = self._get_outputs()
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/plugin/base_iterator.py", line 255, in _get_outputs
    outputs.append(p.share_outputs())
  File "/data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 863, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing CPU operator readers__Numpy, instance name: "ReaderY", encountered:
[/opt/dali/dali/util/std_file.cc:29] Assert on "fp_ != nullptr" failed: Could not open file /../data/11_3d/BraTS2021_00652_y.npy: No such file or directory
Stacktrace (9 entries):
[frame 0]: /data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/libdali.so(+0x7b73e) [0x7f9a30a7b73e]
[frame 1]: /data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/libdali.so(+0x1a981a) [0x7f9a30ba981a]
[frame 2]: /data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/libdali.so(dali::FileStream::Open(std::string const&, bool, bool)+0x11d) [0x7f9a30b96aad]
[frame 3]: /data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/libdali_operators.so(+0x26c2eb2) [0x7f9a33cc2eb2]
[frame 4]: /data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/libdali_operators.so(+0x27bf99e) [0x7f9a33dbf99e]
[frame 5]: /data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/libdali_operators.so(+0x27c0feb) [0x7f9a33dc0feb]
[frame 6]: /data1/students/anaconda3/envs/students/lib/python3.8/site-packages/nvidia/dali/libdali_operators.so(+0x2fd270f) [0x7f9a345d270f]
[frame 7]: /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7f9af6494b43]
[frame 8]: /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7f9af6526a00]

Current pipeline object is no longer valid.
```

It is giving No such file or directory error. I've checked all the folder structure and there are no issues in them. Also the filepath should be `../data/11_3d/BraTS2021_00652_y.npy`, but in the error it is showing as `/../data/11_3d/BraTS2021_00652_y.npy`.

This file has complete [Data Loader](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/nnUNet/data_loading/dali_loader.py) Code
I followed all the installation steps mentioned in nnUNet repo.

Please help me with this.
Thanks

**Comment by JanuszL** [comment]
Hi @shanmukh05,

Thank you for reaching out. Can you double-check if you set the launch parameters of the training script correctly (for example if [data](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/nnUNet/utils/args.py#L47) parameter is set correctly)?
If everything seems fine I would reach out to the maintainers of this particular model to learn more about running it. From the DALI point of view, I don't see anything incorrect there. The overall 10,000 foot view is:
- DALI consists from kernels (low level processing operations), operators (interprets arguments, configures kernels and launches them), pipeline (execution engine that builds processing graph, rans operators, manages memory).

**Comment by JanuszL** [comment]
Closing as stalled.
