### ISSUE TITLE
Is DaliGenericIterator compatible with PyTorch 2.0?    [cuFile error (5033): NVFS driver initialization error]

### ISSUE THREAD

**Issue by omar-valerio** [NVIDIA/DALI#4771]
Hello DALI Team,

I am running my DALI pipeline in a system with a different GPU. Instead of using my already existing environment I decided to test if my code will work with PyTorch 2.0.  I went through the docs but I couldn't find any information regarding the PyTorch plugin in DALI compatibility.  I run a test and I got the following error message.  
```
 missing cuda symbols while dynamic loading
 cuFile initialization failed
Traceback (most recent call last):
  File "/gpfs/soma_fs/scratch/valerio/ibs/bottleneck/train_model_with_dali.py", line 66, in <module>
    main()
  File "/gpfs/soma_fs/scratch/valerio/ibs/bottleneck/train_model_with_dali.py", line 61, in main
    trainer.fit(model)
  File "/gpfs/soma_fs/home/valerio/anaconda3/envs/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/gpfs/soma_fs/home/valerio/anaconda3/envs/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/gpfs/soma_fs/home/valerio/anaconda3/envs/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/gpfs/soma_fs/home/valerio/anaconda3/envs/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 896, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "/gpfs/soma_fs/home/valerio/anaconda3/envs/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 83, in _call_setup_hook
    _call_lightning_module_hook(trainer, "setup", stage=fn)
  File "/gpfs/soma_fs/home/valerio/anaconda3/envs/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 142, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/gpfs/soma_fs/scratch/valerio/ibs/bottleneck/bottleneck_dali.py", line 163, in setup
    self.train_loader = DALIGenericIterator(
  File "/gpfs/soma_fs/home/valerio/anaconda3/envs/lightning/lib/python3.10/site-packages/nvidia/dali/plugin/pytorch.py", line 181, in __init__
    _DaliBaseIterator.__init__(self,
  File "/gpfs/soma_fs/home/valerio/anaconda3/envs/lightning/lib/python3.10/site-packages/nvidia/dali/plugin/base_iterator.py", line 199, in __init__
    p.build()
  File "/gpfs/soma_fs/home/valerio/anaconda3/envs/lightning/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 820, in build
    self._pipe.Build(self._generate_build_args())
RuntimeError: Critical error when building pipeline:
Error when constructing operator: readers__Numpy, instance name: "VtDendReader", encountered:
cuFile error (5033): NVFS driver initialization error
Current pipeline object is no longer valid.
```

Here is some additional information on the CUDA, NVIDIA.DALI & Torch versions.

```
torch version: 2.0.0
nvidia.dali version: 1.25.0dev.20230331

nvidia-smi
Wed Apr  5 14:32:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 6000     On   | 00000000:06:00.0 Off |                    0 |
| N/A   27C    P8    21W / 250W |      0MiB / 22698MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 6000     On   | 00000000:2F:00.0 Off |                    0 |
| N/A   27C    P8    22W / 250W |      0MiB / 22698MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by JanuszL** [comment]
Hi @omar-valerio,

Thank you for reaching out. It seems that the error originates from [GPU Direct Storage](https://docs.nvidia.com/gpudirect-storage/overview-guide/index.html):
```
RuntimeError: Critical error when building pipeline:
Error when constructing operator: readers__Numpy, instance name: "VtDendReader", encountered:
cuFile error (5033): NVFS driver initialization error
Current pipeline object is no longer valid.
```
Please check if your system is capable of running GDS. In the meantime you can [DALI PyTorch examples](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/index.html) to see how it works with 2.0 (as far as I know there is no reason it should not).

**Comment by ovalerio** [comment]
Hello @JanuszL,

Thank you. The card supports GDS but apparently still need some extra drivers which unfortunately cannot be installed because of incompatible OS.  I was wondering if it is possible to set the `force_compat_mode` only for debugging.

```
./gdscheck -p
 ============
 ENVIRONMENT:
 ============
 =====================
 DRIVER CONFIGURATION:
 =====================
 NVMe               : Unsupported
 NVMeOF             : Unsupported
 SCSI               : Unsupported
 ScaleFlux CSD      : Unsupported
 NVMesh             : Unsupported
 DDN EXAScaler      : Unsupported
 IBM Spectrum Scale : Unsupported
 NFS                : Unsupported
 BeeGFS             : Unsupported
 WekaFS             : Unsupported
 Userspace RDMA     : Unsupported
 --Mellanox PeerDirect : Disabled
 --rdma library        : Not Loaded (libcufile_rdma.so)
 --rdma devices        : Not configured
 --rdma_device_status  : Up: 0 Down: 0
 =====================
 CUFILE CONFIGURATION:
 =====================
 properties.use_compat_mode : true
 properties.force_compat_mode : false
 properties.gds_rdma_write_support : true
 properties.use_poll_mode : false
 properties.poll_mode_max_size_kb : 4
 properties.max_batch_io_size : 128
 properties.max_batch_io_timeout_msecs : 5
 properties.max_direct_io_size_kb : 16384
 properties.max_device_cache_size_kb : 131072
 properties.max_device_pinned_mem_size_kb : 33554432
 properties.posix_pool_slab_size_kb : 4 1024 16384 
 properties.posix_pool_slab_count : 128 64 32 
 properties.rdma_peer_affinity_policy : RoundRobin
 properties.rdma_dynamic_routing : 0
 fs.generic.posix_unaligned_writes : false
 fs.lustre.posix_gds_min_kb: 0
 fs.beegfs.posix_gds_min_kb: 0
 fs.weka.rdma_write_support: false
 fs.gpfs.gds_write_support: false
 profile.nvtx : false
 profile.cufile_stats : 0
 miscellaneous.api_check_aggressive : false
 execution.max_io_threads : 0
 execution.max_io_queue_depth : 128
 execution.parallel_io : false
 execution.min_io_threshold_size_kb : 1024
 execution.max_request_parallelism : 0
 =========
 GPU INFO:
 =========
 GPU index 0 Quadro RTX 3000 bar:1 bar size (MiB):256 supports GDS, IOMMU State: Disabled
 ==============
 PLATFORM INFO:
 ==============
 IOMMU: disabled
 Platform verification succeeded
```

**Comment by omar-valerio** [comment]
Thanks @JanuszL
