### ISSUE TITLE
How to use DALI to load images without label

### ISSUE THREAD

**Issue by llx-08** [NVIDIA/DALI#4788]
Hi

I see that many examples of loading images need to read image and label, I want to use DALI to read images without label.

I tried the following code and got error:

``` python
class DALIPipeline(Pipeline):

    def __init__(self, batch_size, num_threads, device_id):

        super(DALIPipeline, self).__init__(batch_size, num_threads, device_id)

        self.img_list = glob.glob('/llx/test2017/*.jpg')

        dummy_label = [0] * len(self.img_list)

        df = pd.DataFrame({'data': self.img_list, 'label': dummy_label})

        df.to_csv('dali.txt', header=False, index=False, sep=' ')

        self.input = ops.FileReader(file_root='.', file_list='dali.txt')

        self.decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)

        self.resize = ops.Resize(device="gpu",
                                 image_type=types.RGB,
                                 resize_x=224., resize_y=224.)

        self.cmn = ops.CropMirrorNormalize(device="gpu",
                                           output_dtype=types.FLOAT,
                                           mirror=1,
                                           image_type=types.RGB,
                                           mean=[128., 128., 128.],
                                           std=[1., 1., 1.])

    def define_graph(self):
        images, labels = self.input(name="Reader")e
        images = self.decode(images)
        images = self.resize(images)
        output = self.cmn(images)
        return output


class DALICustomIterator(DALIGenericIterator):
    def __init__(self, pipelines, output_map, size, auto_reset=False, fill_last_batch=True, dynamic_shape=False,
                 last_batch_padded=False):
        super(DALICustomIterator, self).__init__(pipelines, output_map, size, auto_reset, fill_last_batch,
                                                 dynamic_shape, last_batch_padded)

    def __len__(self):
        return int(self._size / self.batch_size) + 1

    def __next__(self):
        if self._first_batch is not None:
            batch = self._first_batch
            self._first_batch = None
            return batch
        feed = super().__next__()
        data = feed[0]['data']
        return data


def DALIDataLoader(batch_size):
    num_gpus = 1
    pipes = [DALIPipeline(batch_size=batch_size, num_threads=2, device_id=device_id) for device_id in range(num_gpus)]

    pipes[0].build()
    dali_iter = DALICustomIterator(pipes, ['data'], pipes[0].epoch_size("Reader"), auto_reset=True)
    return dali_iter


data_loader = DALIDataLoader(batch_size=64)
start_time = time.time()
for image in tqdm(data_loader):
    # image is already on GPU
    image = image
    pass
dali_time = time.time() - start_time
```

Error:
```
/workspace/DALI/benchmark/dali_dataloader.py:23: DeprecationWarning: The argument ``image_type`` is no longer used and will be removed in a future release.
  self.resize = ops.Resize(device="gpu",
/workspace/DALI/benchmark/dali_dataloader.py:26: DeprecationWarning: The argument ``output_dtype`` is a deprecated alias for ``dtype``. Use ``dtype`` instead.
  self.cmn = ops.CropMirrorNormalize(device="gpu",
/workspace/DALI/benchmark/dali_dataloader.py:26: DeprecationWarning: The argument ``image_type`` is no longer used and will be removed in a future release.
  self.cmn = ops.CropMirrorNormalize(device="gpu",
/usr/local/lib/python3.8/dist-packages/nvidia/dali/ops.py:653: DeprecationWarning: WARNING: `file_reader` is now deprecated. Use `readers.file` instead.
In DALI 1.0 all readers were moved into a dedicated :mod:`~nvidia.dali.fn.readers`
submodule and renamed to follow a common pattern. This is a placeholder operator with identical
functionality to allow for backward compatibility.
  op_instances.append(_OperatorInstance(input_set, self, **kwargs))
/usr/local/lib/python3.8/dist-packages/nvidia/dali/ops.py:653: DeprecationWarning: WARNING: `image_decoder` is now deprecated. Use `decoders.image` instead.
In DALI 1.0 all decoders were moved into a dedicated :mod:`~nvidia.dali.fn.decoders`
submodule and renamed to follow a common pattern. This is a placeholder operator with identical
functionality to allow for backward compatibility.
  op_instances.append(_OperatorInstance(input_set, self, **kwargs))
/usr/local/lib/python3.8/dist-packages/nvidia/dali/plugin/pytorch.py:181: Warning: Please do not use `fill_last_batch` and use `last_batch_policy`                            instead.
  _DaliBaseIterator.__init__(self,


Traceback (most recent call last):
  File "/workspace/DALI/benchmark/dali_dataloader.py", line 69, in <module>
    data_loader = DALIDataLoader(batch_size=64)
  File "/workspace/DALI/benchmark/dali_dataloader.py", line 65, in DALIDataLoader
    dali_iter = DALICustomIterator(pipes, ['data'], pipes[0].epoch_size("Reader"), auto_reset=True)
  File "/workspace/DALI/benchmark/dali_dataloader.py", line 44, in __init__
    super(DALICustomIterator, self).__init__(pipelines, output_map, size, auto_reset, fill_last_batch,
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/plugin/pytorch.py", line 181, in __init__
    _DaliBaseIterator.__init__(self,
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/plugin/base_iterator.py", line 184, in __init__
    assert not reader_name or (reader_name and self._size < 0), \
AssertionError: When reader_name is provided, size should not be set

Process finished with exit code 1
```
Please tell me how to fix this error `AssertionError: When reader_name is provided, size should not be set`
Thank you

**Comment by JanuszL** [comment]
Hi @llx-08,

Thank you for reaching out.
I think it would be best to start with [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-various-readers.html).
If you don't want to return labels modify the mentioned example:
```
def common_pipeline(jpegs):
    images = fn.decoders.image(jpegs, device='mixed')
    images = fn.resize(
        images,
        resize_shorter=fn.random.uniform(range=(256, 480)),
        interp_type=types.INTERP_LINEAR)
    images = fn.crop_mirror_normalize(
        images,
        crop_pos_x=fn.random.uniform(range=(0.0, 1.0)),
        crop_pos_y=fn.random.uniform(range=(0.0, 1.0)),
        dtype=types.FLOAT,
        crop=(227, 227),
        mean=[128., 128., 128.],
        std=[1., 1., 1.])
    return images

@pipeline_def
def file_reader_pipeline(num_gpus):
    jpegs = fn.readers.file(
        file_root=image_dir,
        random_shuffle=True,
        shard_id=Pipeline.current().device_id,
        num_shards=num_gpus,
        name='Reader')

    return common_pipeline(jpegs)

(...)
dali_iter = DALIGenericIterator(pipes, ['data'], reader_name='Reader')
```
Also, you don't have to use `file_list`, but you can pass filenames directly as a dictionary using [`files` argument](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.file.html).

**Comment by awolant** [comment]
Hi, thanks for the question.

To read images from a list of paths without labels you can use `files` argument of file reader. This way you do not need to save a temporary file for the file list, `files` accepts for example a Python list of paths. When you use `files` you do not need to provide a label. It will be assigned as sequential 0-based index but you can just ignore it.

The error `AssertionError: When reader_name is provided, size should not be set` that you are seeing is caused by the fact that you are providing a value for `size` parameter (third argument of `DALICustomIterator`). You can skip it.

Hope that helps

**Comment by llx-08** [comment]
Thank you very much @JanuszL @awolant , I created a dummy label file, and it solved my problem.

I also tried the code below, and it runs successfully
> Hi @llx-08,
> 
> Thank you for reaching out. I think it would be best to start with [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-various-readers.html). If you don't want to return labels modify the mentioned example:
> 
> ```
> def common_pipeline(jpegs):
>     images = fn.decoders.image(jpegs, device='mixed')
>     images = fn.resize(
>         images,
>         resize_shorter=fn.random.uniform(range=(256, 480)),
>         interp_type=types.INTERP_LINEAR)
>     images = fn.crop_mirror_normalize(
>         images,
>         crop_pos_x=fn.random.uniform(range=(0.0, 1.0)),
>         crop_pos_y=fn.random.uniform(range=(0.0, 1.0)),
>         dtype=types.FLOAT,
>         crop=(227, 227),
>         mean=[128., 128., 128.],
>         std=[1., 1., 1.])
>     return images
> 
> @pipeline_def
> def file_reader_pipeline(num_gpus):
>     jpegs = fn.readers.file(
>         file_root=image_dir,
>         random_shuffle=True,
>         shard_id=Pipeline.current().device_id,
>         num_shards=num_gpus,
>         name='Reader')
> 
>     return common_pipeline(jpegs)
> 
> (...)
> dali_iter = DALIGenericIterator(pipes, ['data'], reader_name='Reader')
> ```
> 
> Also, you don't have to use `file_list`, but you can pass filenames directly as a dictionary using [`files` argument](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.file.html).
