### ISSUE TITLE
NVML Error on WSL2

### ISSUE THREAD

**Issue by FriendChi** [NVIDIA/DALI#4964]
### Version

nvidia-dali-cuda120     1.28.0

### Describe the bug.

Traceback (most recent call last):
  File "/mnt/g/postgraduate_studyfile/Ultra-Fast-Lane-Detection-v2-master/train.py", line 88, in <module>
    train_loader = get_train_loader(cfg)
  File "/mnt/g/postgraduate_studyfile/Ultra-Fast-Lane-Detection-v2-master/utils/common.py", line 196, in get_train_loader
    train_loader = TrainCollect(cfg.batch_size, 4, cfg.data_root, os.path.join(cfg.data_root, 'train_gt.txt'), get_rank(), get_world_size(), 
  File "/mnt/g/postgraduate_studyfile/Ultra-Fast-Lane-Detection-v2-master/data/dali_data.py", line 229, in __init__
    self.pii = DALIGenericIterator(pipe, output_map = ['images', 'seg_images', 'points'], last_batch_padded=True, last_batch_policy=LastBatchPolicy.PARTIAL)
  File "/home/cyh/anaconda3/envs/UDL/lib/python3.9/site-packages/nvidia/dali/plugin/pytorch.py", line 181, in __init__
    _DaliBaseIterator.__init__(self,
  File "/home/cyh/anaconda3/envs/UDL/lib/python3.9/site-packages/nvidia/dali/plugin/base_iterator.py", line 198, in __init__
    p.build()
  File "/home/cyh/anaconda3/envs/UDL/lib/python3.9/site-packages/nvidia/dali/pipeline.py", line 820, in build
    self._pipe.Build(self._generate_build_args())
RuntimeError: Critical error when building pipeline:
Error when constructing operator: decoders__Image, instance name: "__Image_4", encountered:
Error in thread 0: nvml error (3): The nvml requested operation is not available on target device
Current pipeline object is no longer valid.

### Minimum reproducible example

```shell
Here's where the problem occurs

# from data.constant import culane_row_anchor, culane_col_anchor
class TrainCollect:
    def __init__(self, batch_size, num_threads, data_root, list_path, shard_id, num_shards, row_anchor, col_anchor, train_width, train_height, num_cell_row, num_cell_col,
    dataset_name, top_crop):
        eii = LaneExternalIterator(data_root, list_path, batch_size=batch_size, shard_id=shard_id, num_shards=num_shards, dataset_name = dataset_name)

        if dataset_name == 'CULane':
            self.original_image_width = 1640
            self.original_image_height = 590
        elif dataset_name == 'Tusimple':
            self.original_image_width = 1280
            self.original_image_height = 720
        elif dataset_name == 'CurveLanes':
            self.original_image_width = 2560
            self.original_image_height = 1440

        if dataset_name == 'CurveLanes':
            pipe = ExternalSourceTrainPipeline(batch_size, num_threads, shard_id, eii, train_width, train_height,top_crop, normalize_image_scale = True, nscale_w = 2560, nscale_h = 1440)
        else:
            pipe = ExternalSourceTrainPipeline(batch_size, num_threads, shard_id, eii, train_width, train_height,top_crop)
        self.pii = DALIGenericIterator(pipe, output_map = ['images', 'seg_images', 'points'], last_batch_padded=True, last_batch_policy=LastBatchPolicy.PARTIAL)
        self.eii_n = eii.n
        self.batch_size = batch_size

        self.interp_loc_row = torch.tensor(row_anchor, dtype=torch.float32).cuda() * self.original_image_height
        self.interp_loc_col = torch.tensor(col_anchor, dtype=torch.float32).cuda() * self.original_image_width
        self.num_cell_row = num_cell_row
        self.num_cell_col = num_cell_col

    def __iter__(self):
        return self

    def __next__(self):
        data = next(self.pii)
        images = data[0]['images']
        seg_images = data[0]['seg_images']
        points = data[0]['points']
        points_row = my_interp.run(points, self.interp_loc_row, 0)
        points_row_extend = self._extend(points_row[:,:,:,0]).transpose(1,2)
        labels_row = (points_row_extend / self.original_image_width * (self.num_cell_row - 1)).long()
        labels_row[points_row_extend < 0] = -1
        labels_row[points_row_extend > self.original_image_width] = -1
        labels_row[labels_row < 0] = -1
        labels_row[labels_row > (self.num_cell_row - 1)] = -1

        points_col = my_interp.run(points, self.interp_loc_col, 1)
        points_col = points_col[:,:,:,1].transpose(1,2)
        labels_col = (points_col / self.original_image_height * (self.num_cell_col - 1)).long()
        labels_col[points_col < 0] = -1
        labels_col[points_col > self.original_image_height] = -1
        
        labels_col[labels_col < 0] = -1
        labels_col[labels_col > (self.num_cell_col - 1)] = -1

        labels_row_float = points_row_extend / self.original_image_width
        labels_row_float[labels_row_float<0] = -1
        labels_row_float[labels_row_float>1] = -1

        labels_col_float = points_col / self.original_image_height
        labels_col_float[labels_col_float<0] = -1
        labels_col_float[labels_col_float>1] = -1

        return {'images':images, 'seg_images':seg_images, 'labels_row':labels_row, 'labels_col':labels_col, 'labels_row_float':labels_row_float, 'labels_col_float':labels_col_float}
    
    def __len__(self):
        return int((self.eii_n + self.batch_size - 1) / self.batch_size)
    def reset(self):
        self.pii.reset()
    next = __next__

    def _extend(self, coords):
        # coords : n x num_lane x num_cls
        n, num_lanes, num_cls = coords.shape
        coords_np = coords.cpu().numpy()
        coords_axis = np.arange(num_cls)
        fitted_coords = coords.clone()
        for i in range(n):
            for j in range(num_lanes):
                lane = coords_np[i,j]
                if lane[-1] > 0:
                    continue

                valid = lane > 0
                num_valid_pts = np.sum(valid)
                if num_valid_pts < 6:
                    continue
                p = np.polyfit(coords_axis[valid][num_valid_pts//2:], lane[valid][num_valid_pts//2:], deg = 1)   
                start_point = coords_axis[valid][num_valid_pts//2]
                fitted_lane = np.polyval(p, np.arange(start_point, num_cls))

                
                fitted_coords[i,j,start_point:] = torch.tensor(fitted_lane, device = coords.device)
        return fitted_coords
    def _extend_col(self, coords):
        pass
```

### Relevant log output

```shell
Ultra-Fast-Lane-Detection-v2 is a full-fledged project, I just replaced the project's feature extraction network, nothing else was modified, you can find the code for Ultra-Fast-Lane-Detection-v2 on github. But the problem is definitely with me.
```

### Other/Misc.

NVIDIA-SMI 525.104      Driver Version: 528.79       CUDA Version: 12.0

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by klecki** [comment]
Hi @FriendChi, I checked the source, and DALI_DISABLE_NVML expects numeric value, can you try:
```
export DALI_DISABLE_NVML=1
```

**Comment by FriendChi** [comment]
Excuse me, thanks for your help, I originally thought these two instructions meant the same

**Comment by klecki** [comment]
No problem. Please let us know if this helps with the issue or if it needs further attention.

**Comment by Minnchong** [comment]
@klecki @JanuszL @FriendChi 
I also encountered this problem, but I'm not sure where to add this parameter：export DALI_DISABLE_NVML=1
