### ISSUE TITLE
Video is too large in at least one dimension. 

### ISSUE THREAD

**Issue by navinelahi** [NVIDIA/DALI#5051]
### Describe the question.

Encountered the following error:

> /opt/dali/dali/operators/reader/nvdecoder/nvdecoder.cc:202: Unable to decode file /home/n/filmictech/filmictech-devtest-main-DXP-0-99/DXP/0-99/out.mp4
Traceback (most recent call last):
  File "/home/n/filmictech/dali_video.py", line 72, in <module>
    (video,) = pipe.run()
  File "/home/n/anaconda3/envs/filmictech/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 1113, in run
    return self.outputs()
  File "/home/n/anaconda3/envs/filmictech/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 956, in outputs
    return self._outputs()
  File "/home/n/anaconda3/envs/filmictech/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 1040, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
Error when executing GPU operator readers__VideoResize encountered:
[/opt/dali/dali/operators/reader/nvdecoder/cuvideodecoder.cc:226] Video is too large in at least one dimension.

What might be the possible reasons for this issue? What are the things I should look out for in my considerations? Thank you.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @navinelahi,

Thank you for reaching out. NVIDIA Video Decoder has limitations (depending on the codec) regarding the maximum width, height, and the number of macroblocks (product of the width and height). In your case, your video resolution may be too high for the GPU video decoder to handle.
Can you check what resolution it has? Also, can you tell us what is the GPU model you have on your computer?
