### ISSUE TITLE
random_resized_crop does not support different image sizes

### ISSUE THREAD

**Issue by CoinCheung** [NVIDIA/DALI#5164]
### Version

nvidia_dali_cuda110-1.29.0-9289311-py3-none-manylinux2014_x86_64.whl

### Describe the bug.

When using external source, and image sizes are various training would be failed, and no explicit error messages are printed.

### Minimum reproducible example

```python
class ExternalInputIterator(object):

    def __init__(self, file_list, rank, world_size, global_batchsize, n_epoches):
        self.rank, self.world_size = rank, world_size
        self.global_batchsize = global_batchsize
        self.batchsize = global_batchsize // world_size
        self.file_list = file_list
        self.n_epoches = n_epoches

        with open(self.file_list, 'r') as fr:
            lines = fr.read().splitlines()#[:1500]
        self.files = lines
        self.n_samples = len(lines)

        print('load indices')
        one_ep_inds = list(range(self.n_samples))
        self.indices = []
        for ep in range(self.n_epoches):
            random.Random(321 + ep).shuffle(one_ep_inds)
            self.indices += one_ep_inds
        n_inds = len(self.indices)
        n_inds = n_inds - n_inds % world_size
        self.indices = np.array(self.indices)
        self.indices = self.indices[rank:n_inds:world_size] # shard
        print('load indices done')

        self.iter = 0
        self.n_iters = self.indices.shape[0] // self.batchsize

    def __iter__(self):
        self.iter = 0
        return self

    def __next__(self):

        if self.iter > self.n_iters:
            raise StopIteration

        st = self.iter * self.batchsize
        inds = self.indices[st : st + self.batchsize]

        import cv2
        bins = [np.fromfile(self.files[i]) for i in inds]
        images = [cv2.imdecode(np.frombuffer(el, dtype=np.uint8), cv2.IMREAD_COLOR)
                for el in bins]

        ## Add this line, and there will be no errors
        ## Without this line, program fail
        images = [cv2.resize(el, (224, 224)) for el in images]

        self.iter += 1

        return images,


@pipeline_def
def create_dali_pipeline(source, shard_id, num_shards, dali_cpu=False):

    images, = fn.external_source(source=source, num_outputs=1,
                                        dtype=[types.UINT8, ],
                                        parallel=True, batch=True,
                                        cycle='raise')


    images = fn.random_resized_crop(images.gpu(), device='gpu',
                        size=(224, 224),
                        random_aspect_ratio=[0.75, 1.333333],
                        random_area=[0.67, 1.0],
                        antialias=True,
                        interp_type=types.INTERP_LINEAR)
    images = fn.color_space_conversion(images, image_type=types.BGR, output_type=types.RGB)

    mirror = fn.random.coin_flip(probability=0.5)
    images = fn.flip(images, horizontal=mirror)

    images = fn.normalize(images,
        dtype=types.FLOAT,
        mean=[0.485 * 255,0.456 * 255,0.406 * 255],
        stddev=[0.229 * 255,0.224 * 255,0.225 * 255]
        )
    images = fn.transpose(images, output_layout="CHW")
    return images



def create_dali_loader(im_anno, batchsize, n_workers, n_epoches):
    rank = int(os.environ['RANK'])
    local_rank = int(os.environ['LOCAL_RANK'])
    world_size = int(os.environ['WORLD_SIZE'])
    local_world_size = int(os.environ['LOCAL_WORLD_SIZE'])


    source = ExternalInputIterator(
                                   file_list=im_anno,
                                   rank=rank,
                                   world_size=world_size,
                                   n_epoches=n_epoches,
                                   global_batchsize=batchsize)

    pipe = create_dali_pipeline(batch_size=batchsize,
                                source=source,
                                num_threads=n_workers,
                                device_id=local_rank,
                                seed=12 + local_rank,
                                dali_cpu=False,

                                py_start_method='spawn',
                                py_num_workers=1,
                                py_callback_pickler=Pickler(),

                                prefetch_queue_depth=8,
                                shard_id=local_rank,
                                num_shards=world_size)
    pipe.build()
    data_loader = DALIGenericIterator(pipe, ['data', ],
                                              last_batch_policy=LastBatchPolicy.DROP,
                                              auto_reset=True)
    return data_loader


```
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/.conda/envs/py310/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0', 'console_scripts', 'torchrun')())
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```
```


### Other/Misc.

_No response_

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @CoinCheung,

Thank you for reaching out.
At first glance, I don't see anything suspicious in your code. Can you make it self-contained so I can run it on my end (even using toy data from https://github.com/NVIDIA/DALI_extra)?
You can also check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html) to make sure we are on the same page when it comes to using external source operator in the parallel mode.

**Comment by CoinCheung** [comment]
Hi @JanuszL ,

After a night's trying, I have shrink the code. Please try [this](https://github.com/CoinCheung/eewee/releases/download/0.0.0/bug.zip).

Just unzip and run `start.sh`:
```
unzip debug.zip
bash start.sh
```

And on my platform, the errors appear.

**Comment by CoinCheung** [comment]
By the way, my error message shows that the program is killed by signal 11, and my is an amd cpu:
![image](https://github.com/NVIDIA/DALI/assets/22693362/9b275106-93e3-4e91-bd3c-f95529dcbd66)

**Comment by JanuszL** [comment]
Hi @CoinCheung,

On my end, I see:
```
Can't allocate 648019968 bytes
```
and
```
torch.cuda.OutOfMemoryError: CUDA out of memory```
This means you just run out of memory on the GPU. Please reduce batch si and try again, something like 128 for a start.

**Comment by CoinCheung** [comment]
Thanks @JanuszL , I would check it. By the way, when I add this to the pipeline: 
```
 images = fn.normalize(images,
        dtype=types.FLOAT,
        mean=[0.485 * 255,0.456 * 255,0.406 * 255],
        stddev=[0.229 * 255,0.224 * 255,0.225 * 255]
        )
```
There is an error:
```
File "/home/projects/bug/main.py", line 162, in create_dali_pipeline
    images = fn.normalize(images,
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/nvidia/dali/fn.py", line 89, in fn_wrapper
    return op_wrapper(*inputs, **kwargs)
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/nvidia/dali/fn.py", line 81, in op_wrapper
    return op_class(**init_args)(*inputs, **call_args)
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/nvidia/dali/ops.py", line 625, in __init__
    _add_spec_args(self._schema, self._spec, kwargs)
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/nvidia/dali/ops.py", line 399, in _add_spec_args
    converted_value = _type_convert_value(dtype, value)
  File "/home/.conda/envs/py310/lib/python3.10/site-packages/nvidia/dali/types.py", line 110, in _type_convert_value
    return _known_types[dtype][1](val)
TypeError: float() argument must be a string or a real number, not 'list'
```

Would you tell me what did I miss here?

**Comment by JanuszL** [comment]
Hi @CoinCheung,

Please check [the 'crop_mirror_normalize` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.crop_mirror_normalize.html) that accepts the list of values for each channel or
```
out = fn.normalize(
            fn.transpose(images, perm=[2,0,1]),
            axes=[1,2],
            mean=np.array([[[128.]], [[128.]], [[128.]]], dtype=np.float32),
            stddev=np.array([[[1.]], [[1.]], [[1.]]], dtype=np.float32)
        )
```
or
```
out = fn.normalize(images,
            axes=[0, 1],
            mean=np.array([[[128., 128., 128.]]], dtype=np.float32),
            stddev=np.array([[[1., 1., 1.]]], dtype=np.float32)
        )
```
depending on the data layout. The tensor provided to `mean` and `stddev` arguments follow the regular broadcasting rules.

**Comment by CoinCheung** [comment]
@JanuszL Thanks!!

One last question, when I use cpu to decode image and crop everything works fine:
![image](https://github.com/NVIDIA/DALI/assets/22693362/4993e1a5-b39e-4576-8cad-e1a17d3cfda7)

But when I try to use mixed device or crop with gpu, there would be errors:
![image](https://github.com/NVIDIA/DALI/assets/22693362/8fc68cc1-6a42-48c9-a265-354c78e11bea)

error message is:
```
    self._pipe.Build(self._generate_build_args())
RuntimeError: Critical error when building pipeline:
Error when constructing operator: decoders__ImageRandomCrop encountered:
CUDA runtime API error cudaErrorOperatingSystem (304):
OS call failed or operation not supported on this OS
Current pipeline object is no longer valid.
[2023-11-16 09:20:56,600] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 101259 closing signal SIGTERM
[2023-11-16 09:20:56,601] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 101260 closing signal SIGTERM
[2023-11-16 09:20:56,603] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 101261 closing signal SIGTERM
[2023-11-16 09:20:57,732] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 101258) of binary: /home/.conda/envs/py310/bin/python

```

Would you tell me what is the cause of this?

**Comment by JanuszL** [comment]
@CoinCheung,
```CUDA runtime API error cudaErrorOperatingSystem (304):
OS call failed or operation not supported on this OS```
Is not expected. Can you tell me more about which GPU driver version you have? Which OS are you running? Have you tried running DALi inside a docker container and see if that helps?

**Comment by CoinCheung** [comment]
Hi @JanuszL ,

this is part of my gpu information:
![image](https://github.com/NVIDIA/DALI/assets/22693362/c81053f0-8c48-4433-aa06-eee7983b85ee)

And this is the output of running `uname -a`:
![image](https://github.com/NVIDIA/DALI/assets/22693362/368a37ee-fa5b-46c3-a8d7-560949fb228a)

I am using python 3.10, and pytorch 2.1.0.

I did not try docker container, because I do not have sudo on this server, and they do not allow me to use docker...

Is this something relevant to cpu? This is my cpu info:

![image](https://github.com/NVIDIA/DALI/assets/22693362/9297cc38-c692-440d-9fce-9aa502f93ca5)

This problem only happens when I try to use gpu for image decoding, and `random_resized_crop`.

**Comment by JanuszL** [comment]
@CoinCheung,

I don't think that this problem is related to your CPU. Can you check if you can run our [toy example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting_started.html)? Also are you sure you can run any GPU-related workload in your configuration (it is the first time I see this error and it doesn't seem to be caused by the DALI itself)?

**Comment by CoinCheung** [comment]
Hi @JanuszL ,

I do not have this problem with cpu, and this problem  only appear when I use gpu/mixed device.

Also, I do not have this problem with other operators, only `fn.decoder.image` and `fn.random_resized_crop` have this problem.

Actually, I also do not have this problem on another server, which has an intel cpu, that is why I ask if this can be related with amd cpu..


I will also have a check on my images.

**Comment by JanuszL** [comment]
I guess this may be due to a particular server SW configuration/setup, that not necessarily needs to be bound to the CPU architecture. That is why I'm asking if you can run any other application that uses GPU.

**Comment by CoinCheung** [comment]
Hi @JanuszL ,

I read the images with PIL and then save back, after that the training is normal.  It seems that the problem is with the images, though with other settings the program can still work.

I am closing this since problem is solved.
