### ISSUE TITLE
nvidia.dali.fn.python_function() failed with TypeError

### ISSUE THREAD

**Issue by jackdaw213** [NVIDIA/DALI#5252]
### Version

1.32

### Describe the bug.

Since DALI does not support LAB color space, I want to use python_function() to convert images from RGB to LAB but got a TypeError

```
def rgb_to_lab(image):
    lab_image = []
    for i in image:
        lab_image.append(cv2.cvtColor(i, cv2.COLOR_RGB2LAB))
    return lab_image

@pipeline_def(device_id=0)
def dali_pipeline(image_dir, do_transform=True):
    images = fn.readers.file(file_root=image_dir, 
                                random_shuffle=True, 
                                name="Reader")

    images = fn.decoders.image(images, 
                                device="cpu",
                                output_type=types.RGB)
    
    images = fn.python_function(images, function=rgb_to_lab) <-- error raises here
    images = fn.transpose(images, device="gpu", perm=[2, 0, 1])

    if do_transform:
        images = fn.resize(images, resize_x=320, resize_y=240)

    color = images[1:, :, :]
    black = images[0, :, :].unsqueeze(0)

    return black, color

train_loader = DALIGenericIterator(
    [dataset.ColorDataset.dali_pipeline(image_dir='data/train',
                                        batch_size=BATCH_SIZE,
                                        num_threads=4)],
    ['black', 'color']
)

train(train_loader,...)
```
Below is the output
```
Traceback (most recent call last):
  File "/home/jackdaw/GitHub/ImageColorization/main.py", line 40, in <module>
    [dataset.ColorDataset.dali_pipeline(image_dir='data/train',
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 1779, in create_pipeline
    _generate_graph(pipe, pipe_func, args, fn_kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 1637, in _generate_graph
    pipe_outputs = func(*fn_args, **fn_kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/dataset.py", line 59, in dali_pipeline
    images = fn.python_function(images, function=ColorDataset.rgb_to_lab)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/nvidia/dali/fn/__init__.py", line 90, in fn_wrapper
    return op_wrapper(*inputs, **kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/nvidia/dali/fn/__init__.py", line 82, in op_wrapper
    return op_class(**init_args)(*inputs, **call_args)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/nvidia/dali/ops/_operators/python_function.py", line 76, in __call__
    raise TypeError(f"Expected inputs of type `DataNode`. "
TypeError: Expected inputs of type `DataNode`. Received input of type 'list'. Python Operators do not support Multiple Input Sets.
```

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by banasraf** [comment]
Hey @jackdaw213 

I think the problem lays in the use of file reader. This operator returns pairs of files and labels, so it should look like this:
```python
@pipeline_def(device_id=0)
def dali_pipeline(image_dir, do_transform=True):
    images, labels = fn.readers.file(file_root=image_dir, 
                                random_shuffle=True, 
                                name="Reader")
    # further code does not change
```

In your case the images captured the whole tuple of images and labels and its later misinterpreted by other operators.

Please let me know if this solves your problem.

**Comment by jackdaw213** [comment]
Thank you so much for your help, that was indeed the issue. Is there any operator that reads only images ? Also what is the equivalent of unsqueeze in DALI, I found only squeeze in the [docs](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.squeeze.html)

**Comment by jackdaw213** [comment]
I've managed to solve all of my problems. Below is the standard PyTorch Dataset class and it's DALI equivalent
```
class ColorDataset(torch.utils.data.Dataset):
    def __init__(self, image_dir, do_transform=False):
        self.names = os.listdir(image_dir)
        self.image_dir = image_dir
        self.do_transform = do_transform
        self.transform = transforms.Compose([
            transforms.Resize((320, 240), antialias=True)
        ])
    def __len__(self):
        return len(self.names)

    def __getitem__(self, index):
        image_path = os.path.join(self.image_dir, self.names[index])

        image = rgb2lab(Image.open(image_path).convert("RGB"))
        image = torch.from_numpy(image).permute(2,0,1).float()
        if self.do_transform:
            image = self.transform(image)

        color = image[1:, :, :]
        black = image[0, :, :].unsqueeze(0)
        
        return black, color
    
    @staticmethod
    @pipeline_def(device_id=0)
    def dali_pipeline(image_dir, do_transform=True):
        images, _ = fn.readers.file(file_root=image_dir, 
                                         file_list=image_dir+"/labels.txt",
                                         random_shuffle=True, 
                                         name="Reader")
        
        images = fn.decoders.image(images, device="mixed", output_type=types.RGB)
        images = fn.python_function(images, function=rgb2lab)

        if do_transform:
            images = fn.resize(images, size=(320, 240))

        images = fn.transpose(images, perm=[2, 0, 1])
        
        #assd = fn.python_function(images, function=ColorDataset.smt)
        
        color = images[1:, :, :]
        black = fn.expand_dims(images[0, :, :], axes=0) <-- the same as unsqueeze(0)

        return black, color
```
I installed DALI, CuPy, and cuCIM (for rgb2lab but GPU accelerated). Also, you need to make a dummy labels.txt file and place it inside the data folder. You can simply ignore the labels and use the images only. Below is the helper function for creating a dummy label file
```
def create_dummy_label_file(folder_path, output_file="labels.txt"):
    with open(f"{folder_path}/{output_file}", 'w') as f:
        for filename in os.listdir(folder_path):
            if filename.endswith(('.jpg', '.jpeg', '.png', '.gif', '.bmp')):
                label_line = f"{filename} 0\n"
                f.write(label_line)
```
Hope this can help other people in the future

**Comment by JanuszL** [comment]
Hi @jackdaw213,

I'm glad you made that work.
One simplification that comes to my mind is that you can just use the `files` argument of the file reader and pass the list of files directly instead of creating a label_file.

**Comment by jackdaw213** [comment]
Thank you for the suggestion
