### ISSUE TITLE
When decoding RTSP streams using DALI, I encountered the following issues:

### ISSUE THREAD

**Issue by qulei123** [NVIDIA/DALI#5463]
### Describe the question.

1. I'm using ffmpeg to capture the RTSP stream and store the raw stream data in memory.
2. I'm packetizing the raw stream data in memory into GOPs (Group of Pictures) of 50 frames per second (fps) and sending them to decoders.video or inputs.video for decoding. The decoding process works fine when I send 50 frames at a time.
3. However, I want to improve the real-time performance by sending and decoding the raw stream data one frame at a time, but the program fails to run correctly, and I'm getting an error as follows:
```
# python 12th_video.py
/usr/local/lib/python3.7/dist-packages/nvidia/dali/backend.py:57: Warning: DALI 1.31 is the last release to support Python 3.7. Please update your environment to use Python 3.8, 3.9, 3.10, or (experimentally) 3.11.
  deprecation_warning("DALI 1.31 is the last release to support Python 3.7. "
sps frame
pps frame
sei frame
idr frame
p frame
(1, 1, 1080, 1920, 3)
Traceback (most recent call last):
  File "12th_video.py", line 547, in <module>
    test_video_input(rtsp_url)
  File "12th_video.py", line 537, in test_video_input
    (output,) = p.run()
  File "/usr/local/lib/python3.7/dist-packages/nvidia/dali/pipeline.py", line 1146, in run
    return self.outputs()
  File "/usr/local/lib/python3.7/dist-packages/nvidia/dali/pipeline.py", line 989, in outputs
    return self._outputs()
  File "/usr/local/lib/python3.7/dist-packages/nvidia/dali/pipeline.py", line 1073, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator experimental__inputs__Video encountered:
[/opt/dali/dali/operators/reader/loader/video/frames_decoder.cc:221] Assert on "ret == 0" failed: Failed to open video file memory filedue to Invalid data found when processing input
Stacktrace (13 entries):
[frame 0]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali_operators.so(+0x69e80e) [0x7f3c0fcd680e]
[frame 1]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali_operators.so(dali::FramesDecoder::FramesDecoder(char const*, int, bool, bool, int)+0x5df) [0x7f3c132a207f]
[frame 2]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali_operators.so(dali::FramesDecoderGpu::FramesDecoderGpu(char const*, int, CUstream_st*, bool, int)+0x16) [0x7f3c13295396]
[frame 3]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali_operators.so(+0x284c5af) [0x7f3c11e845af]
[frame 4]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali_operators.so(+0x2851196) [0x7f3c11e89196]
[frame 5]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali.so(dali::Executor<dali::AOT_WS_Policy<dali::UniformQueuePolicy>, dali::UniformQueuePolicy>::RunHelper(dali::OpNode&, dali::Workspace&, unsigned long)+0x5df) [0x7f3c85c3781f]
[frame 6]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali.so(dali::Executor<dali::AOT_WS_Policy<dali::UniformQueuePolicy>, dali::UniformQueuePolicy>::RunMixedImpl(unsigned long)+0x397) [0x7f3c85c406b7]
[frame 7]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali.so(dali::Executor<dali::AOT_WS_Policy<dali::UniformQueuePolicy>, dali::UniformQueuePolicy>::RunMixed()+0x21) [0x7f3c85c40d51]
[frame 8]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali.so(+0x11d883) [0x7f3c85bff883]
[frame 9]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali.so(+0x199ecc) [0x7f3c85c7becc]
[frame 10]: /usr/local/lib/python3.7/dist-packages/nvidia/dali/libdali.so(+0x7b34f0) [0x7f3c862954f0]
[frame 11]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f3ca13fb6db]
[frame 12]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f3ca173461f]

Current pipeline object is no longer valid.
```
I would appreciate any assistance or solutions regarding these issues. Thank you.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @qulei123,

Thank you for reporting your problem. The error you see is reported by libaviformat which cannot open the raw stream data for with frame at a time. Is it possible for you to share [a minimal and self-contained repro we can run on our end](https://github.com/NVIDIA/DALI?tab=readme-ov-file#reporting-problems-asking-questions) to investigate it further?

**Comment by qulei123** [comment]
> Hi @qulei123,
> 
> Thank you for reporting your problem. The error you see is reported by libaviformat which cannot open the raw stream data for with frame at a time. Is it possible for you to share [a minimal and self-contained repro we can run on our end](https://github.com/NVIDIA/DALI?tab=readme-ov-file#reporting-problems-asking-questions) to investigate it further?

**Comment by qulei123** [comment]
> Hi @qulei123,
> 
> Thank you for reporting your problem. The error you see is reported by libaviformat which cannot open the raw stream data for with frame at a time. Is it possible for you to share [a minimal and self-contained repro we can run on our end](https://github.com/NVIDIA/DALI?tab=readme-ov-file#reporting-problems-asking-questions) to investigate it further?

```

import os
import numpy as np
import glob
import subprocess as sp
import io
import threading
import queue
import array

from nvidia.dali.pipeline import Pipeline
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types
from nvidia.dali.backend import TensorListGPU

import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt


def split_nalus(data):
    nalus = []
    nal_start = None
    i = 0

    while i < len(data):
        if data[i:i+4] == b'\x00\x00\x00\x01':
            if nal_start is not None:
                nalus.append(data[nal_start:i])
            nal_start = i
            i += 4
        elif i > 0 and data[i-1:i+3] == b'\x00\x00\x00\x01':
            if nal_start is not None:
                nalus.append(data[nal_start:i-1])
            nal_start = i
            i += 3
        else:
            i += 1

    if nal_start is not None and nal_start < len(data):
        nalus.append(data[nal_start:])

    return nalus

# Put the SPS, PPS, and IDR frames into a buffer and send them to the decoder all at once.
sps = b''
pps = b''
sei = b''
idr_seq = b''

def pkt_idr_seq(nalus):
    global sps
    global pps
    global sei
    global idr_seq
    frames = []
    frame = b''

    for nalu in nalus[:-1]:
        if nalu[4] == 0x67:
            sps = nalu
            print("sps frame")
        elif nalu[4] == 0x68:
            pps = nalu
            print("pps frame")
        elif nalu[4] == 0x06:
            sei = nalu
            print("sei frame")
        elif nalu[4] == 0x65:
            idr_seq = sps + pps + nalu
            frames.append(idr_seq)
            print("idr frame")
        elif nalu[4] == 0x61:
            frame = nalu
            frames.append(frame)
            print("p frame")
        else:
            print("not frame = ", nalu)

    return frames

def read_ffmpeg_output6(process, pipe):
    buffer = b''
    frames = b''

    try:
        while True:
            data = process.stdout.read(40960)
            if not data:
                break

            buffer += data
            nalus = split_nalus(buffer)
            frames = pkt_idr_seq(nalus)
            for frame in frames:
                batch = []
                data_array = np.frombuffer(frame, dtype=np.uint8)
                batch.append(data_array)
                pipe.feed_input("VIDEO_INPUT", batch)

            # This translation expresses the idea that there is still some data left in the buffer, 
            # which might be the beginning of a NAL (Network Abstraction Layer) unit that has not 
            # been fully received or processed yet.
            buffer = nalus[-1] if nalus else b''
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        process.stdout.close()

def rtsp_video_loader2(rtsp_url, pipe):
    cmd = [
        'ffmpeg',
        '-fflags', 'nobuffer',
        '-i', rtsp_url,
        '-an',
        '-c:v', 'copy',
        '-f', 'rawvideo',
        '-'
    ]

    process = sp.Popen(cmd, stdout=sp.PIPE, stderr=sp.PIPE, universal_newlines=False)
    t = threading.Thread(target=read_ffmpeg_output6, args=(process, pipe))
    t.daemon = True
    t.start()

batch_size = 1
rtsp_url = 'rtsp://192.168.50.88/live/test'

# (N, F, H, W, C)
@pipeline_def(batch_size=1, num_threads=1, device_id=0)
def video_input_pipeline(input_name, device="cpu"):
    vid = fn.experimental.inputs.video(name=input_name, device=device, sequence_length=50, blocking=True)
    return vid
    
def test_video_input(rtsp_url):
    input_name = "VIDEO_INPUT"
    n_iterations = 50
    p = video_input_pipeline(input_name, "mixed")
    p.build()
    rtsp_video_loader2(rtsp_url, p)
    for i in range(n_iterations):
        (output,) = p.run()
        if isinstance(output, TensorListGPU):
            output = output.as_cpu()
        output = output.as_array()
        print(output.shape)
        #show_sequence(output[0], '12th_output_' + str(i) + '.png')

test_video_input(rtsp_url)

```

**Comment by JanuszL** [comment]
Thank you for sharing the code. Could you also provide a snippet on how you run the rtsp server (it can even use data from [DALI_extra repo](https://github.com/NVIDIA/DALI_extra/tree/main/db/video).

**Comment by JanuszL** [comment]
> I can directly pull RTSP data from a network camera for testing, and I would also like to test the raw H.264 stream data from DALI_extra.
If you could assemble such an evn it would help me a lot as I don't have any camera for testing (and besides that, it can make the issue camera HW specific and hard for us to reproduce).

**Comment by qulei123** [comment]
@JanuszL 
For example, when testing with the following raw stream sequence:
```
Raw Stream Sequence: SPS PPS IDR P P ...... P
```
When sending data frame by frame, the issue arises when sending a P frame alone.

If I extend the raw stream sequence to the following:
```
Extended Raw Stream Sequence: [SPS PPS IDR P] [SPS PPS IDR P] [SPS PPS IDR P] ...... [SPS PPS IDR P]
```
By appending [SPS PPS IDR] when sending a P frame alone, the testing issue is resolved.
However, this approach involves significant data copying, which impacts performance.

I suspect that the internal decoder in DALI does not cache [SPS PPS IDR], causing newly arrived P frames to be unable to decode.

**Comment by JanuszL** [comment]
> By appending [SPS PPS IDR] when sending a P frame alone, the testing issue is resolved.
> However, this approach involves significant data copying, which impacts performance.
>
> I suspect that the internal decoder in DALI does not cache [SPS PPS IDR], causing newly arrived P frames to be unable to decode.

Yes, DALI treats the sample as a self-contained thing. So if there are only P frames it will fail to decode (even if in some cases it may open the stream properly).
You may also try to play with [experimental.inputs.video](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.inputs.video.html) which is stateful, however there it no yet proper python API that would indicate that you need to feed more data. In this case, you need to count how many frames you fed and how many you received.

**Comment by qulei123** [comment]
@JanuszL 
I have tested experimental.inputs.video today, and the effect is the same as experimental.decoders.video, both exhibiting the same issue. Thank you for your help.
