### ISSUE TITLE
Error install nvidia-dali-tf-plugin-cuda110-1.38.0

### ISSUE THREAD

**Issue by confusedgreenhand** [NVIDIA/DALI#5498]
### Describe the question.

pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-tf-plugin-cuda110

Looking in indexes: https://pypi.org/simple, https://developer.download.nvidia.com/compute/redist
Collecting nvidia-dali-tf-plugin-cuda110
  Using cached https://developer.download.nvidia.cn/compute/redist/nvidia-dali-tf-plugin-cuda110/nvidia-dali-tf-plugin-cuda110-1.38.0.tar.gz (381 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: nvidia-dali-cuda110==1.38.0 in /home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages (from nvidia-dali-tf-plugin-cuda110) (1.38.0)
Requirement already satisfied: astunparse>=1.6.0 in /home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages (from nvidia-dali-cuda110==1.38.0->nvidia-dali-tf-plugin-cuda110) (1.6.3)
Requirement already satisfied: gast>=0.3.3 in /home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages (from nvidia-dali-cuda110==1.38.0->nvidia-dali-tf-plugin-cuda110) (0.4.0)
Requirement already satisfied: dm-tree in /home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages (from nvidia-dali-cuda110==1.38.0->nvidia-dali-tf-plugin-cuda110) (0.1.8)
Requirement already satisfied: nvidia-nvimgcodec-cu11>=0.2.0 in /home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages (from nvidia-dali-cuda110==1.38.0->nvidia-dali-tf-plugin-cuda110) (0.2.0.7)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages (from astunparse>=1.6.0->nvidia-dali-cuda110==1.38.0->nvidia-dali-tf-plugin-cuda110) (0.43.0)
Requirement already satisfied: six<2.0,>=1.6.1 in /home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages (from astunparse>=1.6.0->nvidia-dali-cuda110==1.38.0->nvidia-dali-tf-plugin-cuda110) (1.16.0)
Building wheels for collected packages: nvidia-dali-tf-plugin-cuda110
  Building wheel for nvidia-dali-tf-plugin-cuda110 (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [220 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/nvidia
      creating build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin
      copying nvidia/dali_tf_plugin/dali_tf_plugin.py -> build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin
      copying nvidia/dali_tf_plugin/__init__.py -> build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin
      running egg_info
      writing nvidia_dali_tf_plugin_cuda110.egg-info/PKG-INFO
      writing dependency_links to nvidia_dali_tf_plugin_cuda110.egg-info/dependency_links.txt
      writing requirements to nvidia_dali_tf_plugin_cuda110.egg-info/requires.txt
      writing top-level names to nvidia_dali_tf_plugin_cuda110.egg-info/top_level.txt
      reading manifest file 'nvidia_dali_tf_plugin_cuda110.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'nvidia_dali_tf_plugin_cuda110.egg-info/SOURCES.txt'
      copying nvidia/dali_tf_plugin/Acknowledgements.txt -> build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin
      copying nvidia/dali_tf_plugin/COPYRIGHT -> build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin
      copying nvidia/dali_tf_plugin/LICENSE -> build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin
      running build_ext
      Checking build environment for DALI TF plugin ...
      
       Environment:
       ----------------------------------------------------------------------------------
       Platform system:                      Linux
       Platform machine:                     x86_64
       DALI lib path:                        /home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/nvidia/dali
       TF path:                              /home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/tensorflow
       DALI TF plugin destination directory: build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin
       Is Conda environment?                 Yes
       Using compiler:                       "g++", version 9.4
       TF version installed:                 2.9
       g++ version used to compile TF:       9.3
       Is g++-9.3 present in the system?     No
       Can install prebuilt plugin?          No
       Prebuilt for exact TF version?        No
       Prebuilt plugin path:                 N/A
       Prebuilt plugins available:           /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/prebuilt/libdali_tf_2_14.so, /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/prebuilt/libdali_tf_2_13.so
       Prebuilt DALI stub available:         /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/prebuilt/stub/libdali.so
       Can compile with default compiler?    Yes
       Can compile with alt compiler?        No
      -----------------------------------------------------------------------------------
      Proceed with build from source...
      Building DALI stub lib:
      
       g++ -Wl,-R,$ORIGIN/.. -std=c++14 -DNDEBUG -shared /tmp/dali_stub_1g0056a0/dali_stub.cc -o /tmp/dali_stub_1g0056a0/libdali.so -fPIC -I/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/include -I/usr/local/cuda/include -O2
      
      
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int daliIsDeserializable(const char*, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:50:1: warning: no return statement in function returning non-void [-Wreturn-type]
         50 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int daliGetMaxBatchSize(DALIPipeline**)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:54:1: warning: no return statement in function returning non-void [-Wreturn-type]
         54 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int daliInputFeedCount(DALIPipeline**, const char*)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:68:1: warning: no return statement in function returning non-void [-Wreturn-type]
         68 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int daliGetNumExternalInput(DALIPipeline**)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:102:1: warning: no return statement in function returning non-void [-Wreturn-type]
        102 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘const char* daliGetExternalInputName(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:106:1: warning: no return statement in function returning non-void [-Wreturn-type]
        106 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘const char* daliGetExternalInputLayout(DALIPipeline**, const char*)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:111:1: warning: no return statement in function returning non-void [-Wreturn-type]
        111 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘dali_data_type_t daliGetExternalInputType(DALIPipeline**, const char*)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:116:1: warning: no return statement in function returning non-void [-Wreturn-type]
        116 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int daliGetExternalInputNdim(DALIPipeline**, const char*)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:120:1: warning: no return statement in function returning non-void [-Wreturn-type]
        120 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int64_t daliOutputHasUniformShape(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:153:1: warning: no return statement in function returning non-void [-Wreturn-type]
        153 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int64_t* daliShapeAt(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:157:1: warning: no return statement in function returning non-void [-Wreturn-type]
        157 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘dali_data_type_t daliTypeAt(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:161:1: warning: no return statement in function returning non-void [-Wreturn-type]
        161 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int64_t* daliShapeAtSample(DALIPipeline**, int, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:165:1: warning: no return statement in function returning non-void [-Wreturn-type]
        165 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘size_t daliNumTensors(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:169:1: warning: no return statement in function returning non-void [-Wreturn-type]
        169 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘size_t daliNumElements(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:173:1: warning: no return statement in function returning non-void [-Wreturn-type]
        173 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘size_t daliTensorSize(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:177:1: warning: no return statement in function returning non-void [-Wreturn-type]
        177 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘size_t daliMaxDimTensors(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:181:1: warning: no return statement in function returning non-void [-Wreturn-type]
        181 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘size_t daliGetDeclaredOutputNdim(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:185:1: warning: no return statement in function returning non-void [-Wreturn-type]
        185 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘dali_data_type_t daliGetDeclaredOutputDtype(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:189:1: warning: no return statement in function returning non-void [-Wreturn-type]
        189 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘unsigned int daliGetNumOutput(DALIPipeline**)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:193:1: warning: no return statement in function returning non-void [-Wreturn-type]
        193 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘const char* daliGetOutputName(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:197:1: warning: no return statement in function returning non-void [-Wreturn-type]
        197 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘device_type_t daliGetOutputDevice(DALIPipeline**, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:201:1: warning: no return statement in function returning non-void [-Wreturn-type]
        201 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int daliHasOperatorTrace(DALIPipeline**, const char*, const char*)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:206:1: warning: no return statement in function returning non-void [-Wreturn-type]
        206 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘const char* daliGetOperatorTrace(DALIPipeline**, const char*, const char*)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:211:1: warning: no return statement in function returning non-void [-Wreturn-type]
        211 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘dali_backend_t daliGetOperatorBackend(DALIPipeline**, const char*)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:258:1: warning: no return statement in function returning non-void [-Wreturn-type]
        258 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int daliPreallocateDeviceMemory(size_t, int)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:277:1: warning: no return statement in function returning non-void [-Wreturn-type]
        277 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘int daliPreallocatePinnedMemory(size_t)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:281:1: warning: no return statement in function returning non-void [-Wreturn-type]
        281 | }
            | ^
      /tmp/dali_stub_1g0056a0/dali_stub.cc: In function ‘void* daliAlloc(size_t)’:
      /tmp/dali_stub_1g0056a0/dali_stub.cc:304:1: warning: no return statement in function returning non-void [-Wreturn-type]
        304 | }
            | ^
      2024-06-05 14:31:10.298328: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
      Build DALI TF library:
      
       g++ -Wl,-R,$ORIGIN/.. -Wl,-rpath,$ORIGIN --std=c++14 -DNDEBUG -shared /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/daliop.cc /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_dataset_op.cc -o build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin/libdali_tf_current.so -fPIC -I/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/include -I/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1 -DEIGEN_MAX_ALIGN_BYTES=64 -I/usr/include -I/usr/local/cuda/include -L/tmp/dali_stub_1g0056a0 -ldali -L/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/tensorflow -l:libtensorflow_framework.so.2 -O2
      
      
      /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_dataset_op.cc: In member function ‘virtual tensorflow::Status dali_tf_impl::DALIDatasetOp::Dataset::Iterator::SaveInternal(tensorflow::data::SerializationContext*, tensorflow::data::IteratorStateWriter*)’:
      /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_dataset_op.cc:417:46: warning: narrowing conversion of ‘n’ from ‘size_t’ {aka ‘long unsigned int’} to ‘long int’ [-Wnarrowing]
        417 |     tensorflow::Tensor cpt_tensor(DT_UINT8, {n});
            |                                              ^
      /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_dataset_op.cc:417:46: warning: narrowing conversion of ‘n’ from ‘size_t’ {aka ‘long unsigned int’} to ‘long int’ [-Wnarrowing]
      /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_dataset_op.cc:423:12: error: ‘OkStatus’ was not declared in this scope
        423 |     return OkStatus();
            |            ^~~~~~~~
      /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_dataset_op.cc: In member function ‘virtual tensorflow::Status dali_tf_impl::DALIDatasetOp::Dataset::Iterator::RestoreInternal(tensorflow::data::IteratorContext*, tensorflow::data::IteratorStateReader*)’:
      /tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_dataset_op.cc:445:12: error: ‘OkStatus’ was not declared in this scope
        445 |     return OkStatus();
            |            ^~~~~~~~
      Build from source failed with error:  Command '['g++', '-Wl,-R,$ORIGIN/..', '-Wl,-rpath,$ORIGIN', '--std=c++14', '-DNDEBUG', '-shared', '/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/daliop.cc', '/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_dataset_op.cc', '-o', 'build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin/libdali_tf_current.so', '-fPIC', '-I/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/include', '-I/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=1', '-DEIGEN_MAX_ALIGN_BYTES=64', '-I/usr/include', '-I/usr/local/cuda/include', '-L/tmp/dali_stub_1g0056a0', '-ldali', '-L/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/tensorflow', '-l:libtensorflow_framework.so.2', '-O2']' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/setup.py", line 37, in <module>
          setup(name='nvidia-dali-tf-plugin-cuda110',
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/setup.py", line 25, in run
          helper.install()
        File "/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_tf_plugin_install_tool.py", line 436, in install
          raise e
        File "/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_tf_plugin_install_tool.py", line 428, in install
          self.build()
        File "/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_tf_plugin_install_tool.py", line 398, in build
          subprocess.check_call(cmd, cwd=self.src_path, shell=False)  # nosec B603
        File "/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['g++', '-Wl,-R,$ORIGIN/..', '-Wl,-rpath,$ORIGIN', '--std=c++14', '-DNDEBUG', '-shared', '/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/daliop.cc', '/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/dali_dataset_op.cc', '-o', 'build/lib.linux-x86_64-cpython-38/nvidia/dali_tf_plugin/libdali_tf_current.so', '-fPIC', '-I/tmp/pip-install-x5gw_3ea/nvidia-dali-tf-plugin-cuda110_7a9fbeef768843b5bb66e48643e90a72/include', '-I/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=1', '-DEIGEN_MAX_ALIGN_BYTES=64', '-I/usr/include', '-I/usr/local/cuda/include', '-L/tmp/dali_stub_1g0056a0', '-ldali', '-L/home/hazelwang/anaconda3/envs/hailo/lib/python3.8/site-packages/tensorflow', '-l:libtensorflow_framework.so.2', '-O2']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nvidia-dali-tf-plugin-cuda110
  Running setup.py clean for nvidia-dali-tf-plugin-cuda110
Failed to build nvidia-dali-tf-plugin-cuda110
ERROR: Could not build wheels for nvidia-dali-tf-plugin-cuda110, which is required to install pyproject.toml-based projects

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @confusedgreenhand,

Thank you for reaching out. This is the DALI plugin incompatibility with the older TensorFlow internal API. I see that 2.9 is over 2 years old, can you update to a more recent version, like 2.10, and check again?
I added a fix for the next release - https://github.com/NVIDIA/DALI/pull/5499, but other things may not work besides that as we no longer test DALI with such an old TensorFlow version.

**Comment by JanuszL** [comment]
The fix has been merged. Please check the next nightly build or 1.39 release once it is available.

**Comment by JanuszL** [comment]
1.39 and 1.40 are public. Closing.
