### ISSUE TITLE
Spaces in s3 URL: Invalid character found in path

### ISSUE THREAD

**Issue by AlanRace** [NVIDIA/DALI#5521]
### Version

1.38

### Describe the bug.

When reading in TFRecords from s3 which have a space in the name, I encounter the error shown in the log output below. Changing spaces to either `%20` or `+` and escaping (`\ `) all produce the same error.

### Minimum reproducible example

```shell
inputs = fn.readers.tfrecord(path="s3://bucket/path/my data.tfrecord",
                    index_path="/path/to/my data.idx",
                    features={
                                'a': tfrec.FixedLenFeature((), tfrec.string, ""),
                                'b': tfrec.FixedLenFeature((), tfrec.string, ""),
                            }, 
                    name="Reader")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/ubuntu/test.py", line 348, in <module>
    train_loader = DALIGenericIterator(train_pipe, ["a", "b"],
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/nvidia/dali/plugin/base_iterator.py", line 385, in _get_outputs
    outputs.append(p.share_outputs())
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 1160, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error in CPU operator `nvidia.dali.fn.readers.tfrecord`,
which was used in the pipeline definition with the following traceback:

  File "/home/ubuntu/test.py", line 42, in create_dali_pipeline
    inputs = fn.readers.tfrecord(path=tfrecord_paths,

encountered:

s3://bucket/path/my data.tfrecord is not a valid URI: Invalid character found ( ) in path
Current pipeline object is no longer valid.
```

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by jantonguirao** [comment]
Thank you, @AlanRace, for reporting this.
I think that https://github.com/NVIDIA/DALI/pull/5525 should fix this problem
