### ISSUE TITLE
Installation of Nvidia-dali-cuda fails

### ISSUE THREAD

**Issue by Yash9060** [NVIDIA/DALI#5735]
### Version

1.44.0

### Describe the bug.

I am trying to install nvidia-dali-cuda via 

https://github.com/argonne-lcf/dlio_benchmark/blob/bc693c62cf28f896caf014e9089d9a7bcba5ef6a/requirements.txt#L23 

and the installation fails with error. (Complete log is below)

Any help ? What might be going on here ? 

I am using Debian 11 if it matters. 

### Minimum reproducible example

```shell
On Debian 11 environment, follow the steps mentioned here https://github.com/mlcommons/storage?tab=readme-ov-file#installation 

the summary of above link is


sudo apt-get install mpich
git clone -b v1.0 --recurse-submodules https://github.com/mlcommons/storage.git
cd storage
pip3 install -r dlio_benchmark/requirements.txt
```

### Relevant log output

```shell
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpm19g_y4k_in_process.py prepare_metadata_for_build_wheel /tmp/tmpqix1lh0z
         cwd: /tmp/pip-install-_8h48wz5/nvidia-dali-cuda110_bbd5bd8a11244b96997566e37f59171a
    Complete output (87 lines):
      File "/tmp/pip-build-env-9rl4e4_g/overlay/lib/python3.9/site-packages/wheel_stub/wheel.py", line 226, in download_wheel
        return download_manual(wheel_directory, distribution, version, config)
      File "/tmp/pip-build-env-9rl4e4_g/overlay/lib/python3.9/site-packages/wheel_stub/wheel.py", line 160, in download_manual
        index_response = urlopen_with_retry(project_url)
      File "/tmp/pip-build-env-9rl4e4_g/overlay/lib/python3.9/site-packages/wheel_stub/wheel.py", line 83, in urlopen_with_retry
        return urlopen(url, **kwargs)
      File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.9/urllib/request.py", line 523, in open
        response = meth(req, response)
      File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
        response = self.parent.error(
      File "/usr/lib/python3.9/urllib/request.py", line 561, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    Traceback (most recent call last):
      File "/tmp/tmpm19g_y4k_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'wheel_stub.buildapi' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-build-env-9rl4e4_g/overlay/lib/python3.9/site-packages/wheel_stub/wheel.py", line 226, in download_wheel
        return download_manual(wheel_directory, distribution, version, config)
      File "/tmp/pip-build-env-9rl4e4_g/overlay/lib/python3.9/site-packages/wheel_stub/wheel.py", line 160, in download_manual
        index_response = urlopen_with_retry(project_url)
      File "/tmp/pip-build-env-9rl4e4_g/overlay/lib/python3.9/site-packages/wheel_stub/wheel.py", line 83, in urlopen_with_retry
        return urlopen(url, **kwargs)
      File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.9/urllib/request.py", line 523, in open
        response = meth(req, response)
      File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
        response = self.parent.error(
      File "/usr/lib/python3.9/urllib/request.py", line 561, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/tmpm19g_y4k_in_process.py", line 280, in <module>
        main()
      File "/tmp/tmpm19g_y4k_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpm19g_y4k_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/tmp/tmpm19g_y4k_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-9rl4e4_g/overlay/lib/python3.9/site-packages/wheel_stub/buildapi.py", line 29, in build_wheel
        return download_wheel(pathlib.Path(wheel_directory), config_settings)
      File "/tmp/pip-build-env-9rl4e4_g/overlay/lib/python3.9/site-packages/wheel_stub/wheel.py", line 228, in download_wheel
        report_install_failure(distribution, version, config, exception_context)
      File "/tmp/pip-build-env-9rl4e4_g/overlay/lib/python3.9/site-packages/wheel_stub/error.py", line 67, in report_install_failure
        raise InstallFailedError(
    wheel_stub.error.InstallFailedError:
    *******************************************************************************

    The installation of nvidia-dali-cuda110 for version 1.44.0 failed.

    This is a special placeholder package which downloads a real wheel package
    from https://pypi.nvidia.com/. If https://pypi.nvidia.com/ is not reachable, we
    cannot download the real wheel file to install.

    You might try installing this package via
    
    $ pip install --extra-index-url https://pypi.nvidia.com/ nvidia-dali-cuda110
    

    Here is some debug information about your platform to include in any bug
    report:

    Python Version: CPython 3.9.2
    Operating System: Linux 5.10.0-33-cloud-amd64
    CPU Architecture: x86_64
    nvidia-smi command not found. Ensure NVIDIA drivers are installed.

    *******************************************************************************
```

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @Yash9060,

Thank you for reaching out. We are aware of this issue and we are working on it. In the meantime you can follow an alternative installation method using [nvidia pipy hosting site](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#pip-official-releases) - `pip install --extra-index-url https://pypi.nvidia.com --upgrade nvidia-dali-cuda120`

**Comment by JanuszL** [comment]
I has been fixed. Please check again.
