### ISSUE TITLE
DALI cannot read TFRecord dataset

### ISSUE THREAD

**Issue by zmasih** [NVIDIA/DALI#5746]
### Describe the question.

I have a TFrecord dataset that is generated by the DLIO Resnet50 model. I used a tfrecord dali loader to load the dataset and got the following error.  
I can perfectly load the dataset on DALI_extra repository with the same loader code.
I guess something is wrong with the dataset format, but I don't know how to find out where the problem lies. Would you help me understand what the problem is? 

Loader code:

```
test_data_root = os.environ["DALI_EXTRA_PATH"]
tfrecord = os.path.join(test_data_root, "db", "tfrecord", "train", "file.tfrecord")
batch_size = 16
tfrecord_idx = os.path.join(test_data_root, "db", "tfrecord", "idx_files", "file.idx")

from nvidia.dali.pipeline import Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
import numpy as np

pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
with pipe:
    inputs = fn.readers.tfrecord(
        path=tfrecord,
        index_path=tfrecord_idx,
        features={
            "image/encoded": tfrec.FixedLenFeature((), tfrec.string, ""),
            "image/class/label": tfrec.FixedLenFeature([1], tfrec.int64, -1),
            "image/class/text": tfrec.FixedLenFeature([], tfrec.string, ""),
            "image/object/bbox/xmin": tfrec.VarLenFeature(tfrec.float32, 0.0),
            "image/object/bbox/ymin": tfrec.VarLenFeature(tfrec.float32, 0.0),
            "image/object/bbox/xmax": tfrec.VarLenFeature(tfrec.float32, 0.0),
            "image/object/bbox/ymax": tfrec.VarLenFeature(tfrec.float32, 0.0),
        },
    )
    jpegs = inputs["image/encoded"]
    images = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
    resized = fn.resize(images, device="gpu", resize_shorter=256.0)
    output = fn.crop_mirror_normalize(
        resized, dtype=types.FLOAT, crop=(224, 224), mean=[0.0, 0.0, 0.0], std=[1.0, 1.0, 1.0]
    )
    pipe.set_outputs(output, inputs["image/class/text"])

    pipe.build()
pipe_out = pipe.run()
```

ERROR:
```
/user/.conda/envs/mpi4py/lib/python3.11/site-packages/nvidia/dali/backend.py:100: Warning: nvidia-dali-cuda120 is no longer shipped with CUDA runtime. You need to install it separately. NPP is typically provided with CUDA Toolkit installation or an appropriate wheel. Please check https://docs.nvidia.com/cuda/cuda-quick-start-guide/index.html#pip-wheels-installation-linux for the reference.
  deprecation_warning(
[ERROR] [jpeg_parser] Could not check if code stream can be parsed - Failed to read
Traceback (most recent call last):
  File "/mnt/lustre-grete/usr/user/scripts/tfrecord/TFrecord.py", line 46, in <module>
    pipe_out = pipe.run()
               ^^^^^^^^^^
  File "/user/.conda/envs/dali/lib/python3.11/site-packages/nvidia/dali/pipeline.py", line 1328, in run
    return self.outputs()
           ^^^^^^^^^^^^^^
  File "/user/.conda/envs/dali/lib/python3.11/site-packages/nvidia/dali/pipeline.py", line 1166, in outputs
    return self._outputs()
           ^^^^^^^^^^^^^^^
  File "/user/.conda/envs/dali/lib/python3.11/site-packages/nvidia/dali/pipeline.py", line 1251, in _outputs
    return self._pipe.Outputs()
           ^^^^^^^^^^^^^^^^^^^^
RuntimeError: Critical error in pipeline:
Error in MIXED operator `nvidia.dali.fn.decoders.image`,
which was used in the pipeline definition with the following traceback:

  File "/mnt/lustre-grete/usr/user/scripts/tfrecord/TFrecord.py", line 38, in <module>
    images = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)

encountered:

nvImageCodec failure: '#4'
```

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @zmasih,

Thank you for reaching out.
So, if I understand correctly your case, you have uncompressed images. In this case you can do something like this using [the `reshape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.reshape.html):
```
images = fn.reshape(inputs["image"], shape=fn.stack(inputs["size"], -1))
```

**Comment by zmasih** [comment]
Thank you for your response.
I tried that:
```
pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
with pipe:
    inputs = fn.readers.tfrecord(
        path=tfrecord,
        index_path=tfrecord_idx,

        features={
            "image": tfrec.FixedLenFeature((), tfrec.string, ""),                
            "size": tfrec.FixedLenFeature([1], tfrec.int64, 0),                     
        },
    )
    raw_images = inputs["image"]      
    image_size = inputs["size"]       
    images = fn.reshape(raw_images, shape=fn.stack(image_size, -1))    
    resized = fn.resize(images, device="gpu", resize_shorter=256.0)          
    output = fn.crop_mirror_normalize(
        resized, dtype=types.FLOAT, crop=(224, 224), mean=[0.0, 0.0, 0.0], std=[1.0, 1.0, 1.0]
    )                                                                         
    pipe.set_outputs(output, image_size)

    pipe.build()
pipe_out = pipe.run()
```
And now the size unmatch error I get:
```
  File "/mnt/lustre-grete/usr/user/scripts/tfrecord/TFrecord.py", line 47, in <module>
    images = fn.reshape(raw_images, shape=fn.stack(image_size, -1))   

encountered:

Assert on "input_i.type() == dtype && input_i.shape().sample_dim() == ndim" failed: All inputs must have the same type and number of dimensions.
input #0: int64, 1-D

input #1: int32, 0-D.
C++ context: [/opt/dali/dali/operators/generic/join.cc:77] 
```

**Comment by JanuszL** [comment]
Hi @zmasih,

Please use [the `cast` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.cast.html) - `fn.cast(-1, dtype=types.INT64` (assuming that the `size` is one of the image dimensions, while the other can be inferred and the image has one channel).

**Comment by zmasih** [comment]
Thank you. That also did not work. Please help me understand how DALI works.
My understanding is that for decoding 'tfrecord  2D images', I need to pass inputs["image"] and also shape=(dim1,dim2). But  I had a deeper look into the generating code, and I found out that size is the multiplication of the dimensions. Now I don't know how to define shape, while I don't have the dimensions. 
I mean, stack or cast are not the proper functions in my case, Is my understanding correct? please guide me. 
with fn.cast(-1, dtypes=types.INT64) I get the following error:
```
  File "/mnt/lustre-grete/usr/user/scripts/tfrecord/TFRecord.py", line 39, in <module>
    shape = fn.stack(image_size, fn.cast(-1, dtype=types.INT64))

encountered:

Assert on "input_i.type() == dtype && input_i.shape().sample_dim() == ndim" failed: All inputs must have the same type and number of dimensions.
input #0: int64, 1-D

input #1: int64, 0-D.
```

**Comment by JanuszL** [comment]
hi @zmasih,

> But I had a deeper look into the generating code, and I found out that size is the multiplication of the dimensions. Now I don't know how to define shape, while I don't have the dimensions.

In that case, if there is no shape I don't know how to restore it. Usually either you store encoded images and the particular format (like JPEG) is responsible for the shape, or you have raw data (pixels) and shape stored as another field in the TF Record.
Do you know how this data is consumed in the code without DALI?

>  mean, stack or cast are not the proper functions in my case, Is my understanding correct? please guide me.
with fn.cast(-1, dtypes=types.INT64) I get the following error:

You can also add a dimension to the data using reshape but this is a secondary problem now.

**Comment by zmasih** [comment]
The following is how the dataset is consumed:
```
class TFDataLoader(BaseDataLoader):

    @dlp.log_init
    def __init__(self, format_type, dataset_type, epoch):
        super().__init__(format_type, dataset_type, epoch, DataLoaderType.TENSORFLOW)
        self._dataset = None

    @dlp.log
    def read(self):
        read_threads = self._args.read_threads
        if read_threads == 0:
            if self._args.my_rank == 0:
                logging.warning(
                    f"{utcnow()} `read_threads` is set to be 0 for tf.data loader. We change it to 1")
            read_threads = 1

        options = tf.data.Options()
        if "threading" in dir(options):
            options.threading.private_threadpool_size = read_threads
            options.threading.max_intra_op_parallelism = read_threads
        elif "experimental_threading" in dir(options):
            options.experimental_threading.private_threadpool_size = read_threads
            options.experimental_threading.max_intra_op_parallelism = read_threads
        if self.format_type != FormatType.TFRECORD:
            self._dataset = tf.data.Dataset.from_tensor_slices(np.arange(read_threads)).with_options(options)
            self._dataset = self._dataset.interleave(lambda x: TensorflowDataset(self.format_type, self.dataset_type,
                                                                                self.epoch_number, (
                                                                                self.batch_size,
                                                                                self._args.max_dimension,
                                                                                self._args.max_dimension), x),
                                                                                cycle_length=read_threads,
                                                                                num_parallel_calls=read_threads)
            if self._args.prefetch_size > 0:
                self._dataset = self._dataset.prefetch(buffer_size=self._args.prefetch_size)
        else:
            self._dataset = ReaderFactory.get_reader(type=self.format_type,
                                          dataset_type=self.dataset_type,
                                          thread_index=-1,
                                          epoch_number=self.epoch_number).next()
```

**Comment by JanuszL** [comment]
And do you know which reader is selected in the case of your dataset?

**Comment by zmasih** [comment]
> Hi [@zmasih](https://github.com/zmasih),
> 
> Please use [the `cast` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.cast.html) - `fn.cast(-1, dtype=types.INT64` (assuming that the `size` is one of the image dimensions, while the other can be inferred and the image has one channel).

Hi @JanuszL 
with the assumption size to be the square of dimensions, I tried:
 
   `     shape = fn.stack(fn.cast(nvidia.dali.math.sqrt(inputs["size"], dtype=types.INT64), fn.cast(-1,dtype=types.INT64))`

And I got a dimension error:
```
    shape = fn.stack(nmath.sqrt(image_size), fn.cast(-1,dtype=types.FLOAT))
encountered:
Assert on "input_i.type() == dtype && input_i.shape().sample_dim() == ndim" failed: All inputs must have the same type and number of dimensions.
input #0: float, 1-D

input #1: float, 0-D.
```
Then I tried to change the dimension:

`        shape = fn.stack(fn.cast(nmath.sqrt(image_size),dtype=types.INT64), fn.reshape(fn.cast(-1,dtype=types.INT64), src_dims=[-1]))`
and I got this error:

```
    image = fn.reshape(inputs["image"], shape)
encountered:
Assert on "shape.sample_dim() == 1 || (shape.sample_dim() == 2 && shape.num_samples() == 1)" failed: shape input must be a list of 1D tensors or a single 2D tensor
```
What is the correct way to address the dimension?

**Comment by zmasih** [comment]
@JanuszL Thank you for the reply. 
With that now I get another error, with both reshape and reinterpret:
`  image = fn.reinterpret(raw_images, shape=shape)`

```
encountered:

Assert on "actual_volume * input_element_size == requested_volume * output_element_size" failed: Input and output samples must occupy the same size in bytes.
Sample index:     0
Actual volume:    114244
     in bytes:    114244
Requested volume: 114228
     in bytes:    114228
Input shape:	114244
Requested shape:	18 x 6346
 ```

**Comment by JanuszL** [comment]
Apparently the underlying data volume is different than the one that comes from the reshape arguments. Can you check this?

**Comment by zmasih** [comment]
@JanuszL 
Do you mean the volume of inputs[image]? Does the following answer?
```
   actual_shape = fn.shapes(inputs["image"])

   print(f"Actual shape of raw_images: {actual_shape}")

   expected_shape = fn.cat(dim, fn.reshape(fn.cast(-1, dtype=types.INT64), src_dims=[-1]))

   print(f"Expected shape: {expected_shape}")

  ```
Actual shape of raw_images: DataNode(name="__Shapes_7", device="cpu, source="<nvidia.dali.ops._OperatorInstance object at 0x1468b567b210>")

Expected shape: DataNode(name="__Cat_13", device="cpu, source="<nvidia.dali.ops._OperatorInstance object at 0x1468b569c750>")
_

**Comment by JanuszL** [comment]
I'm afraid you need to return these data as the pipeline output. Now you only see an operator (`DataNode`) properties.

**Comment by zmasih** [comment]
Thank you for your help. I took them out of the pipeline. They are different, but how can I align then? 
```
    raw_images = inputs["image"]
    image_size = inputs["size"]

    actual_shape = fn.shapes(inputs["image"])
    dim=fn.cast(nmath.sqrt(image_size),dtype=types.INT64)
    shape = fn.cat(dim, fn.reshape(fn.cast(-1, dtype=types.INT64), src_dims=[-1]))
```
OUTPUT:
```
Raw images shape: (16, 114244)
Calculated dimensions: [[18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]
 [18]]
Shape tensors: [[18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]
 [18 -1]]
```

**Comment by JanuszL** [comment]
I don't think that `18` is a square root of `114244`, do you use [DALI math op](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/math.html#nvidia.dali.math.sqrt) to calculate it?

**Comment by zmasih** [comment]
yes, I used nvidia.dali.math.sqrt.

**Comment by JanuszL** [comment]
Can you just return the value of ` nvidia.dali.math.sqrt` to see if that is the case?

**Comment by zmasih** [comment]
I printed out all the steps, for batch size =4. 
```
Raw images shape: (4, 114244)
raw images array: [[  6 225  55 ... 115 174 253]
 [208  67 173 ... 138 132  53]
 [ 15  79  66 ... 129  45 222]
 [249 136  66 ... 195   1 105]]
**********************
Image sizes array: [[338]
 [338]
 [338]
 [338]]
Image size shape: (4, 1)
**********************
Calculated dimensions: TensorListCPU(
    [[18]
     [18]
     [18]
     [18]],
    dtype=DALIDataType.INT64,
    num_samples=4,
    shape=[(1,), (1,), (1,), (1,)])
Calculated dimensions: [[18]
 [18]
 [18]
 [18]]
square root of image_size: TensorListCPU(
    [[18.384777]
     [18.384777]
     [18.384777]
     [18.384777]],
    dtype=DALIDataType.FLOAT,
    num_samples=4,
    shape=[(1,), (1,), (1,), (1,)])
**********************
Shape tensors: TensorListCPU(
    [[18 -1]
     [18 -1]
     [18 -1]
     [18 -1]],
    dtype=DALIDataType.INT64,
    num_samples=4,
    shape=[(2,), (2,), (2,), (2,)])
```
At the end
```
reshaped_imgs = fn.reinterpret(raw_images, shape=shape)
shape= fn.cat(dim, fn.reshape(fn.cast(-1, dtype=types.INT64), src_dims=[-1]))
```
produces error:
```
Actual volume:    114244
     in bytes:    114244
Requested volume: 114228
     in bytes:    114228
Input shape:	114244
Requested shape:	18 x 6346
```
It looks that the procedure is correct and logical, but: 
actual volume = 114244=18 * 6346.8888889, whereas reshaping demands an integer, so the requested volume is 18 * 6346=114228

**Comment by JanuszL** [comment]
I'm a bit confused, sqrt(114244) is 338, and I don't know why you calculate the square root again from it to get 18?
It seems that the image should be reshaped to [338, 338] not [18 x 6346].
