### ISSUE TITLE
Named argument inputs to operators must be CPU data nodes

### ISSUE THREAD

**Issue by zmasih** [NVIDIA/DALI#5759]
### Describe the question.

Hello. 
I am executing the following code:
```
pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
with pipe:
    inputs = fn.readers.tfrecord(
        path=data_path,
        index_path=idx_path,

        features={
            "image": tfrec.FixedLenFeature((), tfrec.string, ""),
            "size": tfrec.FixedLenFeature([1], tfrec.int64, 0),
        },
    )
    raw_images = inputs["image"]
    image_size = inputs["size"]

    shape = fn.cat(image_size, fn.reshape(fn.cast(-1, dtype=types.INT64), src_dims=[-1]), device="mixed")
    reshaped_imgs = fn.reinterpret(raw_images, shape=shape,device = "gpu")
    reshaped_imgs_with_channel = fn.reshape(reshaped_imgs, shape=[338, 338, 1], layout="HWC",device="gpu")

    pipe.set_outputs(reshaped_imgs_with_channel, image_size)

    pipe.build()
pipe_out = pipe.run()
```
And I'm getting this error: 
```
Traceback (most recent call last):
  File "/mnt/lustre-grete/usr/user/scripts/tfrecord/ResnetTFrecord.py", line 49, in <module>
    pipe.build()
  File "/user/zmasih/user/.conda/envs/mpi4py/lib/python3.11/site-packages/nvidia/dali/pipeline.py", line 1032, in build
    self._init_pipeline_backend()
  File "/user/zmasih/user/.conda/envs/mpi4py/lib/python3.11/site-packages/nvidia/dali/pipeline.py", line 884, in _init_pipeline_backend
    related_logical_id[op.relation_id] = self._pipe.AddOperator(op.spec, op.name)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in GPU operator `nvidia.dali.fn.reinterpret`,
which was used in the pipeline definition with the following traceback:

  File "/mnt/lustre-grete/usr/user/scripts/tfrecord/ResnetTFrecord.py", line 40, in <module>
    reshaped_imgs = fn.reinterpret(raw_images, shape=shape,device = "gpu")

encountered:

Error while specifying argument 'shape'. Named argument inputs to operators must be CPU data nodes. However, a GPU data node was provided.
C++ context: [/opt/dali/dali/pipeline/pipeline.cc:382] 
```
The code works only if I put all the tree devices to CPU. I'm using Cuda 12.4.

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @zmasih,

Thank you for reaching out.
Can you try:
```
shape = fn.cat(image_size, fn.reshape(fn.cast(-1, dtype=types.INT64), src_dims=[-1]), device="cpu")
```
To make sure that the shapes you are providing to the `reinterpret` operator are on the CPU?

**Comment by zmasih** [comment]
Thanks for the reply. For the following, I still have an error.
```
shape = fn.cat(image_size, fn.reshape(fn.cast(-1, dtype=types.INT64), src_dims=[-1]), device="cpu")
reshaped_imgs = fn.reinterpret(raw_images, shape=shape,device = "cpu")
reshaped_imgs_with_channel = fn.reshape(reshaped_imgs, shape=[338, 338, 1], layout="HWC",device="mixed")
```
```
Traceback (most recent call last):
  File "/mnt/lustre-grete/usr/user/scripts/tfrecord/ResnetTFrecord.py", line 50, in <module>
    pipe.build()
  File "/user/zmasih/user/.conda/envs/mpi4py/lib/python3.11/site-packages/nvidia/dali/pipeline.py", line 1035, in build
    self._pipe.Build(self._generate_build_args())
RuntimeError: Critical error when building pipeline:
Error in MIXED operator `nvidia.dali.fn.reshape`,
which was used in the pipeline definition with the following traceback:

  File "/mnt/lustre-grete/usr/user/scripts/tfrecord/ResnetTFrecord.py", line 43, in <module>
    reshaped_imgs_with_channel = fn.reshape(reshaped_imgs, shape=[338, 338, 1], layout="HWC",device="mixed")

encountered:

Assert on "creator_it != registry_.end()" failed: Operator "Reshape" not registered for mixed.
```

**Comment by JanuszL** [comment]
You should not use `mixed` backend for [the `fn.reshape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.reshape.html):
![Image](https://github.com/user-attachments/assets/c4d8ae16-3259-4457-9833-8345eb67f8ec)
 If you want to move the data to the GPU please:
```
reshaped_imgs_with_channel = fn.reshape(reshaped_imgs.gpu(), shape=[338, 338, 1], layout="HWC")
```
