### ISSUE TITLE
curlCode: 60, SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by weiji14** [NVIDIA/DALI#5762]
### Version

1.44.0

### Describe the bug.

Trying to read JPEG files from an s3 bucket, but getting some authentication related errors. Accessing the files using `aws s3 ls` works ok though (after I set some `AWS_*` environment variables). Is there some way I can pass through credentials/settings needed to access images in a non-public-facing bucket?

### Minimum reproducible example

```python
from nvidia.dali import fn
from nvidia.dali.pipeline import pipeline_def

@pipeline_def
def simple_pipeline(files):
    jpegs, _labels = fn.readers.file(files=files, name="Reader")
    return jpegs

files = ["s3://<bucket-name>/<folder-name>/<image_name>.jpeg"]
pipe = simple_pipeline(files=files, batch_size=2, num_threads=1, device_id=0)
pipe.build()

pipe_out = pipe.run()
print(pipe_out)
```

### Relevant log output

```python-traceback
Traceback (most recent call last):
  File "/home/ubuntu/project/temp.py", line 17, in <module>
    pipe_out = pipe.run()
               ^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.12/site-packages/nvidia/dali/pipeline.py", line 1396, in run
    return self.outputs(cuda_stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.12/site-packages/nvidia/dali/pipeline.py", line 1205, in outputs
    return self._outputs(cuda_stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.12/site-packages/nvidia/dali/pipeline.py", line 1314, in _outputs
    return self._pipe.Outputs(types._raw_cuda_stream_ptr(cuda_stream))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Critical error in pipeline:
Error in CPU operator `nvidia.dali.fn.readers.file`,
which was used in the pipeline definition with the following traceback:

  File "/home/ubuntu/project/temp.py", line 10, in simple_pipeline
    jpegs, _labels = fn.readers.file(files=files, name="Reader")

encountered:

S3 Object not found. bucket=<bucket-name> object=<folder-name>/<image-name>.jpeg:
: curlCode: 60, SSL peer certificate or SSH remote key was not OK
Current pipeline object is no longer valid.
```

### Other/Misc.

Have tried looking at some Stackoverflow answers (e.g. at https://serverfault.com/questions/469824/curl-disable-certificate-verification), but they don't seem to work. A little unsure if it's something I need to resolve with `curl` or something in DALI.

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @weiji14,

Thank you for reaching out. DALI uses [AWS SDK](https://github.com/aws/aws-sdk-cpp), please check [this short guide](https://github.com/aws/aws-sdk-cpp/blob/main/docs/Credentials_Providers.md#credentials-providers) on how to set creds to it. It shouldn't be any different from your current approach with `aws s3`.

**Comment by jantonguirao** [comment]
We rely on the default credentials provider chain by AWS SDK, as Janusz mentioned.
Other than the AWS SDK environment variables, we expose AWS_ENDPOINT_URL to control the endpoint URL. 
So, for example, you could set your credentials via environment variable:
```
export AWS_ENDPOINT_URL="your-endpoint-url"
export AWS_ACCESS_KEY_ID="your-access-key-id"
export AWS_SECRET_ACCESS_KEY="your-secret-access-key"
export AWS_REGION="your-region"
```

**Comment by weiji14** [comment]
Hmm, what version of [AWS SDK CPP](https://github.com/aws/aws-sdk-cpp) is DALI 1.44.0 using? I'm thinking if this might be a case of https://github.com/aws/aws-sdk-cpp/issues/2908, because I've set `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_REGION` and got `aws s3 ls` to work, but the DALI pipeline script ran in the same terminal is still returning `curlCode: 60, SSL peer certificate or SSH remote key was not OK`. It might well be some certificate issue that `libcurl` is more sensitive to.

**Comment by jantonguirao** [comment]
It uses aws-sdk-cpp [1.11.418](https://github.com/aws/aws-sdk-cpp/tree/1.11.418) version.
One idea would be to recompile DALI enabling debug logs for AWS SDK to see if you get a more detailed message.

**Comment by JanuszL** [comment]
Hi @apocrf,

> I encountered the same issue. Could it be related to third-party S3 buckets not being supported in aws-sdk-cpp? Please see https://github.com/aws/aws-sdk-cpp/issues/2992#issuecomment-2233841185 for reference.

I guess it could be it.

> I tested the code on my MinIO instance and it worked as expected. Could you please advise on any workarounds?

I'm afraid nothing comes to my mind besides trying out what is described in https://github.com/aws/aws-sdk-cpp/issues/2908.
If there is a way we can test this on our own this could help with debugging.

**Comment by weiji14** [comment]
@apocrf, there's some ideas at https://github.com/apache/arrow/issues/37001 about setting `SSL_CERT_FILE` and an endpoint override (`AWS_ENDPOINT_URL`?) that might be helpful for your case?

It looks like https://github.com/aws/aws-sdk-cpp/pull/3349 has been merged which includes [`CURLOPT_ERRORBUFFER`](https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html). Could we get DALI to upgrade to upgrade to [aws-sdk-cpp=1.11.530](https://github.com/aws/aws-sdk-cpp/releases/tag/1.11.530) or above to get a more meaningful error message? I see at https://github.com/NVIDIA/DALI_deps/tree/v1.48.0 that `aws_sdk_cpp=1.11.515` is being used.

**Comment by jantonguirao** [comment]
> Could we get DALI to upgrade to [aws-sdk-cpp=1.11.530](https://github.com/aws/aws-sdk-cpp/releases/tag/1.11.530) or above to get a more meaningful error message? I see at https://github.com/NVIDIA/DALI_deps/tree/v1.48.0 that aws_sdk_cpp=1.11.515 is being used.

Sure. We regularly upgrade dependencies once a month or so.

**Comment by apocrf** [comment]
Hi, everyone!

We discovered that the SSL error we encountered with third-party buckets was triggered during SSL verification. We successfully worked around it by setting

```cpp
config.verifySSL = false
```
in S3ClientManager(). We have opened a [PR](https://github.com/NVIDIA/DALI/pull/5907) with this change.

**Comment by JanuszL** [comment]
@apocrf thank you for your contribution. I have added small comments. Please check them.
