### ISSUE TITLE
CPU version of `CropMirrorNormalize` ignores `crop_pos_x` and `crop_pos_y` options

### ISSUE THREAD

**Issue by hyabe** [NVIDIA/DALI#813]
When I run [`CropMirrorNormalize`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.CropMirrorNormalize) on CPU, it always returns the top-left region of original image even when `crop_pos_x`/`crop_pos_y` has non-zero value.

It reproduces on DALI 0.8.1/CUDA 9.2/CentOS 7.5 with the following code, which extracts rightmost 1/3 region from an image like French-flag and checks if the region is red:
```
import sys
import tempfile

import PIL.Image
import nvidia.dali as dali
import numpy as np


class ExtractRightmostOneThirdPipeline(dali.pipeline.Pipeline):
    """A DALI-pipeline which reads ImageNet like dataset and crop top-right 100x100 image"""
    def __init__(self, list_file: str, use_gpu: bool):
        super(ExtractRightmostOneThirdPipeline, self).__init__(batch_size=1, num_threads=1, device_id=0)
        self._reader = dali.ops.FileReader(file_root='/', file_list=list_file)
        self._decoder = dali.ops.HostDecoder()
        self._cropper = dali.ops.CropMirrorNormalize(
            # crop rightmost 100x100 from 300x100 image
            crop=[100,100], crop_pos_x=1, crop_pos_y=0,
            mean=0, std=1, device='gpu' if use_gpu else 'cpu')

    def define_graph(self):
        bytes, labels = self._reader()
        images = self._decoder(bytes)
        if self._cropper.device != 'cpu':
            images = images.gpu()
        images = self._cropper(images)
        return images, labels


def prepare_data(root_dirname: str):
    """Create an ImageNet-like data directory with only one 300x100 image, which looks like French flag"""

    image = np.zeros([100,300,3], dtype=np.uint8)
    image[:,:100,:] = [ 0, 0, 255 ]
    image[:,100:200,:] = [ 255, 255, 255]
    image[:,200:,:] = [ 255, 0, 0 ]
    image = PIL.Image.fromarray(image)
    #image.show()

    with tempfile.NamedTemporaryFile(mode='wb', dir=root_dirname, suffix='.png', delete=False) as image_file,\
         tempfile.NamedTemporaryFile(mode='w', dir=root_dirname, suffix='.txt', delete=False) as list_file:
        image.save(image_file, format='PNG')
        list_file.write(f'{image_file.name} 0\n')

    return list_file.name


if __name__ == '__main__':
    print(f'Python: {sys.version_info}')
    print(f'DALI: {dali.__version__}')

    with tempfile.TemporaryDirectory() as root_dirname:
        list_filename = prepare_data(root_dirname)

        print('testing GPU version...')
        p_gpu = ExtractRightmostOneThirdPipeline(list_filename, True)
        p_gpu.build()
        images, labels = p_gpu.run()
        # all pixels have the same color and...
        np.testing.assert_equal(images.as_cpu().at(0).var(axis=(1,2)), [0,0,0])
        # ...it is red (i.e. (255,0,0))
        np.testing.assert_equal(images.as_cpu().at(0).mean(axis=(1,2)), [255,0,0])

        print('testing CPU version...')
        p_cpu = ExtractRightmostOneThirdPipeline(list_filename, False)
        p_cpu.build()
        images, labels = p_cpu.run()
        # all pixels have the same color and...
        np.testing.assert_equal(images.at(0).var(axis=(1,2)), [0,0,0])
        # ...it is red (i.e. (255,0,0))
        np.testing.assert_equal(images.at(0).mean(axis=(1,2)), [255,0,0])
```

And the following is my result, GPU version is okay but CPU version returns blue (`[0, 0, 255]`) region:
```
Python: sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
DALI: 0.8.1
testing GPU version...
testing CPU version...
Traceback (most recent call last):
  File "test.py", line 70, in <module>
    np.testing.assert_equal(images.at(0).mean(axis=(1,2)), [255,0,0])
  File "/home/XXXXXXXX/anaconda3/envs/work/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 348, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/home/XXXXXXXX/anaconda3/envs/work/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 896, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/XXXXXXXX/anaconda3/envs/work/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 819, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatch: 66.7%
Max absolute difference: 255.
Max relative difference: nan
 x: array([  0.,   0., 255.], dtype=float32)
 y: array([255,   0,   0])
```

**Comment by szalpal** [comment]
Hi @hyabe !
Correct me if I'm wrong:

**Comment by szalpal** [comment]
Hi @hyabe !
Please correct me if I'm wrong. In the following snippet:
```
        self._cropper = dali.ops.CropMirrorNormalize(
            # crop rightmost 100x100 from 300x100 image
            crop=[100,100], crop_pos_x=1, crop_pos_y=0,
            mean=0, std=1, device='gpu' if use_gpu else 'cpu')
```
You used `crop_pox_x=1` and `crop_pos_y=0`. That means, that starting position of your crop is in top-right corner of the image. Shouldn't you pass `crop_pos_x=0.66` and `crop_pod_y=0` if you want to crop the rightmost 1/3 of the image?

**Comment by JanuszL** [comment]
It seems that CropMirrorNormalize doesn't use crop_pos_x and crop_pos_y at all. Added as a bug and tracked as DALI-759.

**Comment by hyabe** [comment]
@szalpal @JanuszL, thank you for your comments.

I confirmed the followings:
1. even when I change `crop_pos_x=1` to `crop_pos_x=2/3`, CPU version returned leftmost blue region (and GPU version returned 2/3-white&1/3-red region)
2. extracting rightmost region for `crop_pos_x=1` seems to be correct, as [the document](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.CropMirrorNormalize) states `crop_pos_x` is relative to “(_W_ - _crop_W_), where... _W_ is the width of the image and _crop_W_ is the width of the cropping window”
3. when I switched from `CropMirrorNormalize` to [`Crop`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.Crop), both CPU and GPU versions returned red-regions

I guess this is one of causes of #560 as this:
 * turns off random cropping during training and
 * evaluates accuracy using top-left region instead of the center.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/853 should fix this problem

**Comment by hyabe** [comment]
I'm sorry for taking time to respond.
The release-0.10.0 works well for me.
Thank you very much for the fix.

**Comment by JanuszL** [comment]
:+1:
